### ISSUE TITLE
Passing invalid parameter results in KeyNotFoundException even though tests run just fine

### ISSUE THREAD

**Issue by moozzyk** [xunit/xunit#672] opened 2015-11-11 23:46 UTC
`dnx test -xxxx xxxx` results in the exception below. Note that tests were executed correctly. 

```
PS C:\source\HelloAspNet5\test\HelloAspNet5Tests> dnx test -xxxx xxxx
xUnit.net DNX Runner (32-bit DNXCore 5.0)
  Discovering: HelloAspNet5Tests
  Discovered:  HelloAspNet5Tests
  Starting:    HelloAspNet5Tests
    HelloWorld.ClassTests.ReturnNumber_returns_number_failing [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   42
      Stack Trace:
        C:\source\HelloAspNet5\test\HelloAspNet5Tests\ClassTests.cs(26,0): at HelloWorld.ClassTests.ReturnNumber_returns_number_failing()
  Finished:    HelloAspNet5Tests
=== TEST EXECUTION SUMMARY ===
   HelloAspNet5Tests  Total: 5, Errors: 0, Failed: 1, Skipped: 0, Time: 0.178s
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Xunit.Runner.Dnx.TransformFactory.<>c__DisplayClass5_0.<GetXmlTransformers>b__1(XElement xml)
   at Xunit.Runner.Dnx.Program.RunProject(XunitProject project, Nullable`1 parallelizeAssemblies, Nullable`1 parallelizeTestCollections, Nullable`1 maxThreadCount, Boolean diagnosticMessages, Boolean noColor, Boolean designTime, Boolean list, IReadOnlyList`1 designTimeFullyQualifiedNames)
   at Xunit.Runner.Dnx.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
PS C:\source\HelloAspNet5\test\HelloAspNet5Tests>  $lastexitcode
1
```

Seems similar to https://github.com/xunit/xunit/issues/653

**Comment by bradwilson** [comment] 2015-11-11 23:52
It's not similar to, it's a duplicate of it. :)

**Closed by bradwilson** 2015-11-11 23:52 UTC
Labels: [a] dnx.xunit, [r] Duplicate
