### ISSUE TITLE
Suggestion: Assert.Equals( ) for JSON objects

### ISSUE THREAD

**Issue by wizofaus** [xunit/xunit#2063] opened 2020-02-10 08:04 UTC
I write a lot of unit/integration tests that basically are about testing that a server is returning the expected JSON for a particular set of conditions.
Many of these tests consist of lots of asserts on all the individual key bits of data, but having also worked on a similar NodeJS project that used a simple "deep-equals" assert for every test, it's hard to not to wish for something similar in Xunit.
I'm still on .NET 2.1 so using Newtonsoft Json.Net, and did try using `Assert.True(JToken.DeepEquals(expected, actual))` but it's hopeless for determining why exactly the tests have failed.
I've thrown together my own rough version again for Json.net, and the key thing is having it clearly point out *where* the difference between two potentially large/complex objects.
I haven't used the new .NET 3.0 Json library enough to know how different it would need to be but I can understand it would make more sense to support that than Newtonsoft (though switching away from Newtonsoft would surely be a big change for many codebases).
 
An example of the sort of thing I mean might look like:

```
async Task GetUser_WithValidId_ShouldReturnExpectedResult()
{
    var response = await client.GetAsync("/api/user/123");
    var parsed = JToken.Parse(await response.ReadAsStringAsync());

    Assert.Equal(parsed, JToken.FromObject(new { firstName = "Joe", lastName = "Bloggs", age = 41, 
children = new [] { firstName = "Sally", lastName = "Bloggs", age = 13 }));
}
```

And if, for instance, the age of Sally Bloggs came back incorrectly, it might say

Assert.Equals() Failure for children[0].age
Actual: 12
Expected: 13

**Comment by bartelink** [comment] 2020-02-10 08:27
I've used jsondiffpatch.net to generate a diff, and then assert that the diff is empty.
The other requirement/desire I'd have is to be able to compare JSON objects as strings, UTF8, STJ or json.net against any other form of them
The problem is that these things change (and are some distance from the core aims of xUnit), so it'd be a really useful extension, but certainly not something that should be in the core xUnit library. I guess that doesn't completely rule out the project shipping alongside other xUnit libs - the main requirement is someone to build it...

**Comment by bradwilson** [comment] 2020-02-10 15:11
I believe this is probably a dupe of #1604

**Comment by tmort93** [comment] 2020-05-13 14:06
@wizofaus 

> I write a lot of unit/integration tests that basically are about testing that a server is returning the expected JSON for a particular set of conditions.

We do the same thing. I recommend [Snapshooter](https://swisslife-oss.github.io/snapshooter/). Conceptually based on Jest snapshot testing, with some caveats (which I prefer).

**Comment by bjartwolf** [comment] 2020-05-29 08:29
Still in alpha, but maybe you could try this @wizofaus ? I am sure be interested in feedback on it! https://github.com/nrkno/Quibble.Xunit

**Closed** 2020-07-27 05:28 UTC
Labels: status: Duplicate

**Comment by lateapexearlyspeed** [comment] 2024-03-10 05:10
Hi, it is 2024 now and there is a Xunit assertion json extension package which can do json-related assertion, not only 'Equals' you mentioned, but also other assertion requirement methods, against any json node location. Hope can try it and thanks for feedback !
https://github.com/lateapexearlyspeed/Lateapexearlyspeed.JsonSchema
