### ISSUE TITLE
Invalid "xUnit1000: Test classes must be public" on partial classes

### ISSUE THREAD

**Issue by tristanlabelle** [xunit/xunit#1844] opened 2018-10-27 18:55 UTC
The `Xunit.Analyzers.TestClassMustBePublic` analyzer reports an error on this:

```
public partial class Test { }
partial class Test { [Fact] public static void Foo() { } }
```

The resulting `Test` class is clearly public, but xUnit apparently only checks the visibility of the current partial declaration, resulting in an incorrect error being reported.

**Comment by voroninp** [comment] 2022-05-29 09:16
By the way, @bradwilson , is the requirement for test classes to be public externally enforced, or is it just the design choice of xUnit authors?

**Comment by bradwilson** [comment] 2022-05-29 18:18
We chose to only support public classes because private reflection is (at least was) extremely slow: not just mechanically slow, but also because it would dramatically increase the number of types we'd have to search.

**Comment by voroninp** [comment] 2022-05-29 18:37
And are there any plans to use source generators which will enumerate test classes/methods at the build phase?

**Comment by bradwilson** [comment] 2022-05-29 19:54
No current plans.

**Comment by bjornhellander** [comment] 2022-07-16 13:41
Unable to reproduce this. Looks like a duplicate of #1602, which has already been fixed.

**Comment by bradwilson** [comment] 2022-07-19 16:35
Agreed, this does appear to be a dup. Closing.

**Closed by bradwilson** 2022-07-19 16:35 UTC
Labels: type: Bug, help wanted, area: Analyzers, good first issue
