### ISSUE TITLE
Weirdness in parameter conversion (InlineData)

### ISSUE THREAD

**Issue by JulianBirch** [xunit/xunit#2572] opened 2022-08-16 10:11 UTC
I don't know if this qualifies as a bug or not, but

```
    [Theory]
    [InlineData(3)] // Passes
    [InlineData(3.0)] // Passes
    public void NotNullTest(double x)
    {
        Assert.Equal(x, 3);
    }

    [Theory]
    [InlineData(3)] // Fails
    [InlineData(3.0)] // Passes
    public void NullableTest(double? x)
    {
        Assert.Equal(x, 3);
    }
```

FWIW, I _think_ the behaviour might have changed between 2.4.1 and 2.4.2.

Running 6.0.302, because it's looking like this behaviour might also be minor-version sensitive.

**Comment by JulianBirch** [comment] 2022-08-18 11:59
Confirmed: doing the same thing with an `int` to `long?` works on 302, but not on 202.

**Comment by ilya-scale** [comment] 2022-08-29 12:01
I have a similar problem on 2.4.2 that can very well be connected to this, when I have `InlineData(1)` and the argument is `long? value`, the conversion fails saying that Int.32 cannot be converted to nullable Int.64.

Additionally `Assert.Equal` stopped figuring out nullability for `IEnumerable<SomeType>? obj`, it just fails during compilation for the line `Assert.Equal(obj, obj1);` and says that it expects non-nullable objects.

**Comment by Kampfmoehre** [comment] 2022-09-16 17:38
I have a similar problem where I can no longer run this test:
```cs
[Theory]
[InlineData(null, 0)]
public void TestSomething(double? value, uint expected)
{
  uint actual = Something(value);
  actual.Should().Be(expected);
}
```

I receive the following error with stacktrace
```
  Error Message:
   System.ArgumentException : Object of type 'System.Int32' cannot be converted to type 'System.Nullable`1[System.Double]'.
  Stack Trace:
     at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(StackAllocedArguments& stackArgs, ReadOnlySpan`1 parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
--- End of stack trace from previous location ---
```

This is failing with the update to Xunit 2.4.2, with 2.4.1 it still works flawlessly.

We are using `dotnet test` with `xunit.runner.visualstudio` 2.4.5 on Linux machines if that matters somehow.

**Comment by jzabroski** [comment] 2022-09-27 22:03
I believe this is caused by a combination of two bug fixes in 2.4.2 : #2401 (Fixed in #2417 ) and #2418 , where I left a comment : https://github.com/xunit/xunit/issues/2418#issuecomment-1260088208

**Comment by jzabroski** [comment] 2022-09-27 22:16
This error can also happen in the correct scenario where it should raise (but arguably should explain to the users which values are converted incorrectly) but wasn't raising in 2.4.1:

```c#
[Theory]
[InlineData(0.0)] // works in 2.4.1! failed in 2.4.2 (which I argue is correct behavior)
[InlineData(1)]
public TestIntWithDouble(int val)
{
  Assert.True(val is int); // pointless jibber jabber
}
```

**Comment by JulianBirch** [comment] 2022-10-07 18:21
The thing is, you want the conversion to happen. Otherwise it makes it really awkward to work with e.g. decimals which can't be set up in an attribute.

**Comment by bradwilson** [comment] 2023-01-22 23:47
This behavior is by design.

The only officially supported way to get a `decimal` value into a theory is via some other data provider besides `InlineData`, since Microsoft chooses not support decimal values in attributes.

**Closed by bradwilson** 2023-01-22 23:47 UTC

**Comment by jzabroski** [comment] 2023-01-23 15:09
@bradwilson This issue has absolutely nothing to do with decimals. The OP made a misleading comment about decimals that doesn't make any sense, otherwise the word decimal never even appears in this issue.

I put together a repro here: 

https://github.com/xunit/xunit/issues/2572#issuecomment-1260112341

**Comment by bradwilson** [comment] 2023-01-25 03:42
@jzabroski I understand it's not related to decimals; it's related to how data types are converted. Unfortunately, this behavior (the silent conversion between types) was unintended. What we have now matches the behavior of the .NET framework code itself, which is what was always what was intended. As such, this is a "by design" closure.

**Comment by jzabroski** [comment] 2023-01-25 04:10
Sorry, I didn't understand that last point. I think the reason we, users, are complaining this is a bug is because .net documentation explicitly talks about "widening conversion" being safe to perform and the C# compiler allows the following 👍

```c#
double d = 0;
```

Documented here : https://learn.microsoft.com/en-us/dotnet/standard/base-types/conversion-tables#widening-conversions

**Comment by bradwilson** [comment] 2023-01-26 22:34
We aren't a compiler, we're a runtime. The compiler is free to do this, but the runtime does not (to be clear: the .NET runtime, not just xUnit.net).

**Comment by jzabroski** [comment] 2023-01-27 03:26
Expression trees can also be widened, though. So interpreters respect this behavior.
