### ISSUE TITLE
Tests with 11 int parameters fails on M1 Macbook

### ISSUE THREAD

**Issue by jnysteen** [xunit/xunit#2495] opened 2022-03-02 21:33 UTC
I am experiencing tests that fails, seemingly just because they have 11 parameters, and run on an M1 Macbook. Other tests, that are completely identical but the amount of parameters, will run just fine.
Also, this only seem to be an issue on M1 Macbooks (my ability for confirming this is limited, though).

I have experimented with adding, removing and changing the types of the input parameters, and almost all combinations run just fine. The clearest distinction between running tests and crashing tests is the number of parameters.

I do not know if this is an error in xUnit or in layers further below, but I hope to get some help for further debugging the issue.

## Steps to reproduce

(the following is what I will report in the issue)

1. Install the .NET 6.0.200 ARM64 SDK on a Mac running on the M1 chip
2. Create a new xUnit test project 
3. Add the following class and contents to the project:

```csharp
using System;
using System.Threading.Tasks;
using Xunit;

namespace DebuggingTestCrashing;

public class DebuggingTestCrashing
{
    [Theory]
    [InlineData(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
    public async Task ElevenParams_Crashes(
        int p1,
        int p2,
        int p3,
        int p4,
        int p5,
        int p6,
        int p7,
        int p8,
        int p9,
        int p10,
        int p11
        )
    {
        Console.WriteLine("test crashes");
    }
}
```

4. Run the tests in the test project using `dotnet test`
5. Watch the test fail with the following exception:

```
The active test run was aborted. Reason: Test host process crashed

Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
```

6. Experiment with adding or removing parameters from the method, and watch the test run just fine.

A repository that can reproduce the exception (and contains other tests, that for some reason do no crash), visit https://github.com/jnysteen/DebuggingTestCrashing.

**Comment by jnysteen** [comment] 2022-03-02 21:34
Details about a setup, where the issue can be reproduced:

### .NET 

```sh
$dotnet --list-sdks
6.0.200 [/usr/local/share/dotnet/sdk]

$dotnet --version
6.0.200

$dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.2
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.200/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.200 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

```

### Hardware

* Model Name:	MacBook Pro
* Model Identifier:	MacBookPro18,1
* Chip:	Apple M1 Pro
* Total Number of Cores:	10 (8 performance and 2 efficiency)
* Memory:	32 GB
* System Firmware Version:	7429.81.3
* OS Loader Version:	7429.81.3

### OS

System Software Overview:

* System Version:	macOS 12.2.1 (21D62)
* Kernel Version:	Darwin 21.3.0

**Comment by jnysteen** [comment] 2022-03-02 21:40
This is from a datacollector log file, where a stacktrace points to `Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection.DataCollectionRequestHandler.<HandleBeforeTestRunStart>b__24_0()`

```
TpTrace Information: 0 : 12111, 7, 2022/03/02, 21:48:02.561, 28387020904166, datacollector.dll, DataCollectionTestCaseEventHandler: Test case 'DebuggingTestCrashing.DebuggingTestCrashing.Params11Ints2DoublesCrashes2(p1: 1, p2: 1, p3: 1, p4: 1, p5: 1, p6: 1, p7: 1, p8: 1, p9: 1, p10: 1, p11: 1, p12: 1, p13: 1) - 50730e24-135c-12d2-a330-2525fa4c421a' started.
TpTrace Information: 0 : 12111, 1, 2022/03/02, 21:48:02.584, 28387044036083, datacollector.dll, DataCollectionRequestHandler.ProcessRequests : Datacollector received message: (DataCollection.AfterTestRunEnd) -> false
TpTrace Error: 0 : 12111, 7, 2022/03/02, 21:48:02.591, 28387050824541, datacollector.dll, DataCollectionRequestHandler.HandleBeforeTestRunStart : Error occurred during initialization of TestHost : System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.ReceiveRawMessage()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.ReceiveMessage()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection.DataCollectionTestCaseEventHandler.ProcessRequests()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection.DataCollectionRequestHandler.<HandleBeforeTestRunStart>b__24_0()
TpTrace Information: 0 : 12111, 1, 2022/03/02, 21:48:02.598, 28387057527333, datacollector.dll, Blame Collector : Session End
```

**Comment by mupuri** [comment] 2022-06-07 21:07
I can confirm that this is happening. Just ran into the same issue on my M1 Macbook.

**Comment by bradwilson** [comment] 2022-07-25 03:02
I cannot reproduce this with:

- `dotnet test` and Visual Studio 2022 against .NET Framework 4.7.2 on Windows 11
- `dotnet test`, VS Code, and Visual Studio 2022 against .NET 6 on Windows 11
- `dotnet test` and VS Code against .NET 6 on Ubuntu 20.04
- `dotnet test` and VS Code against .NET 6 on Intel macOS 12.4

I do not have access to an M1 Mac. My Intel Mac does not have VS Mac installed.

This feels to me like the problem is either with .NET itself on M1 Mac and/or with VS Mac.

**Comment by bradwilson** [comment] 2023-06-11 01:03
I have verified this on an M2 Mac mini, and I am still convinced this is a bug for the .NET team rather than xUnit.net, so I'm closing it.

**Closed by bradwilson** 2023-06-11 01:03 UTC
Labels: status: External
