### ISSUE TITLE
xUnit1013 doesn't work correctly with abstract classes

### ISSUE THREAD

**Issue by mmiller678** [xunit/xunit#1731] opened 2018-06-05 16:37 UTC
When you have an abstract class with a test method decorated with the fact attribute you still receive xUnit1013 saying it should be marked as a fact.

```
public abstract class TestClassBase
{
        [Fact]
        public virtual void DoSomeTest(){ }
}

public class TestClassImplementation : TestClassBase
{
         [Fact]
         public virtual void SomeOtherTestMethod(){ }
}

```
warning xUnit1013: Public method 'DoSomeTest' on test class 'TestClassBase' should be marked as a Fact.

The tests run correctly - however the warning is incorrect and should be corrected.

**Comment by wachulski** [comment] 2018-06-06 10:55
@mmiller678 : I cannot repro the warning just with your snippet. Which version of xunit are you using? Platform/runtime?

BTW - could you make sure a rebuild results with the warning in output?

**Comment by jzabroski** [comment] 2019-04-08 23:03
@wachulski I work with @mmiller678  and think this issue was resolved by either upgrading to v0.10.0 OR by using a TargetFrameworks of net461;netcoreapp2.0 instead of net461;netstandard2.0, or maybe the fact the "Referencing class" TestClassImplementation was in a different assembly and that assembly used the old csproj file format.

I tried to repro the issue just now to see if I could help you clear through your backlog, and can't seem to repro it even looking at our repository's source history around this time.

That said, I 100% remember seeing this error, and recall rebuild not fixing the error.

**Comment by gkarabin** [comment] 2019-11-22 17:40
I see this issue with projects targeting both Xamarin.Android and .NET 4.6.2 (running on MacOS / Xamarin.Android 10.0.6.2, Mono 6.4.0.208).

Example logs:

BaseControllerTest.cs(35,35): Warning xUnit1013: Public method 'controller_can_start' on test class 'BaseControllerTest' should be marked as a Theory. (xUnit1013) (UnitTest.Droid)
BaseControllerTest.cs(35,35): Warning xUnit1013: Public method 'controller_can_start' on test class 'BaseControllerTest' should be marked as a Theory. (xUnit1013) (UnitTest.Win32)

**Comment by jzabroski** [comment] 2019-11-22 18:07
@gkarabin Can you create a repro?  The problem is the last time we reported this we didn't ship a repro, so we have no idea if we just side stepped the bug through refactoring or if it was fixed.

**Comment by gkarabin** [comment] 2019-11-24 02:25
As it turns out, those unit test projects are holdovers from many years ago and remain ToolsVersion csproj file format. Most of the other projects in our solution have since migrate to SDK style cspro, even though we have switched out the package references to PackageReference.

I can see if completing the migration has any impact. I suspect not, because while I see the problem with our large (proprietary) solution that has the problem. If I pare it down to a set of projects and classes with the similar structure and nuget dependencies I don't see the problem.  That pared down solution is still based on ToolsVersion. Still, it's worth a shot and probably good to get off of ToolsVersion.

If changing that makes a difference, I'll post back.

**Comment by jzabroski** [comment] 2022-08-15 23:27
Ran into this xUnit1013 problem again today - but I think it only occurred because I had compiler errors. After resolving the compiler errors, the warning remained. After cleaning out all bin folders and all obj folders, the problem went away. 🤷 

There's some weird stuff sometimes with Roslyn Analyzers.

**Comment by bradwilson** [comment] 2023-06-25 05:59
I am unable to repro this, and based on the conversations, it sounds like it was probably fixed around the time of 0.10.0.

Closing this as already fixed.

**Closed by bradwilson** 2023-06-25 05:59 UTC
Labels: area: Analyzers

**Comment by jzabroski** [comment] 2023-06-25 10:52
It still happens, but only if there is a compiler error. It would be nice to know why it happens, but I think my previous post about clearing out bin and OBJ folders is sufficient clue for those searching online for this error. Agree, it can be closed.

**Comment by Sohra** [comment] 2023-10-18 06:31
In case it helps anyone reading this, I came across this issue today, after upgrading from `2.4.1`, to `2.5.3`.  The abstract methods pointed to were already marked up with a `Fact` attribute.  There were no other errors showing in the solution.

It was caused by the implementations of the abstract fact methods not being marked up with the `Fact` attribute themselves.  I felt the message was rather spurious because it reported only one error per abstract method, and those methods already had the `Fact` attribute applied.  After ensuring every _implementation_ had the `Fact` attribute applied, the errors went away, and it made no difference whether I retained the attribute on the abstract method declarations or not.

It would have been more useful if the error messages pointed to each non-compliant implementation, instead of the abstract declarations.

**Comment by jzabroski** [comment] 2023-10-18 17:54
I stand by my analysis that this only happens when the obj directory becomes corrupt. I am not familiar with Roslyn enough to understand why but my guess is something Roslyn code analyzers depends on is cached there.

**Comment by Sohra** [comment] 2023-10-20 22:30
I had a try reproducing int in a small, simple scenario, but was unable to - so I'm inclined to agree with @jzabroski, it's likely due to corruption of working files - _however_, I'm in the habit of clearing out my `bin`, `obj`, and `.vs` folders when I encounter these kind of weird issues and in my case, doing this did not fix the problem - I've just verified that again right now.  I still get the same three errors reported after a clean build with no pre-existing Intellisense database, bin, or object folders.  The only solution I could find was as I described in my earlier message.

As I reproduced it, I noticed these were the dependencies I started on (among others - this is a large solution at my company):
```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

After upgrading all 3 dependencies I did have two new errors manifest, both xunit1031.  After fixing them, that's when the xunit1013 errors manifest, and they persisted even after cleaning out the build artifacts.  I'll keep trying to reproduce it in a smaller sample I could provide here... but at this stage I don't think I'll be able to.
