### ISSUE TITLE
Weird (in)precision in test-cases with arguments of System.Double

### ISSUE THREAD

**Issue by estrizhok** [xunit/xunit#2960] opened 2024-06-24 16:16 UTC
```
[Theory, InlineData(2.1)]
public void Double(double value) { }
```

Is presented by Xunit v3 0.1.1-pre.485 as `Double(value: 2.1000000000000001)`
Used to be `Double(value: 2.1)` using Xunit v2

Similarly presentation of test-cases changed for the following tests:

```
[Theory, InlineData(System.Double.Epsilon)]
public void DoubleEpsilon(double value) { }

[Theory, InlineData(System.Double.MaxValue)]
public void DoubleMaxValue(double value) { }

[Theory, InlineData(System.Double.MinValue)]
public void DoubleMinValue(double value) { }
```

**Comment by bradwilson** [comment] 2024-07-06 17:18
I cannot reproduce this with current builds of v2 or v3.

v2 2.8.2-pre.20:

```
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.8.2-pre.7+e5e6fbacb2 (64-bit .NET 6.0.31)
[xUnit.net 00:00:00.06]   Discovering: empty (method display = ClassAndMethod, method display options = None)
[xUnit.net 00:00:00.10]   Discovered:  empty (found 1 test case)
[xUnit.net 00:00:00.10]   Starting:    empty (parallel test collections = on [24 threads], stop on fail = off)
[xUnit.net 00:00:00.14]   Finished:    empty
  Passed Empty.UnitTest.Double(value: 2.1000000000000001) [1 ms]
```

v3 0.2.0-pre.8:

```
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v3.0.0-pre.11+9e3af28cec (64-bit .NET 6.0.31)
[xUnit.net 00:00:00.14]   Discovering: empty
[xUnit.net 00:00:00.27]   Discovered:  empty
[xUnit.net 00:00:00.39]   Starting:    empty
[xUnit.net 00:00:00.47]   Finished:    empty
  Passed Empty.UnitTest.Double(value: 2.1000000000000001) [10 ms]
```

There was a change in formatting a while ago in v2 to include the full precision of the floating point values when presenting them. The fact that floating point numbers are imprecise is not really a "bug" that can be fixed by xUnit.net, and the reality is that the older format hid some of that imprecision. It's possible that you're using an older version of v2 which did not accurately present the values.

From my perspective, this is a feature, not a bug. If you want precise non-integer values, you should use `decimal` rather than `float` or `double`.

**Closed by bradwilson** 2024-07-06 17:18 UTC
