### ISSUE TITLE
Failed to test ASP.NET Core 2.0 views with TestHost using dotnet-xunit

### ISSUE THREAD

**Issue by sergeysolovev** [xunit/xunit#1519] opened 2017-10-16 22:49 UTC
Repro: https://github.com/sergeysolovev/xunit-mvc-repro

xunit 2.4.0-beta1-build3834
.NET Core SDK 2.0.2

```shell
dotnet build
cd FunctionalTests && dotnet xunit
```

Expected to pass as it does with visual studio runner (`dotnet test`), but instead

```
Detecting target frameworks in FunctionalTests.csproj...
Building for framework netcoreapp2.0...
  BasicWebSite -> C:\Users\sergees\source\repos\xunit-mvc-repro\BasicWebSite\bin\Debug\netcoreapp2.0\BasicWebSite.dll
  FunctionalTests -> C:\Users\sergees\source\repos\xunit-mvc-repro\FunctionalTests\bin\Debug\netcoreapp2.0\FunctionalTests.dll
Running .NET Core 2.0.0 tests for framework netcoreapp2.0...
xUnit.net Console Runner (64-bit .NET Core 4.6.00001.0)
  Discovering: FunctionalTests
  Discovered:  FunctionalTests
  Starting:    FunctionalTests
    FunctionalTests.WhenRequestingRazorView.ShouldRespondWithValidContent [FAIL]
      System.InvalidOperationException : Can not find compilation library location for package 'FunctionalTests'
      Stack Trace:
           at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
           at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
           at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
           at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
           at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
           at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
           at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
           at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
           at Microsoft.AspNetCore.Mvc.Razor.Internal.LazyMetadataReferenceFeature.get_References()
           at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
           at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
           at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
           at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
           at Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine.GenerateCode(RazorCodeDocument codeDocument)
           at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
           at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCacheEntry(String normalizedPath)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
           at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
           at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
           at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
           at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
           at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
           at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
           at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
           at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
           at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()

        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
           at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
           at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass3_0.<<SendAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.AspNetCore.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        C:\Users\sergees\source\repos\xunit-mvc-repro\FunctionalTests\WhenRequestingRazorView.cs(17,0): at FunctionalTests.WhenRequestingRazorView.<ShouldRespondWithValidContent>d__0.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    FunctionalTests
=== TEST EXECUTION SUMMARY ===
   FunctionalTests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.610s
```

**Comment by bradwilson** [comment] 2017-10-19 16:59
Probably a dup of #1499

**Comment by bradwilson** [comment] 2017-10-27 02:25
Perhaps @javiercn can help us here, based on  https://github.com/xunit/xunit/issues/1499#issuecomment-339510146:

> In general there are a few things that are usually required for MVC to run E2E test correctly, but usually these things are only related to Views, which is what is tripping me off.

I personally don't know what's required to get these things to work correctly.

**Comment by javiercn** [comment] 2017-10-27 19:52
You need to do the following:
* Copy your the deps file of the project under test to the test project bin folder.
* Disable shadow copy (you can put an xunit.runner.json file on your bin folder for this).
* Set the content root to the application under test path

References:
Add the msbuild file below to automatically copy the deps file.
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Testing/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Testing.targets
Use a method like the one below to set the content root path relative to your solution file:
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.TestHost/WebHostBuilderExtensions.cs#L52

**Comment by sergeysolovev** [comment] 2017-10-28 02:36
@javiercn @bradwilson thank you for the guidance! I believe all what you mentioned is done in [my repro](https://github.com/sergeysolovev/xunit-mvc-repro) and it really works using `dotnet test`, but not `dotnet xunit`.

**Comment by bradwilson** [comment] 2017-10-28 13:54
I'm suspicious of this code:

```csharp
        public static string GetContentRoot()
        {
            var currentDirectory = Directory.GetCurrentDirectory();
            var webSiteRelativePath = @"..\..\..\..\BasicWebSite\";


            return Path.Combine(currentDirectory, webSiteRelativePath);
        }
```

It would be better to use a known location (like `typeof(WebSite).Assembly.Location`) rather than `Directory.GetCurrentDirectory()`.

**Comment by bradwilson** [comment] 2017-10-28 14:33
FYI, @javiercn, the `2.1.0-alpha1-27377` build of `Microsoft.AspNetCore.Mvc.Testing` is broken in several ways (the fixture class cannot be a fixture in xUnit.net, it fails when using `dotnet xunit`, etc.).

**Comment by sergeysolovev** [comment] 2017-10-28 14:46
@bradwilson yes, this kind of code is not reliable for production, but for a repro I think it's OK. It points out to the right folder.

>It would be better to use a known location (like typeof(WebSite).Assembly.Location) rather than Directory.GetCurrentDirectory().

`typeof(WebSite).Assembly.Location` will lead us to the output folder of the test project, while I actually need the website's content root folder.

P.S. I wish I could use WebHostBuilderExtensions, suggested by @javiercn, but it's not available as a nuget package yet, unfortunately.

**Comment by bradwilson** [comment] 2017-10-28 14:47
@javiercn The issue appears to be your reliance upon `AppContext.BaseDirectory`, which points to `dotnet-xunit.dll`'s package folder when running `dotnet xunit`. This is not only the case in your fixture, but also in the `WebHostBuilderExtensions` file you pointed to earlier.

**Comment by bradwilson** [comment] 2017-10-28 14:49
The fact that this folder is not point to the right place may be the source of the original issue, too, if MVC is relying on `AppContext.BaseDirectory` to point somewhere specific.

**Comment by bradwilson** [comment] 2017-10-28 14:55
At this point, I'm fairly confident that this is an issue with MVC's reliance upon `AppContext.BaseDirectory` as the issue, and willing to concede that full MVC testing with `dotnet xunit` is probably not going to be possible until this is fixed.

**Comment by sergeysolovev** [comment] 2017-10-28 15:23
@bradwilson 👍 sounds right to me
@javiercn too bad you're using `dotnet test` instead of `dotnet xunit` for running your xunit tests, since the former doesn't fully utilize parallelization features of xunit and usually has longer turnaround time. It's supposed to be important for ASP.NET Core MVC testing, since you have lots of CI builds, running every day, each build taking ~13 minutes to accomplish.

**Comment by javiercn** [comment] 2017-10-30 22:02
> @javiercn The issue appears to be your reliance upon AppContext.BaseDirectory, which points to dotnet-xunit.dll's package folder when running dotnet xunit. This is not only the case in your fixture, but also in the WebHostBuilderExtensions file you pointed to earlier.

@bradwilson I've investigated this and I've confirmed that AppContext.BaseDirectory is not set to the correct path. I'm proposing a change in which we use a property to explicitly set this base path if needed and we default to try AppContext.BaseDirectory and typeof(TStartup).Assembly.CodeBase as default probing paths if no value is defined. I'm not super familiar with the inner workings of dotnet tools but this will probably suffice (we will fix WebHostBuilderExtensions too).

> FYI, @javiercn, the 2.1.0-alpha1-27377 build of Microsoft.AspNetCore.Mvc.Testing is broken in several ways (the fixture class cannot be a fixture in xUnit.net, it fails when using dotnet xunit, etc.).

Can you point out what other things are broken in terms of xUnit? I would love to get your input on things that might need fixing. We've grown this package organically from our testing infrastructure and there might be some things that might need cleanup. We've been using this class as a fixture with xUnit in our functional tests but maybe we have baked in opinions we don't necessarily want to force to our customers.

**Comment by bradwilson** [comment] 2017-10-31 10:20
> Can you point out what other things are broken in terms of xUnit?

The context class, as coded, is not suitable as a context for xUnit.net, because it defines multiple public constructors. We've already discussed the reliance on `AppContext.BaseDirectory`. I think those were the only two things I ended up fixing, to at least get to the point of realizing that the ASP.NET Core framework itself was dependent on `AppContext.BaseDirectory` and my desire to copy and fix code came to a sudden halt. ;)

**Comment by bradwilson** [comment] 2017-11-11 19:32
Closed as external.

**Comment by bradwilson** [comment] 2017-12-30 03:24
Re-opening because I've found a solution.

**Closed** 2017-12-30 06:50 UTC
Labels: [a] dotnet xunit, [t] Bug

**Comment by bradwilson** [comment] 2017-12-30 07:00
Verified with 2.4 beta 1 build 3986.

![image](https://user-images.githubusercontent.com/16944/34452055-f49a2f7a-eceb-11e7-9198-73a5dec8dd4d.png)
