### ISSUE TITLE
Collection assert  should return passed when same collections have same records

### ISSUE THREAD

**Issue by pranavdhundhia** [xunit/xunit#1904] opened 2019-02-15 15:08 UTC
Hello I do have issue with collection assert
 
Here is the code
```csharp
        [Fact]
        public void PassingTest()
        {
            List<User> expected = new List<User>();
            expected.Add(new User { Id = 1, FirstName = "Joe" });
            expected.Add(new User { Id = 2, FirstName = "Sarah" });
            Assert.Equal<List<User>>(expected, returnData());
        }

        [Fact]
        public void FailingTest()
        {
            List<User> expected = new List<User>();
            expected.Add(new User { Id = 1, FirstName = "Joe" });
            expected.Add(new User { Id = 2, FirstName = "Jane" });
            Assert.Equal<List<User>>(expected, returnData());
        }
```
Collection result is actually equals to expected result shouldn't it be returning passes test: Error is demonstrated below.

![image](https://user-images.githubusercontent.com/3126366/52865057-a0bf6f80-3161-11e9-8793-d0dd20364d71.png)

**Comment by bradwilson** [comment] 2019-03-14 16:45
What you're looking for is structural equality ("do these two objects look the same?") but equality in .NET by default (for classes) is reference equality ("are these two pointers to the exact same memory address?").

This is our default comparer: https://github.com/xunit/assert.xunit/blob/master/Sdk/AssertEqualityComparer.cs

Since you own the `User` type, one simple solution is to implement `IEquatable<User>` directly on it. As line 47 of AssertEqualityComparer shows, that's the primary thing we prefer when comparing two objects. Another easy solution would be to convert `User` to a `struct`, since the default equality implementation for structs is structural equality.

Given this code:

```csharp
using System;
using Xunit;

public class UserClass
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public struct UserStruct
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class SampleTests
{
    [Fact]
    public void ClassTest()
    {
        var user1 = new UserClass { Id = 1, Name = "Brad" };
        var user2 = new UserClass { Id = 1, Name = "Brad" };

        Assert.Equal(user1, user2);
    }

    [Fact]
    public void StructTest()
    {
        var user1 = new UserStruct { Id = 1, Name = "Brad" };
        var user2 = new UserStruct { Id = 1, Name = "Brad" };

        Assert.Equal(user1, user2);
    }
}
```

ClassTest fails, and StructTest passes. Here's the class version with equality implemented:

```csharp
public class UserClass : IEquatable<UserClass>
{
    public int Id { get; set; }
    public string Name { get; set; }

    public bool Equals(UserClass other)
    {
        return other != null &&
               Id == other.Id &&
               Name == other.Name;
    }
}
```

This makes `ClassTest` pass now.

(I know your question talked about collections, specifically for `List<User>`, but the issue is the equality check for the individual items in the collection, not the collection itself. The collection part of your question is a red herring.)

**Comment by bradwilson** [comment] 2020-08-15 21:36
Now marking this as a duplicate of #1604 because I believe that will cover your use case.

**Closed by bradwilson** 2020-08-15 21:36 UTC
Labels: status: Duplicate
