### ISSUE TITLE
Binding value from memberdata to Nullable Long fails

### ISSUE THREAD

**Issue by dogahasdemir** [xunit/xunit#2663] opened 2023-02-03 14:01 UTC
public static IEnumerable<object[]> _myMemberData => new List<object[]>
        {
            new object[]
            {
                1,2
            }
        };

        [Theory]
        [MemberData(nameof(_myMemberData))]
        public void TestSuccessToAdd(long? operand1, long? operand2)
        {
            Calculator calc = new Calculator(operand1.Value, operand2.Value);

            var result = calc.Add();

            Assert.Equal(3, result);
        }

After migrating from net5.0 to net6.0 which forces me to migrate xunit from 2.4.1 to 2.4.2 following exception occurs:
 System.ArgumentException : Object of type 'System.Int32' cannot be converted to type 'System.Nullable`1[System.Int64]'.
 
Is this the expected behaviour after last release ?

The problem is fixed If i update my memberData as :
public static IEnumerable<object[]> _myMemberData => new List<object[]>
        {
            new object[]
            {
                (long?)1,(long?)2
            }
        };

**Comment by bartelink** [comment] 2023-02-03 15:02
Duplicate of #2564

ASIDE: you can put triple ticks before and after a block of code to quote it

**Comment by dogahasdemir** [comment] 2023-02-03 15:17
Thanks for the reply, i could  not manage to find the duplicate. Closing the issue

**Closed** 2023-02-03 15:17 UTC
