### ISSUE TITLE
Can't install xUnit.net for vs 2013 project, why?

### ISSUE THREAD

**Issue by jiangwest** [xunit/xunit#1150] opened 2017-03-03 07:49 UTC
a few days I install xUnit.Net for Visual studio 2013 project, it is all right.
but today, this install process encounter a wrong:

**the error information ** is as followed:

> Install failed. Rolling back...
> Could not install package 'xunit.core 2.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

why? help

**Comment by balexandre** [comment] 2017-03-03 08:27
I had no issues...

Created a new Class Library project and added the nuget:

```
PM> Install-Package xunit 


Attempting to gather dependency information for package 'xunit.2.2.0' with respect to project 'ClassLibrary1', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 14,83 sec
Attempting to resolve dependencies for package 'xunit.2.2.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'xunit.2.2.0'
Resolved actions to install package 'xunit.2.2.0'
Retrieving package 'Microsoft.NETCore.Platforms 1.0.1' from 'nuget.org'.
Retrieving package 'NETStandard.Library 1.6.0' from 'nuget.org'.
Retrieving package 'xunit.abstractions 2.0.1' from 'nuget.org'.
Retrieving package 'xunit.assert 2.2.0' from 'nuget.org'.
Retrieving package 'xunit.extensibility.core 2.2.0' from 'nuget.org'.
Retrieving package 'xunit.extensibility.execution 2.2.0' from 'nuget.org'.
Retrieving package 'xunit.core 2.2.0' from 'nuget.org'.
Retrieving package 'xunit 2.2.0' from 'nuget.org'.
Retrieving package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0' from 'nuget.org'.
Retrieving package 'System.Diagnostics.Tools 4.0.1' from 'nuget.org'.
Retrieving package 'System.Reflection.Extensions 4.0.1' from 'nuget.org'.
Retrieving package 'System.Reflection.Primitives 4.0.1' from 'nuget.org'.
Retrieving package 'System.Resources.ResourceManager 4.0.1' from 'nuget.org'.
Retrieving package 'System.Runtime.Numerics 4.0.1' from 'nuget.org'.
Retrieving package 'System.Collections 4.0.11' from 'nuget.org'.
Retrieving package 'System.Diagnostics.Debug 4.0.11' from 'nuget.org'.
Retrieving package 'System.Globalization 4.0.11' from 'nuget.org'.
Retrieving package 'System.Net.Primitives 4.0.11' from 'nuget.org'.
Retrieving package 'System.Text.Encoding 4.0.11' from 'nuget.org'.
Retrieving package 'System.Text.Encoding.Extensions 4.0.11' from 'nuget.org'.
Retrieving package 'System.Threading 4.0.11' from 'nuget.org'.
Retrieving package 'System.Threading.Tasks 4.0.11' from 'nuget.org'.
Retrieving package 'System.Xml.ReaderWriter 4.0.11' from 'nuget.org'.
Retrieving package 'System.Xml.XDocument 4.0.11' from 'nuget.org'.
Retrieving package 'System.Collections.Concurrent 4.0.12' from 'nuget.org'.
Retrieving package 'System.ObjectModel 4.0.12' from 'nuget.org'.
Retrieving package 'System.Diagnostics.Tracing 4.1.0' from 'nuget.org'.
Retrieving package 'System.IO 4.1.0' from 'nuget.org'.
Retrieving package 'System.IO.Compression 4.1.0' from 'nuget.org'.
Retrieving package 'System.Linq 4.1.0' from 'nuget.org'.
Retrieving package 'System.Linq.Expressions 4.1.0' from 'nuget.org'.
Retrieving package 'System.Net.Http 4.1.0' from 'nuget.org'.
Retrieving package 'System.Reflection 4.1.0' from 'nuget.org'.
Retrieving package 'System.Runtime 4.1.0' from 'nuget.org'.
Retrieving package 'System.Runtime.Extensions 4.1.0' from 'nuget.org'.
Retrieving package 'System.Runtime.InteropServices 4.1.0' from 'nuget.org'.
Retrieving package 'System.Text.RegularExpressions 4.1.0' from 'nuget.org'.
Adding package 'Microsoft.NETCore.Platforms.1.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'Microsoft.NETCore.Platforms.1.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'Microsoft.NETCore.Platforms.1.0.1' to 'packages.config'
Successfully installed 'Microsoft.NETCore.Platforms 1.0.1' to ClassLibrary1
Adding package 'System.Collections.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Collections.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Collections.4.0.11' to 'packages.config'
Successfully installed 'System.Collections 4.0.11' to ClassLibrary1
Adding package 'System.Collections.Concurrent.4.0.12' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Collections.Concurrent.4.0.12' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Collections.Concurrent.4.0.12' to 'packages.config'
Successfully installed 'System.Collections.Concurrent 4.0.12' to ClassLibrary1
Adding package 'System.Diagnostics.Debug.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Diagnostics.Debug.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Diagnostics.Debug.4.0.11' to 'packages.config'
Successfully installed 'System.Diagnostics.Debug 4.0.11' to ClassLibrary1
Adding package 'System.Diagnostics.Tools.4.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Diagnostics.Tools.4.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Diagnostics.Tools.4.0.1' to 'packages.config'
Successfully installed 'System.Diagnostics.Tools 4.0.1' to ClassLibrary1
Adding package 'System.Diagnostics.Tracing.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Diagnostics.Tracing.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Diagnostics.Tracing.4.1.0' to 'packages.config'
Successfully installed 'System.Diagnostics.Tracing 4.1.0' to ClassLibrary1
Adding package 'System.Globalization.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Globalization.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Globalization.4.0.11' to 'packages.config'
Successfully installed 'System.Globalization 4.0.11' to ClassLibrary1
Adding package 'System.IO.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.IO.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.IO.4.1.0' to 'packages.config'
Successfully installed 'System.IO 4.1.0' to ClassLibrary1
Adding package 'System.IO.Compression.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.IO.Compression.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.IO.Compression.4.1.0' to 'packages.config'
Successfully installed 'System.IO.Compression 4.1.0' to ClassLibrary1
Adding package 'System.Linq.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Linq.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Linq.4.1.0' to 'packages.config'
Successfully installed 'System.Linq 4.1.0' to ClassLibrary1
Adding package 'System.Linq.Expressions.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Linq.Expressions.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Linq.Expressions.4.1.0' to 'packages.config'
Successfully installed 'System.Linq.Expressions 4.1.0' to ClassLibrary1
Adding package 'System.Net.Http.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Net.Http.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Net.Http.4.1.0' to 'packages.config'
Successfully installed 'System.Net.Http 4.1.0' to ClassLibrary1
Adding package 'System.Net.Primitives.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Net.Primitives.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Net.Primitives.4.0.11' to 'packages.config'
Successfully installed 'System.Net.Primitives 4.0.11' to ClassLibrary1
Adding package 'System.ObjectModel.4.0.12' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.ObjectModel.4.0.12' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.ObjectModel.4.0.12' to 'packages.config'
Successfully installed 'System.ObjectModel 4.0.12' to ClassLibrary1
Adding package 'System.Reflection.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Reflection.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Reflection.4.1.0' to 'packages.config'
Successfully installed 'System.Reflection 4.1.0' to ClassLibrary1
Adding package 'System.Reflection.Extensions.4.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Reflection.Extensions.4.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Reflection.Extensions.4.0.1' to 'packages.config'
Successfully installed 'System.Reflection.Extensions 4.0.1' to ClassLibrary1
Adding package 'System.Reflection.Primitives.4.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Reflection.Primitives.4.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Reflection.Primitives.4.0.1' to 'packages.config'
Successfully installed 'System.Reflection.Primitives 4.0.1' to ClassLibrary1
Adding package 'System.Resources.ResourceManager.4.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Resources.ResourceManager.4.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Resources.ResourceManager.4.0.1' to 'packages.config'
Successfully installed 'System.Resources.ResourceManager 4.0.1' to ClassLibrary1
Adding package 'System.Runtime.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Runtime.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Runtime.4.1.0' to 'packages.config'
Successfully installed 'System.Runtime 4.1.0' to ClassLibrary1
Adding package 'System.Runtime.Extensions.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Runtime.Extensions.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Runtime.Extensions.4.1.0' to 'packages.config'
Successfully installed 'System.Runtime.Extensions 4.1.0' to ClassLibrary1
Adding package 'System.Runtime.InteropServices.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Runtime.InteropServices.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Runtime.InteropServices.4.1.0' to 'packages.config'
Successfully installed 'System.Runtime.InteropServices 4.1.0' to ClassLibrary1
Adding package 'System.Runtime.InteropServices.RuntimeInformation.4.0.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Runtime.InteropServices.RuntimeInformation.4.0.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Runtime.InteropServices.RuntimeInformation.4.0.0' to 'packages.config'
Successfully installed 'System.Runtime.InteropServices.RuntimeInformation 4.0.0' to ClassLibrary1
Adding package 'System.Runtime.Numerics.4.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Runtime.Numerics.4.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Runtime.Numerics.4.0.1' to 'packages.config'
Successfully installed 'System.Runtime.Numerics 4.0.1' to ClassLibrary1
Adding package 'System.Text.Encoding.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Text.Encoding.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Text.Encoding.4.0.11' to 'packages.config'
Successfully installed 'System.Text.Encoding 4.0.11' to ClassLibrary1
Adding package 'System.Text.Encoding.Extensions.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Text.Encoding.Extensions.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Text.Encoding.Extensions.4.0.11' to 'packages.config'
Successfully installed 'System.Text.Encoding.Extensions 4.0.11' to ClassLibrary1
Adding package 'System.Text.RegularExpressions.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Text.RegularExpressions.4.1.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Text.RegularExpressions.4.1.0' to 'packages.config'
Successfully installed 'System.Text.RegularExpressions 4.1.0' to ClassLibrary1
Adding package 'System.Threading.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Threading.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Threading.4.0.11' to 'packages.config'
Successfully installed 'System.Threading 4.0.11' to ClassLibrary1
Adding package 'System.Threading.Tasks.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Threading.Tasks.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Threading.Tasks.4.0.11' to 'packages.config'
Successfully installed 'System.Threading.Tasks 4.0.11' to ClassLibrary1
Adding package 'System.Xml.ReaderWriter.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Xml.ReaderWriter.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Xml.ReaderWriter.4.0.11' to 'packages.config'
Successfully installed 'System.Xml.ReaderWriter 4.0.11' to ClassLibrary1
Adding package 'System.Xml.XDocument.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Xml.XDocument.4.0.11' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'System.Xml.XDocument.4.0.11' to 'packages.config'
Successfully installed 'System.Xml.XDocument 4.0.11' to ClassLibrary1
Adding package 'NETStandard.Library.1.6.0', which only has dependencies, to project 'ClassLibrary1'.
Adding package 'NETStandard.Library.1.6.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'NETStandard.Library.1.6.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'NETStandard.Library.1.6.0' to 'packages.config'
Successfully installed 'NETStandard.Library 1.6.0' to ClassLibrary1
Adding package 'xunit.abstractions.2.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.abstractions.2.0.1' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.abstractions.2.0.1' to 'packages.config'
Successfully installed 'xunit.abstractions 2.0.1' to ClassLibrary1
Adding package 'xunit.assert.2.2.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.assert.2.2.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.assert.2.2.0' to 'packages.config'
Successfully installed 'xunit.assert 2.2.0' to ClassLibrary1
Adding package 'xunit.extensibility.core.2.2.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.extensibility.core.2.2.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.extensibility.core.2.2.0' to 'packages.config'
Successfully installed 'xunit.extensibility.core 2.2.0' to ClassLibrary1
Adding package 'xunit.extensibility.execution.2.2.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.extensibility.execution.2.2.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.extensibility.execution.2.2.0' to 'packages.config'
Successfully installed 'xunit.extensibility.execution 2.2.0' to ClassLibrary1
Adding package 'xunit.core.2.2.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.core.2.2.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.core.2.2.0' to 'packages.config'
Successfully installed 'xunit.core 2.2.0' to ClassLibrary1
Adding package 'xunit.2.2.0', which only has dependencies, to project 'ClassLibrary1'.
Adding package 'xunit.2.2.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.2.2.0' to folder 'c:\users\gdkbma\documents\visual studio 2015\Projects\ClassLibrary1\packages'
Added package 'xunit.2.2.0' to 'packages.config'
Successfully installed 'xunit 2.2.0' to ClassLibrary1
Executing nuget actions took 3,86 sec
Time Elapsed: 00:00:19.8043575
```

try removing and add again with:

    Uninstall-Package xunit -RemoveDependencies

and then

    Install-Package xunit

**Comment by bradwilson** [comment] 2017-03-03 08:27
Duplicate of #1134 and #1127.

Specifically, see this comment: https://github.com/xunit/xunit/issues/1134#issuecomment-282073235

**Closed by bradwilson** 2017-03-03 08:27 UTC

**Comment by bradwilson** [comment] 2017-03-03 08:28
Also, please make sure you're using .NET 4.5.2, not .NET 4.5.

**Comment by jiangwest** [comment] 2017-03-05 02:50
- I search NuGet with keyword `xunit.assert`, which can find xUnit version 2.1.0
I try it

**Comment by bradwilson** [comment] 2017-03-05 04:00
`xunit.assert` is available in version 2.2.0: https://www.nuget.org/packages/xunit.assert/2.2.0

**Comment by jiangwest** [comment] 2017-03-10 05:11
finally, I still use xUnit 2.1.0

1. Install `xUnit.net`: `Install-Package xunit -Version 2.1.0`
2. Install `xUnit.net [Runner: Visual Studio] `: `Install-Package xunit.runner.visualstudio -Version 2.1.0`

it is ok

**Comment by rduan** [comment] 2017-03-31 03:31
got the same issue, finally use 2.1

**Comment by philwindsor** [comment] 2018-02-19 16:34
i know the case is closed but i have just received the same error using visual studio 2013 enterprise.

forcing version 2.1.0 installed fine however.

**Comment by bradwilson** [comment] 2018-02-19 17:04
@philwindsor NuGet has chosen not to fix this bug, so there's nothing we can do about it. The [workaround here](https://github.com/xunit/xunit/issues/1134#issuecomment-282073235) is your only option.

**Comment by philwindsor** [comment] 2018-02-19 17:29
thanks for the swift response brad!
