### ISSUE TITLE
Different behavior for Assert.Equal with type Dictionary<string, List<string>> in 2.5.0

### ISSUE THREAD

**Issue by JD-Robertson** [xunit/xunit#2755] opened 2023-07-14 20:13 UTC
Upgrading a project from 2.4.5 to 2.5.0 and a test started failing. I hacked up a simplified test case to reproduce:

```cs       
        [Fact]
        public async void Reproducing_test()
        {
            var expected1 = new Dictionary<string, List<string>>
            {
                ["toAddresses"] = new List<string> { "test1@example.com" },
                ["ccAddresses"] = new List<string> { "test2@example.com" },
            };
            var actual1 = new Dictionary<string, List<string>>();
            actual1["toAddresses"] = expected1["toAddresses"];
            actual1["ccAddresses"] = expected1["ccAddresses"];

            Assert.Equal(expected1, actual1);

            var expected2 = new Dictionary<string, List<string>>
            {
                ["toAddresses"] = new List<string> { "test1@example.com" },
                ["ccAddresses"] = new List<string> { "test2@example.com" },
            };
            var actual2 = new Dictionary<string, List<string>>
            {
                ["toAddresses"] = new List<string> { "test1@example.com" },
                ["ccAddresses"] = new List<string> { "test2@example.com" },
            };

            Assert.Equal(expected2, actual2);
        }
```

The second assertion fails with:

>  Message: 
> Assert.Equal() Failure: Dictionaries differ
> Expected: [["toAddresses"] = ["test1@example.com"], ["ccAddresses"] = ["test2@example.com"]]
> Actual:   [["toAddresses"] = ["test1@example.com"], ["ccAddresses"] = ["test2@example.com"]]

Previously both would pass. It seems that Assert.Equals() no longer does deep equality for Dictionary values, at least for the List<string> type. It appears to be using reference equality instead. I didn't see any documentation about this behavior change in the release notes so I'm assuming that it is a regression.

**Comment by bradwilson** [comment] 2023-07-15 20:34
Thanks for the bug report! This will be fixed in 2.5.1 (and available in the first prerelease build--which has not shipped to NuGet yet--if you want to test it early).

**Closed by bradwilson** 2023-07-15 20:34 UTC
Labels: type: Bug, area: Assertion library, target: 3.0, target: 2.x

**Comment by AdamWillden** [comment] 2023-07-18 18:33
@bradwilson do you have a timeline on 2.5.1 (or even a prerelease to test) I am facing the same bug. I have reverted for the moment.

Thank you very much for fixing though

**Comment by bradwilson** [comment] 2023-07-18 18:34
There will be a prerelease this week

**Comment by AdamWillden** [comment] 2023-07-18 18:35
Wow I blinked and there was a reply. Thanks

**Comment by bradwilson** [comment] 2023-07-18 18:55
You caught me on my phone and the GitHub app notification popped up 😂

**Comment by yfital** [comment] 2023-07-24 14:02
I can confirm this was fixed with 2.5.1-pre.12, thank you for the fast prompt!
Wasted an hour trying to understand what i screwed with my code 🤣

**Comment by fbraun4358** [comment] 2023-08-08 15:35
@bradwilson Thanks so much for all the hard work on xunit. I just ran into this issue myself when updating to `2.5.0` so eagerly watching for when 2.5.1 is released. Updated like 300 tests to use `Assert.Equivalent` but I will probably stay on `2.4.x` for now. Should have looked at the issues before all that work 🤦‍♂️

**Comment by Matthewsre** [comment] 2023-08-20 00:59
Just tried updating to 2.5.0 and hit this as well.

In my case the Assert.Equal is now failing on Dictionary<string,object>, where some cases the object is a nested Dictionary<string,object> recursively.

Example:

```
var dictionary = new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase) {
    { "int", 1 },
    { "string", "two" },
    { "bool", true },
    { "nested1Root", new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase) {
        { "int", 11 },
        { "string", "two-two" },
        { "bool", false },
        { "nested1Middle", new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase) {
            { "int", 111 },
            { "string", "two-two-two" },
            { "bool", true },
            { "nested1End", new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase) {
                { "int", 1111 },
                { "string", "two-two-two-two" },
                { "bool", false },
            }},
        }},
    }},
    { "nested2Root", new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase) {
        { "int", 99 },
        { "string", "nine-nine" },
        { "bool", true },
    }},
    { "anotherRoot", "value" }
};
```

Rolling back to 2.4.x and hope the fix coming up in 2.5.1 addresses my scenario as well.

**Comment by bradwilson** [comment] 2023-08-20 20:33
@Matthewsre You can try it right now with a 2.5.1 prerelease build on NuGet. (I am away from my coding computer for a while and cannot verify it myself). https://www.nuget.org/packages/xunit/2.5.1-pre.20

**Comment by chotea** [comment] 2023-09-22 11:50
@bradwilson
It looks like we still have regressions in 2.5.1. The following test is failing now but passing with:
    <PackageVersion Include="xunit" Version="2.4.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.4.5" />

`        [Fact]
        public void TestEqualDict()
        {
            var dict1 = new Dictionary<string, object>();
            dict1["key"] = new Dictionary<string, object>()
            {
                {
                    "key", new List<Dictionary<string, object>>()
                        {
                            new Dictionary<string, object>()
                            {
                                {
                                    "key", new List<object> { "value" }
                                }
                            }
                        }
                }
            };
            var dict2 = new Dictionary<string, object>();
            dict2["key"] = new Dictionary<string, object>()
            {
                {
                    "key", new List<Dictionary<string, object>>()
                        {
                            new Dictionary<string, object>()
                            {
                                {
                                    "key", new List<object> { "value" }
                                }
                            }
                        }
                }
            };
            Assert.Equal(dict1, dict2);
        }`

**Comment by bradwilson** [comment] 2023-09-22 17:24
@chotea No need for a new issue. I have a fix incoming.

**Comment by bradwilson** [comment] 2023-09-22 17:39
@chotea Fix is now available on feedz.io.

v2: `2.5.2-pre.2`
v3: `0.1.1-pre.280`

I'll push the v2 prerelease build to NuGet tomorrow.

**Comment by chotea** [comment] 2023-09-25 09:12
@bradwilson 
Tested with 2.5.2-pre.2 and it works as expected. Thanks!
