### ISSUE TITLE
Microsoft.Extensions.Configuration stopped working with Xunit 2.3.1

### ISSUE THREAD

**Issue by VictorGavrish** [xunit/xunit#1564] opened 2017-11-09 10:20 UTC
Repro here:

https://github.com/VictorGavrish/XunitBugRepro

## Steps to reproduce:

1. `git clone https://github.com/VictorGavrish/XunitBugRepro.git`
2. `cd XunitBugRepro/UnitTests`
3. `dotnet restore`
4. `dotnet xunit`

## Expected result:

Test runs successfully

## Actual result:

```
    UnitTests.Class1.PassingTest [FAIL]
      System.IO.FileNotFoundException : The configuration file 'testsettings.json' was not found and is not optional. The physical path is '/root/.nuget/packages/dotnet-xunit/2.3.1/tools/netcoreapp2.0/testsettings.json'.                                                                                            
      Stack Trace:
           at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
           at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()                                                                           
           at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)                                                                 
           at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()                                                                               
        /XunitBugRepro/UnitTests/Class1.cs(12,0): at UnitTests.Class1.PassingTest()                                                                         
```

## Notes

This used to work without a problem with version `2.3.0-beta4-build3742`, but fails with `2.3.1`. There is another project in the repo which runs successfully, and the only change is the older version of xunit.

**Comment by bradwilson** [comment] 2017-11-09 23:28
This appears to be the same problem as https://github.com/xunit/xunit/issues/1519#issuecomment-340196916 which cannot be resolved by us.

**Comment by VictorGavrish** [comment] 2017-11-10 00:34
It did use to work with version `2.3.0-beta4-build3742`, so obviously some change in Xunit has made the issue appear.

**Comment by bradwilson** [comment] 2017-11-10 00:41
Yes, we fixed several bugs with assembly loading, and what used to be working accidentally no longer works now that we're doing the right thing (and they're not).

**Comment by VictorGavrish** [comment] 2017-11-10 00:47
Why is relying on `AppContext.BaseDirectory` to be the place where `Copy if newer` content files are copied not doing the right thing? Seems to me that that is one of the purposes of this property. How else are you supposed to refer to it?

**Comment by bradwilson** [comment] 2017-11-10 00:51
The problem is the library in question used to site in your bin folder, but now we correctly pull it from the NuGet package cache (where your config file isn't). My guess is there is fallback logic to look in `AppContext.BaseDirectory`, which is why the error says it's looking where `xunit.console.dll` lives (since that's the launched executable, that is the base directory of the application).

**Comment by bradwilson** [comment] 2017-11-10 00:53
Alternatively, perhaps you can pass a full path to the configuration file, using `Path.Combine(Path.GetDirectoryName(typeof(Class1).GetTypeInfo().Assembly.Location), "testsettings.json")`.

**Comment by VictorGavrish** [comment] 2017-11-10 01:03
> but now we correctly pull it from the NuGet package cache

Why is that correct if it breaks stuff? Seems to me that a testing framework should emulate the way the application as it will be launched in production as closely as possible, otherwise it imposes workarounds like you suggested on the subject under test and is also a surprising gotcha.

**Comment by bradwilson** [comment] 2017-11-10 01:41
Copying the DLLs from NuGet packages to the bin folder had never been correct. The fact that your test passed while we were doing incorrect things is irrelevant. It was an accident.

**Comment by bradwilson** [comment] 2017-11-10 01:41
When your application is compiled, the DLLs from NuGet packages aren't copied, either.

**Comment by bradwilson** [comment] 2017-11-10 01:43
As stated previously, the bug is in MVC. We have no intention of special casing the broken behavior in MVC.

**Comment by bradwilson** [comment] 2017-11-11 19:39
Closing as external.

**Closed by bradwilson** 2017-11-11 19:39 UTC
Labels: [a] dotnet xunit, [s] External, [t] Bug
