### ISSUE TITLE
Overridden test with InlineData also executes InlineData on base implementation

### ISSUE THREAD

**Issue by SrChronus** [xunit/xunit#2585] opened 2022-09-20 14:50 UTC
### Description

When overriding a test decorated with the InlineDataAttribute all the datarows on the base will also be executed. This makes overriding a test quite useless.
We use test overriding to test feature flag implementations.

### Steps to reproduce
```
public class Test
{
    [Theory]
    [InlineData("cherry")]
    [InlineData("banana")]
    [InlineData("Apple")]
    public virtual void TestMethod(string a)
    {
        Assert.True(true);
    }
}

public class MyTest : Test
{
    [Theory]
    [InlineData("orange")]
    [InlineData("pineapple")]
    public override void TestMethod(string a)
    {
        Assert.True(true);
    }
}
```
### Expected behavior
MyTest (2 tests) [0:00.004] Success
TestMethod (2 tests) [0:00.004] Success
TestMethod (orange) [0:00.004] Success
TestMethod (pineapple) [0:00.000] Success
Test (3 tests) [0:00.005] Success
TestMethod (3 tests) [0:00.005] Success
TestMethod (Apple) [0:00.000] Success
TestMethod (banana) [0:00.000] Success
TestMethod (cherry) [0:00.005] Success

### Actual behavior
MyTest (5 tests) [0:00.006] Success
TestMethod (5 tests) [0:00.006] Success
TestMethod (Apple) [0:00.000] Success
TestMethod (banana) [0:00.000] Success
TestMethod (cherry) [0:00.000] Success
TestMethod (orange) [0:00.006] Success
TestMethod (pineapple) [0:00.000] Success
Test (3 tests) [0:00.007] Success
TestMethod (3 tests) [0:00.007] Success
TestMethod (Apple) [0:00.000] Success
TestMethod (banana) [0:00.000] Success
TestMethod (cherry) [0:00.007] Success

**Comment by sysa20** [comment] 2022-10-10 10:37
hello is this issue still open, can I grab it?

**Comment by SrChronus** [comment] 2022-10-10 11:44
> hello is this issue still open, can I grab it?

I believe it is still open yes.

**Comment by sysa20** [comment] 2022-10-23 15:37
Hi, the solution was found. The solution is made so that the current XUnit API contract does not change. I made a fix in the code that correctly accepts an attribute parameter that is inherited. 

```
[DataDiscoverer("Xunit.Sdk.InlineDataDiscoverer", "xunit.core")]
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
public sealed class NonInheritableInlineDataAttribute : DataAttribute
{
      readonly object[] data;

      /// <summary>
      /// Initializes a new instance of the <see cref="InlineDataAttribute"/> class.
      /// </summary>
      /// <param name="data">The data values to pass to the theory.</param>
      public NonInheritableInlineDataAttribute(params object[] data)
      {
          this.data = data;
      }

      /// <inheritdoc/>
      public override IEnumerable<object[]> GetData(MethodInfo testMethod)
      {
          // This is called by the WPA81 version as it does not have access to attribute ctor params
          return new[] { data };
      }
}
```

![image](https://user-images.githubusercontent.com/61652662/197392090-e91a2707-6504-47d2-9bdf-196812ab998a.png)

**Comment by bradwilson** [comment] 2022-11-05 19:31
@SrChronus wrote:

> When overriding a test decorated with the InlineDataAttribute all the datarows on the base will also be executed. This makes overriding a test quite useless.

This is by design.

In addition, it's not even clear what your example is trying to achieve: it uses neither the original test nor the original test data, so why is inheritance even something you're trying to do? Perhaps a real-world example would help to clarify.

**Comment by sysa20** [comment] 2022-11-05 19:51
@bradwilson 
Testing all theory data rows when a test is inherited, is perfectly correct (by design), also in my opinion, but in hypotetic case someone uses some sort of BaseTest class, and there will be some specific case where you need change some particular case. Using my fix You are able to do it.
It can be used in projects where you are writing, Data Repository layer unit tests, where 95% of testing code can be put in some sort of BaseRepo tests. But maybe there is some particular entity which need one theory with a bit different data.

**Comment by SrChronus** [comment] 2022-11-16 13:47
> @SrChronus wrote:
> 
> > When overriding a test decorated with the InlineDataAttribute all the datarows on the base will also be executed. This makes overriding a test quite useless.
> 
> This is by design.
> 
> In addition, it's not even clear what your example is trying to achieve: it uses neither the original test nor the original test data, so why is inheritance even something you're trying to do? Perhaps a real-world example would help to clarify.

@bradwilson the point of the shown code is that the overridden test does explicitly NOT use the original test NOR the original data.
The whole point of this is feature flag testing. Say that I have a method I have under test such as

```
bool IsFruit(string input)
{
    Switch( input)
    case "apple":
         return true;
    case "tomato":
        if(flag)  return true;
        return false;
    default:
        return false;
}
```
now I want to test this method both with the flag on and off, I need to override the original test
```
 public class TestClass
    {
        readonly Mock<IFeatureFlagChecker> _featureFlagChecker = new Mock<IFeatureFlagChecker>();

        public TestClass()
        {
            _featureFlagChecker.Setup(f => f.IsEnabled("flag")).Returns(false);
        }

        [Theory]
        [InlineData("apple", true)]
        [InlineData("banana", false)]
        [InlineData("tomato", false)]
        public virtual void IsFruit_ShouldReturnExpected(string input, bool expectedResult)
        {

            Assert.Equal(expectedResult, GetSubject().IsFruit(input));
        }

        private FruitTester GetSubject()
        {
            return new FruitTester(_featureFlagChecker.Object);
        }

        public class TestClassFlagOn : TestClass
        {
            public TestClassFlagOn()
            {
                _featureFlagChecker.Setup(f => f.IsEnabled("flag")).Returns(true);
            }

            [Theory]
            [InlineData("apple", true)]
            [InlineData("banana", false)]
            [InlineData("tomato", true)]
            public override void IsFruit_ShouldReturnExpected(string input, bool expectedResult)
            {
                Assert.Equal(expectedResult, GetSubject().IsFruit(input));
            }
        }
    }
```

IF I do the above I certainly wouldn't want both the tomato rows to be executed on the overridden test as this would throw the result, but in addition running the test multiple times with the same input also makes no sense. If I want to override, I want to override all the behavior of the test. This working perfectly fine with MS Test btw.

**Comment by bradwilson** [comment] 2023-01-22 22:55
In your example, there doesn't appear to be any reason to "override" anything. Just write a new test with a new test method name, as it's a completely different test (since the data is different).

I'm still not convinced there is anything here that needs to be fixed, so I'm closing this issue.

**Closed by bradwilson** 2023-01-22 22:55 UTC

**Comment by SrChronus** [comment] 2023-01-23 14:26
If you look closer at my example you will see that creating a new test with a new name would cause the base class test to be run twice with the same expectation which would result in a failing test. That is the whole exact reason for this bug report. I want to Override the base class test with the desired feature flag status.

It is the same test with changed expectations between feature on/ feature off.

**Comment by bradwilson** [comment] 2023-01-25 03:59
I understand your argument, but I disagree that this is desired behavior.

In my opinion, the problem is a philosophical one, and it's surfaced through the misuse of inheritance. What you really have is two groups of tests: one with the flag enabled, and one with the flag disabled. The fact that you put the "flag is disabled" tests into the base class is where the error lives.

Although it's obviously overkill for this simple example, in my opinion the correct philosophical expression of what you're trying to do is this:

```csharp
public class TestClass
{
    readonly Mock<IFeatureFlagChecker> _featureFlagChecker = new Mock<IFeatureFlagChecker>();

    protected FruitTester GetSubject()
    {
        return new FruitTester(_featureFlagChecker.Object);
    }

    public class TestClassFlagOff : TestClass
    {
        public TestClassFlagOff()
        {
            _featureFlagChecker.Setup(f => f.IsEnabled("flag")).Returns(false);
        }

        [Theory]
        [InlineData("apple", true)]
        [InlineData("banana", false)]
        [InlineData("tomato", false)]
        public void IsFruit_ShouldReturnExpected(string input, bool expectedResult)
        {
            Assert.Equal(expectedResult, GetSubject().IsFruit(input));
        }
    }

    public class TestClassFlagOn : TestClass
    {
        public TestClassFlagOn()
        {
            _featureFlagChecker.Setup(f => f.IsEnabled("flag")).Returns(true);
        }

        [Theory]
        [InlineData("apple", true)]
        [InlineData("banana", false)]
        [InlineData("tomato", true)]
        public void IsFruit_ShouldReturnExpected(string input, bool expectedResult)
        {
            Assert.Equal(expectedResult, GetSubject().IsFruit(input));
        }
    }
}
```

This pattern is one I call context-based testing: your test class describes the context of the environment in which the test runs, and the constructor and/or Dispose are responsible for creating and/or destroying that context. Our [Stack sample](https://github.com/xunit/samples.xunit/blob/main/Stack/StackTests.cs) shows this style, albeit without the inheritance.
