### ISSUE TITLE
Console Runner 2.1.0 is really slow compared to 1.9.2

### ISSUE THREAD

**Issue by TrevorPilley** [xunit/xunit#959] opened 2016-08-31 16:28 UTC
I've just updated my project from xunit 1.9.2 to 2.1.0 the build output (run from PSake) shows:

> Executing RunTests
> Running MicroLite.Tests.NET45
> xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
>   Discovering: MicroLite.Tests
>   Discovered:  MicroLite.Tests
>   Starting:    MicroLite.Tests
>   Finished:    MicroLite.Tests
> === TEST EXECUTION SUMMARY ===
>    MicroLite.Tests  Total: 1454, Errors: 0, Failed: 0, Skipped: 0, Time: 13.319s
> Running MicroLite.Tests.NET46
> xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
>   Discovering: MicroLite.Tests
>   Discovered:  MicroLite.Tests
>   Starting:    MicroLite.Tests
>   Finished:    MicroLite.Tests
> === TEST EXECUTION SUMMARY ===
>    MicroLite.Tests  Total: 1454, Errors: 0, Failed: 0, Skipped: 0, Time: 13.069s
> ---
> ## Build Time Report
> 
> Name      Duration
> ---
> 
> Clean     00:00:00.0745726
> Build     00:00:17.9933533
> RunTests  00:07:29.5545361
> BuildHelp 00:01:11.7860821
> Total:    00:08:59.4338494

Since the tests run in 26.4s, what is taking up the rest of the 7 mins 30?

**Comment by bradwilson** [comment] 2016-08-31 23:37
Can you provide a repro please?

**Comment by Zvirja** [comment] 2016-09-02 15:40
It might be related to the issue fixed in 8d553ace06aba4cfb78e27cdc96669920c48d840. I noted the similar behavior even with 2.2 beta 2, however is not reproducible if build runner from source code.

It was has not been published as a beta, so no way to check whether it has been already fixed without messing with source code. As soon as it's published - you can check.

**Comment by bradwilson** [comment] 2016-09-02 18:42
You don't need to compile from source. You can pull the packages from our [CI builds on MyGet](http://myget.org/gallery/xunit).

**Comment by TrevorPilley** [comment] 2016-09-06 08:31
I'll try the myget build and see if that's quicker, if not I'll sort out a reproduction

**Comment by nparrish** [comment] 2016-09-13 22:49
I am also seeing this issue, and can confirm it is fixed in the latest MyGet builds.  Using the latest 2.2.0-beta3 builds, my tests run in 16.8s vs 79.1s with the stable 2.1 build.

**Comment by Zvirja** [comment] 2017-03-23 20:46
@TrevorPilley Is your issue fixed with 2.2? If so, feel free to close this issue :)

**Comment by johncrim** [comment] 2017-05-26 22:58
This looks resolved to me, in that 2.2 is substantially faster than 2.1. Here's one example:

```
λ measure-command {.\packages\xunit.runner.console.2.2.0\tools\xunit.console.exe .\test\Web.Tests\bin\Debug\Tv.Web.Demand.Web.Tests.dll}


Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 48
Milliseconds      : 756
Ticks             : 1087565249
TotalDays         : 0.00125875607523148
TotalHours        : 0.0302101458055556
TotalMinutes      : 1.81260874833333
TotalSeconds      : 108.7565249
TotalMilliseconds : 108756.5249



C:\src\tv\web\demand [develop ≡]
λ measure-command {.\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe .\test\Web.Tests\bin\Debug\Tv.Web.Demand.Web.Tests.dll}


Days              : 0
Hours             : 0
Minutes           : 4
Seconds           : 45
Milliseconds      : 473
Ticks             : 2854735383
TotalDays         : 0.00330409187847222
TotalHours        : 0.0792982050833333
TotalMinutes      : 4.757892305
TotalSeconds      : 285.4735383
TotalMilliseconds : 285473.5383
```

**Comment by onovotny** [comment] 2017-05-26 23:06
Can you please try the 2.3 betas? There has been a lot of performance optimizations between 2.1 and the current betas.

**Comment by johncrim** [comment] 2017-05-26 23:41
You bet. I used the latest beta from nuget.org:
https://www.nuget.org/packages/xunit.runner.console/2.3.0-beta1-build3642
As well as the latest beta from myget:
https://myget.org/feed/xunit/package/nuget/xunit.runner.console/2.3.0-beta3-build3699

I also decided to test against one of my open-source projects (https://github.com/logjam2/logjam) to make it more reproducible. Using .NET 4.6.2.

First run:
```
CommandLine                                                                                                                                 RunningTime
-----------                                                                                                                                 -----------
.\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe .\test\LogJam.UnitTests\bin\Debug\LogJam.UnitTests.dll                        00:00:13.9649590
.\packages\xunit.runner.console.2.2.0\tools\xunit.console.exe .\test\LogJam.UnitTests\bin\Debug\LogJam.UnitTests.dll                        00:00:08.1009766
.\packages\xunit.runner.console.2.3.0-beta2-build3683\tools\net452\xunit.console.exe .\test\LogJam.UnitTests\bin\Debug\LogJam.UnitTests.dll 00:00:07.3705431
.\packages\xunit.runner.console.2.3.0-beta3-build3699\tools\net452\xunit.console.exe .\test\LogJam.UnitTests\bin\Debug\LogJam.UnitTests.dll 00:00:08.1053121
```

Second run:
```
CommandLine                                                                                                                                 RunningTime
-----------                                                                                                                                 -----------
.\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe .\test\LogJam.UnitTests\bin\Debug\LogJam.UnitTests.dll                        00:00:11.1579917
.\packages\xunit.runner.console.2.2.0\tools\xunit.console.exe .\test\LogJam.UnitTests\bin\Debug\LogJam.UnitTests.dll                        00:00:07.3178809
.\packages\xunit.runner.console.2.3.0-beta2-build3683\tools\net452\xunit.console.exe .\test\LogJam.UnitTests\bin\Debug\LogJam.UnitTests.dll 00:00:07.6589340
.\packages\xunit.runner.console.2.3.0-beta3-build3699\tools\net452\xunit.console.exe .\test\LogJam.UnitTests\bin\Debug\LogJam.UnitTests.dll 00:00:06.7863932
```

In all cases the console runner reporting test running time was similar, eg from the first run:

2.1.0:
=== TEST EXECUTION SUMMARY ===
   LogJam.UnitTests  Total: 107, Errors: 0, Failed: 0, Skipped: 9, Time: 6.320s

2.2.0:
=== TEST EXECUTION SUMMARY ===
   LogJam.UnitTests  Total: 107, Errors: 0, Failed: 0, Skipped: 9, Time: 6.223s
   
2.3.0-beta2-build3683:
=== TEST EXECUTION SUMMARY ===
   LogJam.UnitTests  Total: 107, Errors: 0, Failed: 0, Skipped: 9, Time: 6.596s
   
2.3.0-beta3-build3699:
=== TEST EXECUTION SUMMARY ===
   LogJam.UnitTests  Total: 107, Errors: 0, Failed: 0, Skipped: 9, Time: 6.342s


Interesting that in my first run the newest beta3 from myget appeared slower, but in the second run it was faster (and fastest overall). Either way the major slowdown in running time from 2.1.0 appears to be fixed.

**Comment by jawn** [comment] 2017-10-19 08:12
Given the positive speedups in recent versions, is this still an open issue?

**Comment by bradwilson** [comment] 2017-10-19 18:31
> In all cases the console runner reported test running time was similar. For 2.1.0, the actual running time was much longer.

That's because that summary is showing the sum of the amount of time spent executing each individual test. The overall "wall clock" time may be significantly larger (or smaller) depending on several factors.

> Either way the major slowdown in running time from 2.1.0 appears to be fixed.

> Given the positive speedups in recent versions, is this still an open issue?

We have definitely done substantial things to improve "wall clock" performance from 2.1 to 2.3, so I'm going to close this now.

**Closed by bradwilson** 2017-10-19 18:31 UTC
Labels: [a] Core framework, [t] Performance
