### ISSUE TITLE
Change of behavior in v2.5.0 when using `Assert.Equal()` with a custom `IEqualityComparer`

### ISSUE THREAD

**Issue by eduherminio** [xunit/xunit#2743] opened 2023-07-07 14:56 UTC
I'm experiencing the following change of behavior when bumping xunit to from 2.4.2 to 2.5.0.

Given:

```csharp
public class BitArrayComparer : IEqualityComparer<BitArray>
{
    public bool Equals(BitArray? x, BitArray? y)
    {
        return x?.ToBitString() == y?.ToBitString();
    }

    public int GetHashCode(BitArray obj)
    {
        return obj.ToBitString().GetHashCode();
    }
}
```

and the following test code:

```csharp
public class BitArrayComparerTest
{
    [Fact]
    public void BitArrayComparer()
    {
        var set = new HashSet<BitArray>
            {
                new BitArray(new[] { true, false }),
                new BitArray(new[] { false, true }),
            };

        var otherSet = new HashSet<BitArray>
            {
                new BitArray(new[] { true, false }),
                new BitArray(new[] { false, true }),
            };

        // Without the comparer
        Assert.NotEqual(set, otherSet);
        Assert.False(set == otherSet);

        var aggregatedSet = new HashSet<BitArray>();
        set.ForEach(s => aggregatedSet.Add(s));
        otherSet.ForEach(s => aggregatedSet.Add(s));
        Assert.Equal(4, aggregatedSet.Count);

        // Using the comparer
        Assert.Equal(set, otherSet, new BitArrayComparer());      // <----- Passing before, failing now
}
```

This test went red when Dependabot tried to bump xunit version in this PR: https://github.com/eduherminio/SheepTools/pull/136

```log
[xUnit.net 00:00:03.38]     SheepTools.Test.BitArrayComparerTest.BitArrayComparer [FAIL]
  Failed SheepTools.Test.BitArrayComparerTest.BitArrayComparer [[54](https://github.com/eduherminio/SheepTools/actions/runs/5486106129/jobs/9995760210?pr=136#step:13:55) ms]
  Error Message:
   Assert.Equal() Failure: HashSets differ
Expected: [[···], [···]]
Actual:   [[···], [···]]
  Stack Trace:
     at SheepTools.Test.BitArrayComparerTest.BitArrayComparer() in /_/tests/SheepTools.Test/BitArrayComparerTest.cs:line 34
```

.NET version: 6.0.411

[Here's another CI run](https://github.com/eduherminio/SheepTools/actions/runs/5487677039/jobs/9999455528) (using the same .NET version and xunit 2.4.2) that I triggered after the failed one to make sure the results were consistent.

**Comment by Kharos** [comment] 2023-07-10 10:17
**Note that this does not just happen when using a custom IEqualityComparer**, as XUnit is [internally using equality comparers](https://github.com/xunit/assert.xunit/blob/1886f12618ad509776fd977cdcffbc772a4957c2/EqualityAsserts.cs#L81).

For example we have a case in our code where an `Assert.Equal(x, y)` suddenly fails with two strings. Looking at the details the two strings are different but equivalent under unicode rules (e.g. `StringComparison.InvariantCulture` will treat the strings as equal. Up to now this assert succeeded, now it fails.

This looks like a regression that has the potential to really screw with other people's code.

**Comment by bradwilson** [comment] 2023-07-15 20:47
@Kharos I can't get your repro to compile, because I'm missing the `ToBitString` function.

**Comment by bradwilson** [comment] 2023-07-15 20:47
Also, please provide a repro case for the strings. Thanks!

**Comment by bradwilson** [comment] 2023-07-16 10:38
I am going to close this as completed, as I've addressed the issue with HashSet.

-----

Your comment regarding strings is unaddressed. I did a quick verification with two simple tests:

```csharp
[Fact]
public void Strings_1()
{
    Assert.Equal("foo", "FOO", StringComparer.InvariantCulture);
}

[Fact]
public void Strings_2()
{
    Assert.Equal("foo", "FOO", StringComparer.InvariantCultureIgnoreCase);
}
```

Strings_1 fails as expected, and Strings_2 passes as expected. Without knowing what strings you think should be passing and/or failing here, it's impossible for me to repro the problem. If you open a new issue for your string issue, please provide a full repro. Thanks!

**Closed by bradwilson** 2023-07-16 10:38 UTC
Labels: type: Bug, help wanted, area: Assertion library

**Comment by eduherminio** [comment] 2023-07-16 14:29
Thanks @bradwilson, fix verified in `2.5.1-pre.9` (from https://www.myget.org/F/xunit/api/v3/index.json).

PD: You did guess the [`ToBitString()` implementation](https://github.com/eduherminio/SheepTools/blob/main/src/SheepTools/Extensions/BitArrayExtensions.cs#L23-L26) correctly, sorry for not providing it straight away:

```csharp
    public static string ToBitString(this BitArray bitArray)
    {
        return string.Join("", bitArray.Cast<bool>().Select(bit => bit ? 1 : 0));
    }
```

**Comment by Kharos** [comment] 2023-07-17 06:28
@bradwilson A simple test case should be:
```
Assert.Equal("ééé", "e\u0301e\u0301e\u0301");
```
This should succeed in 2.4.2 but fail in 2.5.0 (because the underlying code does `Equal(expected, actual, GetEqualityComparer<T>());`). Reading your comments I expect that it will succeed with your fix.

**Comment by bradwilson** [comment] 2023-07-17 06:42
That doesn't call Assert.Equal<T>, it calls the special string overload.

**Comment by Kharos** [comment] 2023-07-17 06:45
> That doesn't call `Assert.Equal<T>`, it calls the special string overload.

You are right, sorry. I had to re-check our code as it was not written by me. The code is rather complex (it's part of a test that parses json and compares the result to the expected result) and I over-simplified. The following should reproduce the situation:
```
string expectedValue = "e\u0301e\u0301e\u0301";
object propertyValue= "ééé";
Assert.Equal(expectedValue, propertyValue);
```
```

**Comment by bradwilson** [comment] 2023-07-17 06:49
Out of curiosity, why are you bypassing the built-in string comparison? It's much more useful.

**Comment by bradwilson** [comment] 2023-07-17 06:51
This is still broken in 2.5.1-pre.9, and I'm not sure I know enough about what you're trying to accomplish here to understand why it's broken or how to fix it. Either way, please open a new issue.

**Comment by Kharos** [comment] 2023-07-17 06:53
> Out of curiosity, why are you bypassing the built-in string comparison? It's much more useful. Is it because it makes this case pass?

I am not the original author of that test case so I have to give my best guess. Reading the code it passes some json into a wrapped json parser and then compares the property value that is coming out to the expected property value. As json properties are not necessarily strings, the signature of the property that holds the parsed json value ends up `object`.

**Comment by bradwilson** [comment] 2023-07-17 07:01
It also has different output results, depending on the runner, but I suspect that's because `dotnet test` does not set its console output format to Unicode (our console runner sets the console output to UTF-8):

![image](https://github.com/xunit/xunit/assets/16944/63ca7390-7c77-4f54-8fe8-ee56d0c8b290)

**Comment by bradwilson** [comment] 2023-07-17 07:09
.NET 7 doesn't think they're equal:

![image](https://github.com/xunit/xunit/assets/16944/cbba992e-7484-4e93-bdda-d665d840eb02)

Honestly at the moment I'm leaning towards this being an "accidental & unintended feature" in 2.4.x.

**Comment by Kharos** [comment] 2023-07-17 07:09
> It also has different output results, depending on the runner

Both of these are ok, our original Jenkins output was:
```
Expected: ééé
Actual:   ééé
```
You can imagine the confusion that this caused 😂.

> Either way, please open a new issue.

I am still debating with myself if I should. On the one hand I feel like the new behavior is "more correct" as the two strings are not equal (and the `Assert.Equal<string>` overload will fail this case). On the other hand it is an undocumented behavior change...

**Comment by bradwilson** [comment] 2023-07-17 07:12
> On the other hand it is an undocumented behavior change...

I have no problem with saying that unintended behavior is unsupported. I've done it more than once in the past when closing issues. It's impossible to cover every single case when so many of them are simply unknown ahead of time (like this one). I have a bit of curiosity as to exactly _why_ it passed in the past, but that doesn't necessarily mean I want to revert to the old behavior. When in doubt, behaving like the framework does (unless we're explicitly and purposefully doing something different) is a pretty good rule of thumb for me.

**Comment by bradwilson** [comment] 2023-07-17 07:15
Another data point, for what it's worth: Powershell's `-eq` operator considers the strings to be equal:

![image](https://github.com/xunit/xunit/assets/16944/2825e82f-b5dc-4cc1-bd95-906b793b10de)

**Comment by Kharos** [comment] 2023-07-17 07:18
>.NET 7 doesn't think they're equal:

Even older versions of .net will tell you that the two strings are not equal when using `==`. They will be considered equal under invariant culture though, e.g. `"e\u0301e\u0301e\u0301".Equals("ééé", StringComparison.InvariantCulture)` will evaluate to `true`. I suspect that this is the reason for the powershell behavior that you mention. I also suspect that the 2.4.x code somehow ended in a custom comparer that was using `InvariantCulture`.

>Honestly at the moment I'm leaning towards this being an "accidental & unintended feature" in 2.4.x.

>I have no problem with saying that unintended behavior is unsupported.

I can totally live with that - the fact that it passes in 2.4.x while `==` returns false was somewhat unexpected for me, and I have in the meantime changed our code to explicitly do a string comparison using `InvariantCulture`, that is much clearer in my opinion. So bottom line, closed 🙂 .

**Comment by bradwilson** [comment] 2023-07-17 07:19
`Assert.Equal(string, string)` has a lot of existing flags:

https://github.com/xunit/assert.xunit/blob/20e76223edd758f7490e6b71ef47a8539d588335/StringAsserts.cs#L304-L325

I wonder if there's a place for Yet Another Flag™️ to describe this desired behavior.

**Comment by Kharos** [comment] 2023-07-17 07:25
> I wonder if there's a place for Yet Another Flag™️ to describe this desired behavior.

I honestly feel that it is already too complicated with the flags that it currently has. When somebody calls that overload in a PR that I am reviewing, I will probably have to look up the definition of `Asser.Equal(..)` to verify the intention of the PR author. I think if people want non-standard behavior they can use `Assert.True` with a custom message instead:

```
Assert.True(expected.Equals(actual, StringComparison.InvariantCulture), $"Strings not equal.\nExpected: {expected}\nActual: {actual}");
```

It's how I fixed our failing test. Yeah it's a bit longer but I am fine with that.
