### ISSUE TITLE
Analyzer AssertEqualShouldNotBeUsedForCollectionSizeCheck throws exception

### ISSUE THREAD

**Issue by jmarolf** [xunit/xunit#1431] opened 2017-08-30 01:33 UTC
Pre-requisites: Have Visual Studio 2017.3 installed

1. Sync https://github.com/dotnet/project-system to SHA 24a1bc267bef98b60d8911c5473c2485ff539c31
2. Open solution ProjectSystem.sln
3. Add Xunit Analyzer to project `Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests`

Result:
Analyzer throws exception
```
Analyzer `Xunit.Analyzers.AssertEqualShouldNotBeUsedForCollectionSizeCheck` threw an exception of type `System.ArgumentException` with message 'Wrong number of type arguments	
```

**Comment by marcind** [comment] 2017-08-30 17:51
Duplicate of #1408

**Closed by marcind** 2017-08-30 17:51 UTC
