### ISSUE TITLE
xunit.runner.dnx: dnx46 on Mono

### ISSUE THREAD

**Issue by AlekseyMartynov** [xunit/xunit#518] opened 2015-08-02 09:55 UTC
I noticed that `2.1.0-beta4-build132`  switched from dnx451 to dnx46.
It seems that dnx46 does not work in Mono (4.3 nightly):

    System.InvalidOperationException: The current runtime target framework is not compatible with 'LimeBean.Tests'.
    Current runtime Target Framework: 'DNX,Version=v4.5.1 (dnx451)'
      Type: Mono
      Architecture: x64
      Version: 1.0.0-beta6-12256
    Please make sure the runtime matches a framework specified in project.json

**Comment by CoreyKaylor** [comment] 2015-08-02 19:27
Yeah, I just ran into this as well.

**Comment by bradwilson** [comment] 2015-08-02 19:51
I'm working on a fix today.

**Comment by bradwilson** [comment] 2015-08-02 20:14
I think it's fixed now. Give it a shot.

https://github.com/xunit/dnx.xunit/commit/833b565cbff794db633c314dc1e91e59fd9ca944

**Comment by AlekseyMartynov** [comment] 2015-08-02 21:01
@bradwilson 
builds ok, but runner fails

    System.TypeInitializationException: The type initializer for 'Xunit.Sdk.XunitTestFrameworkDiscoverer' threw an exception.
    System.MissingMethodException: Method not found: 'System.String System.String.Format(System.IFormatProvider, System.String, System.Object)'.

this?
http://stackoverflow.com/a/30559657

**Comment by bradwilson** [comment] 2015-08-02 21:09
I guess it's time to fire up my Linux VM. :unamused:

**Comment by bradwilson** [comment] 2015-08-02 21:48
Making progress... with xunit build 3103, I'm able to run tests with parallelization turned off (if I turn it on, it complains that it can't load the `MaxConcurrencySyncContext` type).

@AlekseyMartynov Can you verify that your tests are able to run with 3103 (with parallelization off)?

**Comment by bradwilson** [comment] 2015-08-02 21:51
BTW, this is the version of Mono I'm testing with:

```
$ mono --version
Mono JIT compiler version 4.0.3 (Stable 4.0.3.19/e4f44c1 Fri Jul 24 08:37:58 UTC 2015)
```

**Comment by CoreyKaylor** [comment] 2015-08-02 22:12
@bradwilson with -parallel none the tests pass on mono for me as well.

https://travis-ci.org/CoreyKaylor/Lightning.NET

**Comment by bradwilson** [comment] 2015-08-02 22:49
The issue is that [ExecutionContext](https://msdn.microsoft.com/en-us/library/system.threading.executioncontext(v=vs.110).aspx) is not available in the [System.Threading 4.0.0 back-compat NuGet package](https://www.nuget.org/packages/System.Threading/4.0.0); it's only available in 4.0.10, which is not compatible with .NET 4.5.

I'm working on a fix right now. Hopefully this is the last thing. :)

**Comment by bradwilson** [comment] 2015-08-03 00:54
Okay, I had to temporarily disable support for setting maximum # of threads. You can still turn parallelism on or off, but if you run things in parallel, it will use the built-in thread pool (and whatever limits are associated with that).

One last time, please verify with:

```
xunit 2.1.0-beta4-build3106
xunit.runner.dnx 2.1.0-beta4-build134
```

I was able to successfully run xUnit.net's unit tests on Debian w/ Mono 4.0.3, so I assume you should no more issues (and `-parallel none` should no longer be required).

**Comment by AlekseyMartynov** [comment] 2015-08-03 02:33
@bradwilson fixed, thank you.

**Closed** 2015-08-03 03:14 UTC
Labels: affects: dnx.xunit, type: Bug
