### ISSUE TITLE
mutliple test adapters in visual studio 2017

### ISSUE THREAD

**Issue by rm2k** [xunit/xunit#1188] opened 2017-03-28 08:43 UTC
Running my tests on visual studio 2017, I get this warning message:

Multiple test adapters with the same uri 'executor://xunit/VsTestRunner2' were found. Ignoring adapter 'Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner'. Please uninstall the conflicting adapter(s) to avoid this warning.

here is how my `*.csproj` look like:

      <ItemGroup>
          <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
          <PackageReference Include="Moq" Version="4.7.8" />
         <PackageReference Include="xunit" Version="2.2.0" />
         <PackageReference Include="FluentAssertions" Version="4.19.2" />
          <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
    </ItemGroup>

I don't remember installing any adapter other than adding the references above? Could the clash be between `"Microsoft.NET.Test.Sdk` and `xunit.runner.visualstudio`?

**Comment by bradwilson** [comment] 2017-03-28 16:27
Do you perhaps have the old test runner VSIX installed?

**Comment by rm2k** [comment] 2017-03-28 17:33
I have vs2015 side by side with vs2017. My project is upgrade from `project.json` and `*.xproj`.  

I have multiple projects solution and to my surprise I've just tracked this problem to just 1 project. removing it, the warning goes away, and running it alone the problem comes back. 

I'll recreate just that test project using the vs2017 template and see what happens.

**Comment by rm2k** [comment] 2017-03-29 06:26
yeah. everything works fine till i add reference to my project.

**Comment by lythix** [comment] 2017-04-26 16:02
I'm also getting this exact error message. 
The project it's happening for me on (tested on two different machines) is a fork of this repo
https://github.com/Azure/service-fabric-services-and-actors-dotnet  (develop branch)

**Comment by bradwilson** [comment] 2017-04-26 18:31
Closing, as it appears that this issue is related to Hangfire and not xUnit.net.

**Closed by bradwilson** 2017-04-26 18:31 UTC
Labels: [r] External

**Comment by lythix** [comment] 2017-04-27 03:49
The issue I hit trying to run tests against service fabric repo doesn't use Hangfire unless its a dependency I don't know about. Until now, had never heard of it.

**Comment by bradwilson** [comment] 2017-04-27 04:02
It sounds like the same dependency issue is there. It sounds like the issue is likely to be one for the .NET team, not us, since it relates to loading dependent assemblies (something we don't do).

**Comment by lythix** [comment] 2017-04-27 04:55
Is there a bug raised for this issue somewhere?
If not is that something I can add? I'd like to be able to run unit tests in visual studio, and dont want the issue forgotten/missed.
Thanks

**Comment by Rutix** [comment] 2017-10-12 10:06
@lythix did you find a solution for this? I think we are running in the same problem atm

**Comment by eoner** [comment] 2018-03-08 09:10
For me, it was because i had two test projects with different Xunit versions in the same VS Solution.
Once I've updated everything to the same version, the problem went away.
