### ISSUE TITLE
xunit.runner.visualstudio contains wrong version of xunit.runner.utility.dll

### ISSUE THREAD

**Issue by attilah** [xunit/xunit#1148] opened 2017-03-01 21:01 UTC
When migrating our project to 2.2.0 of the xunit packages it turned out that I got an assembly loading failure.

```xunit.runner.reporters.net452.dll``` tries to load ```xunit.runner.utility.net452.dll```, which is a reference of that dll, but the ```xunit.runner.visualstudio``` 2.2.0 package contains ```xunit.runner.utility.net35.dll```.

**Comment by bradwilson** [comment] 2017-03-02 01:48
Is this a critical failure, or does it ignore the error and move on?

**Comment by attilah** [comment] 2017-03-02 01:54
test running fails since looking for ```xunit.runner.utility.net452.dll``` which is not there.

After I added a direct reference to ```xunit.runner.utility``` package it got the right dll there so our tests passed, but a "standalone" reference to ```xunit.runner.visualstudio``` is bringing this error.

**Comment by bradwilson** [comment] 2017-03-02 02:02
I assume this is for a desktop unit test project?

**Comment by attilah** [comment] 2017-03-02 02:06
The unit test targets net462, yes, using the new project system.

The error happened when we run the tests from command line from a shared output folder of binaries.

Repro:
1. clone https://github.com/dotnet/orleans
2. open cmd in the vNext folder
3. remove ```xunit.runner.utility``` package reference from csproj files in test folder.
4. build.cmd
5. test.cmd

**Comment by danrozenberg** [comment] 2017-05-26 00:20
I am facing similar problems with version 2.2
I am trying to run the following sample: https://github.com/xunit/samples.xunit/blob/master/TestRunner/Program.cs

When I run it, the assembly load error...

``System.IO.FileLoadException: 'Could not load file or assembly 'xunit.runner.utility.net452, Version=2.2.0.3545, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'``

Downgrading to 2.1 solves the issue...

**Comment by danrozenberg** [comment] 2017-06-16 22:54
Seems to be fixed in 2.3.0-beta....

**Closed** 2017-06-17 00:48 UTC
Labels: [a] visualstudio.xunit, [t] Bug

**Comment by Frankwayne** [comment] 2019-02-28 16:34
I'm having this issue and I think it may be a cause of something else.     reverting back to version 2.2.0  fixed the issue for me, due to the issue being fixed by people using other version than me and reporting the version I'm using breaks their unit test.

I have used xunit.runner.visualstudio    

2.3.0,
2.3.1,
2.4.0
2.4.1       



All unit test run fine inside visual studio  Test Explorer, but my dotnet test command in my build process is  causes the following error 

Catastrophic failure: System.IO.FileLoadException: Could not load file or assembly 'xunit.runner.utility.net452, Version=2.3.1.3858,


   I have a unit test project that  is targeting the following frameworks 

```
 <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>
  </PropertyGroup>

```



` dotnet test {{proejct path}}     -l trx -r {{results folder path}}  --filter Category!=Integration /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  
`

Here is a copy of my  directory.Build.props    that actually works.  I'm not sure why kicking my xunit.runner.visualstudio    version above 2.2.0    breaks my dotnet test command.   
```
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
    
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.analyzers" Version="0.10.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
    

    <PackageReference Include="coverlet.msbuild" Version="2.5.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>



    <Content Condition="$(Configuration)=='Debug'" Include="$(MsBuildThisFileDirectory)\xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>

```

**Comment by bradwilson** [comment] 2019-02-28 16:36
@Frankwayne If you can provide a repro project, please open a new issue for this. Thanks!

**Comment by Frankwayne** [comment] 2019-02-28 16:47
sure, it may take some time  as its a work project and I will need to reproduce the issue into a simple project
