### ISSUE TITLE
Request non-generic Assert.Throws to support null exception Type

### ISSUE THREAD

**Issue by daerhiel** [xunit/xunit#2193] opened 2020-11-14 10:24 UTC
Currently ``Exception Throws(Type exceptionType, Action testCode)`` doesn't allow nulls on exceptionType parameter. I suggest it to accept nulls and interpret it as 'no exception throws is expected. That would be useful to enable this testing pattern without need to write complex wrappers:

```csharp
        [Theory]
        [InlineData(0, null)]
        [InlineData(1, typeof(InvalidOperationException))]
        public void BehaviorTest(int input, Type exceptionType)
        {
            Assert.Throws(exceptionType, () =>
            {
                if (input != 0)
                    throw InvalidOperationException("Can't handle that");
            });
        }
```

**Comment by bradwilson** [comment] 2020-11-21 20:21
We used to have `Assert.DoesNotThrow()` which is what you're asking for, but it's pointless, because all code is implicitly this (any code which throws, fails).

I also actually don't like `Assert.Throws()` when it comes right down to it, because it violates the AAA pattern which I prefer. So my suggestion would be to re-write this with AAA like this:

```csharp
[Theory]
[InlineData(0, null)]
[InlineData(1, typeof(InvalidOperationException))]
public void BehaviorTest(int input, Type exceptionType)
{
    var ex = Record.Exception(() =>
    {
        if (input != 0)
            throw InvalidOperationException("Can't handle that");
    });

    if (exceptionType == null)
        Assert.Null(ex);
    else
        Assert.IsType(exceptionType, ex);
}
```

I'm not a big fan of accepting `null` for `Assert.IsType` either, so I'd do the conditional.

Yet another alternative would be to bring in the assertion library via source (swap your `xunit` NuGet package reference for three separate references: `xunit.analyzers`, `xunit.assert.source`, and `xunit.core`). Then you'll get a source version of `Assert`, which is a partial class that could be extended as desired. You could write something like:

```csharp
namespace Xunit
{
    public partial class Assert
    {
        public static void MaybeThrows(Type? exceptionType, Action code)
        {
            // ... implementation here ...
        }
    }
}
```

Then you could use your custom assertion, and move the conditional logic there.

**Comment by daerhiel** [comment] 2020-11-22 08:39
So what you're literally saying that any use of Throws is bad because it breaks AAA.

**Comment by bradwilson** [comment] 2020-12-01 00:27
Another way to phrase it is: If you are a strict AAA adherent, you wouldn't use `Assert.Throws`.

**Comment by bradwilson** [comment] 2021-01-18 20:09
Closing this as By Design.

**Closed by bradwilson** 2021-01-18 20:09 UTC
Labels: status: By Design / Won't Fix
