### ISSUE TITLE
Assert.Contain products incorrect result when object implements IComparable<T>

### ISSUE THREAD

**Issue by clawrenceks** [xunit/xunit#1926] opened 2019-04-18 20:30 UTC
I am encountering an issue with use of Assert.Contains in XUnit - it is not returning the correct result in a particular scenario in my project. Details and reproduction steps below.

In my project when I write the following code, the test result is expected (the item is indeed not in the collection) (but a compiler warning is generated, to say that Assert.Contains should be used instead).

Assert.False(collection.Contains(object))

When I change this Assert to use Contains as follows:

Assert.Contains(object, collection) then then result is returned as True, even though the item is not in the collection.

In this particular case, in my object I have overridden equality so that structural equality for the object is used, rather than reference equality. I know that my equality implementation is correct as I have it covered with unit tests and have used a similar implementation many times.

What is different in this case for me is that my object also implements IComparable<T> and as such has a CompareTo method. From stepping through the code I can see that the Assert.Contains statement is calling the CompareTo method AFTER checking equality. In this instance the equality checks are returning false, as I would expect, but the CompareTo is returning true (which in my implementation is also correct).

I am not sure why the xUnit Assert.Contains is executing the CompareTo method from the IComparable<T> interface however. This interface is for sorting / ordering and not equality checking, so it seems like a bug to me that Assert.Contain is calling this and returning a false positive in my case, whereas the .net implementation of Contains on the collection returns the expected result.

**Comment by bradwilson** [comment] 2019-04-20 18:27
Support for `IComparable<T>` in addition to `IEquatable<T>` is about maximum compatibility when determining the equality of two objects. For performance reasons, our code prefers `IEquatable<T>` over `IComparable<T>` when both are implemented (https://github.com/xunit/assert.xunit/blob/92395f59e3ff47d6d5a1edeced9e99ccfef9fd37/Sdk/AssertEqualityComparer.cs#L46-L81), as the former only needs to return `true` or `false`, rather than relative position for sort order. Usage of `Equals` is the last-case resort in our choices, precisely because the default behavior is identity rather than structural equality.

That said, there's nothing wrong with using `IComparable<T>` to determine if two values are equal. IMO, it would be a violation of the spirit (if not the letter) of the contract for `IComparable<T>` to return anything other than `0` for an object for which `IEquatable<T>` would return `true`.

/cc @terrajobst for sanity checking purposes. 😃

**Comment by clawrenceks** [comment] 2019-04-22 00:42
I am not sure I agree with the sentiment that there is nothing wrong with using IComparable<T> to determine if to values are equal for equality purposes. Obviously using it to determine if two values are equal for sorting / ordering purposes makes perfect sense, as that is the intent of the interface.

To use an example of why I perceive this to be wrong. Consider the scenario of a type that should use reference equality, but implements IComparable<T> for sorting /ordering. With the current explanation you have given above, if I have two instances that for ordering / sorting purposes are equal and a collection containing only the first instance but not the second instance - when I call Assert.Contains(instance2, collection) I believe the assert would pass, even though the second instance is not in the collection.

It is in my opinion confusing for Assert.Contains to return a different result than the dotnet implementation of Contains. In my scenario  the dotnet implementation of Contains is correct and the xUnit implementation is yielding an incorrect result

**Comment by bradwilson** [comment] 2019-04-22 02:55
I'm not against removing support for `IComparable<T>`, but it's probably worth pointing out that this is the first time it's come up in nearly 12 years. There is a clearly simple work-around (implement `IEquatable<T>`, which honestly you should do instead of/in addition to implementing `Equals`), so nobody should be blocked.

**Comment by terrajobst** [comment] 2019-08-21 22:14
I've asked folks on the API review board. I find myself agreeing with @clawrenceks but everyone else was agreeing with @bradwilson's position that returning 0 is the same as returning true form `Equals`. So xUnit's behavior seems inline with the BCL

**Comment by bradwilson** [comment] 2019-08-22 21:04
🤯

It's not often majorities of people agree with me. I'm gonna print this thread out and frame it. 😂

**Comment by bradwilson** [comment] 2020-08-15 21:19
Closed as by design.

**Closed by bradwilson** 2020-08-15 21:19 UTC
