### ISSUE TITLE
Add way to compare strings more fully ignoring whitespace.

### ISSUE THREAD

**Issue by Clockwork-Muse** [xunit/xunit#2440] opened 2021-12-13 06:42 UTC
Currently, when comparing strings, options like `ignoreLineEndingDifferences` and `ignoreWhiteSpaceDifferences` require there be _at least one_ instance of the various characters

```csharp
// Succeeds
Assert.Equal("    ", " ", ignoreWhiteSpaceDifferences: true);
// Fails
Assert.Equal("    ", String.Empty, ignoreWhiteSpaceDifferences: true);
```

... I'm looking for a way to compare two strings ignoring any whitespace differences at all, so that the second test succeeds

**Comment by bradwilson** [comment] 2022-01-10 00:57
I would not want this to affect the existing behavior (for example, `Assert.Equal("A B", "AB", ignoreWhiteSpaceDifferences: true)` fails, and this is expected behavior). Instead, I think we should have a different flag (like maybe `ignoreAllWhiteSpace`), and make sure the XML docs for the two flags make it clear how they differ, and refer to the other flag when appropriate.

**Comment by bakermo** [comment] 2022-01-23 16:10
Hello! I'd like to contribute.  Would you mind if I took a stab at this?

**Comment by bakermo** [comment] 2022-05-12 13:52
@mongeon I did not end up taking it, go right ahead :)

**Comment by VictorLlanir** [comment] 2022-06-18 21:14
Hello, @mongeon, did you worked on this issue? If not, I would like to contribute.

**Comment by mongeon** [comment] 2022-06-20 12:15
> Hello, @mongeon, did you worked on this issue? If not, I would like to contribute.

No, didn't go far on this. Please feel free to contribute to this.

**Comment by gy-soft** [comment] 2022-07-06 02:25
This new behavior seems equivalent to removing all white space from actual and expected before comparing. Am I understanding ok?

**Comment by Clockwork-Muse** [comment] 2022-07-06 04:27
@gy-soft - Yes, that's correct.

**Comment by jhowlett-scottlogic** [comment] 2022-07-18 13:40
@VictorLlanir did you start working on this?

**Comment by jhowlett-scottlogic** [comment] 2022-07-26 09:57
I have a possible solution for this that also addresses Equal(Span<char>) but waiting on a reply to a workflow [query](https://github.com/xunit/xunit/discussions/2558).

**Comment by bradwilson** [comment] 2023-05-04 05:30
Merged. Thanks!

**Closed by bradwilson** 2023-05-04 05:30 UTC
Labels: type: Feature, help wanted, area: Assertion library, good first issue, target: 3.0, target: 2.x

**Comment by wizofaus** [comment] 2024-02-01 05:07
Doesn't work as I expected - Assert.Equal("<a></a>", "<a>  </a>", ignoreAllWhiteSpace: true); still fails?

**Comment by bradwilson** [comment] 2024-02-01 07:01
@wizofaus Carriage returns and line feeds aren't treated as white space, they're treated as line ending characters. It looks like you're trying to use to compare HTML, which has its own rules about when line ending characters are equivalent to white space which isn't something that we directly support. Just one example of a place where this rule is "inconsistent" is when HTML is parsing text which is pre-formatted (i.e., inside of `<pre>` or `<code>` or something equivalent) vs. normally formatted.

You may be able to get away with converting line ending characters into white space characters if you know your data doesn't have pre-formatted content, but this is likely to be full of potential edge cases. I would strongly suggest finding a third part library that's designed to compare HTML equivalence.

**Comment by wizofaus** [comment] 2024-02-01 07:42
Well, xml technically, but in my book linefeeds are whitespace (unless specified otherwise).  Anyway, yes, with a replace on \n (and \r) characters first it works as expected.  For the purposes of my test, it was sufficient.

**Comment by wizofaus** [comment] 2024-02-01 22:14
> @wizofaus - You still shouldn't be doing it with string comparisons, because there are additional transformations that might be made that still result in semantically identical documents. The most likely one being the order of attributes.

Sure, if I really did want to check that two complete XML documents were semantically equivalent despite order of attributes etc. etc.  In my particular case the test is far easier to read/understand as it is, just confirming that an XML fragment has the expected elements/attributes in the given order.  Anyway, happy to have this closed.
