### ISSUE TITLE
ArgumentFormatter doesn't pretty-print rank-1 variable-bound arrays correctly

### ISSUE THREAD

**Issue by GrabYourPitchforks** [xunit/xunit#2534] opened 2022-06-11 02:17 UTC
## Summary

`ArgumentFormatter` does not pretty-print rank-1 variable-bound arrays correctly. It prints `int[]` when it should instead print `int[*]`.

## Repro

In the file __ArgumentFormatterTests.cs__, take this theory data:

https://github.com/xunit/xunit/blob/c27a91f8cbcee37cb45699a3a81287bca225e876/src/xunit.v3.assert.tests/Asserts/Sdk/ArgumentFormatterTests.cs#L176-L189

And insert this test case into it:

```cs
{ typeof(int).MakeArrayType(1), "typeof(int[*])" },
```

Then run __build.cmd__ and you will observe the failure when the unit tests run.

```txt
xUnit.net v3 In-Process Runner v0.1.1-pre.30-dev+c27a91f8cb (64-bit .NET Core 3.1.25)
  Discovering: xunit.v3.assert.tests (method display = ClassAndMethod, method display options = None)
  Discovered:  xunit.v3.assert.tests (found 826 test cases)
  Starting:    xunit.v3.assert.tests (parallel test collections = on, max threads = unlimited)
    ArgumentFormatterTests+SimpleValues.TypeValue(type: typeof(int[]), expected: "typeof(int[*])") [FAIL]
      Assert.Equal() Failure
                           ↓ (pos 11)
      Expected: typeof(int[*])
      Actual:   typeof(int[])
                           ↑ (pos 11)
      Stack Trace:
        C:\xunit\src\xunit.v3.assert.tests\Asserts\Sdk\ArgumentFormatterTests.cs(197,0): at ArgumentFormatterTests.SimpleValues.TypeValue(Type type, String expected)
  Finished:    xunit.v3.assert.tests
=== TEST EXECUTION SUMMARY ===
   xunit.v3.assert.tests  Total: 883, Errors: 0, Failed: 1, Skipped: 0, Time: 0.253s
```

## Sample fix

The issue is in these lines in __ArgumentFormatter.cs__.

https://github.com/xunit/assert.xunit/blob/43e3e208a597bc1a4c77f2665f39f98e7401c157/Sdk/ArgumentFormatter.cs#L310-L320

They should have a call to [`Type.IsSZArray`](https://docs.microsoft.com/dotnet/api/system.type.isszarray), as shown below.

```cs
if (typeInfo.IsSZArray)
{
	arraySuffix += "[]";
}
else
{
	var rank = typeInfo.GetArrayRank();
	if (rank == 1)
	{
		arraySuffix += "[*]";
	}
	else
	{
		arraySuffix += $"[{new string(',', rank - 1)}]";
	}
}
```

This can also be implemented as an extension method to work downlevel.

```cs
public static bool IsSzArrayType(this Type type)
{
#if NETCOREAPP2_0_OR_GREATER
    // framework built-in function
    return type.IsSZArray;
#else
    // bounce through a few layers of indirection to detect this
    return type.IsArray && type == type.GetElementType().MakeArrayType();
#endif
}
```

## Discussion

In .NET, there are actually __three__ ways to represent arrays:

* `int[]`, which is a standard single-dimensional, zero-indexed array ("SZ array")
* `int[,,,]`, which is a multi-dimensional array (not necessarily zero-indexed)
* `int[*]`, which is a single-dimensional array (not necessarily zero-indexed)

The last two are also called _variable-bound arrays_, and the rank-1 syntax of `[*]` has an asterisk to disambiguate it from the standard `[]` SZ array syntax.

This is fairly easy to see in PowerShell as well:

```txt
❯ [int].MakeArrayType().Name
Int32[]

❯ [int].MakeArrayType(1).Name
Int32[*]

❯ [int].MakeArrayType(2).Name
Int32[,]

# Also shows that the runtime considers int[] and int[*] truly different, incompatible types
❯ [int].MakeArrayType().Equals([int].MakeArrayType(1))
False
```

**Comment by GrabYourPitchforks** [comment] 2022-06-17 15:48
FWIW, if the maintainers do decide this is worth taking, it seems like a good "starter" candidate for an external contributor to dip their toes in the water.

**Comment by Tomheza** [comment] 2022-07-29 09:35
Hi, I would like to investigate this issue

**Comment by Eliminator1999** [comment] 2022-10-05 21:36
Hi, I am a first time contributor. Would like to take this task, appreciate any help with starting

**Comment by zachspang** [comment] 2022-11-29 20:25
I am going to start working on this.

**Comment by Jaswir** [comment] 2023-01-25 18:36
Hi I'm trying to reproduce this so I can work on it and fix it. 

"Then run build.cmd and you will observe the failure when the unit tests run."

How can I do that? 
You mean using ./build from root folder?  And then maybe I can build just xunit.v3.assert.tests? 

I am used to just pressing run in visual studio to test out stuff..

**Comment by Jaswir** [comment] 2023-01-26 18:13
@GrabYourPitchforks  Ah I reproduced it. 
./build -3  with the adaptation reproduces it.  
Takes long time to run though. How can I run just this part"==> Running .NET Core tests (via Console runner) <=="

**Comment by bradwilson** [comment] 2023-01-26 21:22
> How can I run just this part"==> Running .NET Core tests (via Console runner) <=="

`./build TestCoreConsole -3`

**Comment by Jaswir** [comment] 2023-01-28 14:53
@bradwilson That command  ./build TestCoreConsole -3 still runs the ==> Compiling binaries (AnyCPU) <==
and ==> Compiling binaries (32-bit) <== part.  

But I found a faster way to do it in Visual Studio though.

**Comment by Jaswir** [comment] 2023-01-29 16:35
I tried running xunit.v3.assert.tests in visual studio on Debug mode. 
When trying to debug this issue I get lots of error throws. How can I debug this thing without constant error throws. 

![image](https://user-images.githubusercontent.com/15957528/215340551-4939c85a-fea2-4574-9fee-e39ed5b19d09.png)

**Comment by Jaswir** [comment] 2023-01-30 16:56
@bradwilson @GrabYourPitchforks @ExterminatorX99 @Clockwork-Muse @toseni 

I tried adding this inside of the while loop:

if (typeInfo.IsSZArray)
{
	arraySuffix += "[]";
}
else
{
	var rank = typeInfo.GetArrayRank();
	if (rank == 1)
	{
		arraySuffix += "[*]";
	}
	else
	{
		arraySuffix += $"[{new string(',', rank - 1)}]";
	}
}

But it says that 'Type' does not contain a definition for 'IsSZArray' and no accessible extension method 'IsSZArray' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

**Comment by bradwilson** [comment] 2023-02-02 05:06
That would seem to be a case of it not being available on .NET Framework or .NET Standard 2.0.

**Comment by bradwilson** [comment] 2023-02-05 00:00
> How can I debug this thing without constant error throws.

Unfortunately, Visual Studio does not realize this exception is _not_ unhandled and inappropriately breaks in the debugger when such exceptions would've been handled by the test framework. To me, the definition of "unhandled" would be "the app is about to crash", but that's clearly not the case here. Unfortunately, Visual Studio seems to disagree.

¯\_(ツ)_/¯

You'll have to ask someone on the Visual Studio team how to disable this behavior. I've not found a way.

**Comment by Jaswir** [comment] 2023-02-08 19:19
@bradwilson Is this issue stil open? 
Someone made a pull request a while ago. 
I checked the solution and it works, however it is not so clean and not implemented as an extension method as mentioned in the sample fix. Nor does it use the framework built in function IsSZArray. These areas could be improved.

**Comment by Jaswir** [comment] 2023-02-09 19:14
@bradwilson Is this issue still open? Saw there was a pull request a while ago. 
I tested it and it works, however it doesn't have a call to IsSZArray as requested in Sample Fix and isn't implemented as an extension method to work downlevel. 

Anyway I made a fix for it that makes a call to IsSZArray and also works downlevel incase IsSZArray is not available due to .NET Version

**Comment by bradwilson** [comment] 2023-02-10 04:21
@Jaswir I haven't looked at pull requests in a little while, so it's possible that there are multiple PRs out to fix this. I'll take a look at yours when I can get to it.

**Comment by bradwilson** [comment] 2023-02-12 01:29
Fixed with xunit/assert.xunit#59 and tested with #2669.

**Closed by bradwilson** 2023-02-12 01:29 UTC
Labels: type: Bug, help wanted, area: Assertion library, good first issue, target: 3.0
