### ISSUE TITLE
Assert.Throws reports the wrong call stack when the thrown exception is different than expected

### ISSUE THREAD

**Issue by geoffkizer** [xunit/xunit#2351] opened 2021-07-22 08:32 UTC
Repro:

```csharp
    public class MyTestClass
    {
        private void DoSomething() => throw new Exception("This is not an InvalidOperationException");

        [Fact]
        public void Test1()
        {
            Assert.Throws<InvalidOperationException>(DoSomething);
        }
    }
```

This results in output like so:

```
      MyTests.MyTestClass.Test1 [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.InvalidOperationException)
        Actual:   typeof(System.Exception): This is not an InvalidOperationException
        ---- System.Exception : This is not an InvalidOperationException
        Stack Trace:
          C:\<elided>(14,0): at MyTests.MyTestClass.DoSomething()
          ----- Inner Stack Trace -----
          C:\<elided>(14,0): at MyTests.MyTestClass.DoSomething()
```

Note the "stack trace" and "inner stack trace" are both the same -- the stack from where the exception is thrown. Neither are the stack where the Assert.Throws fails.

Compare to changing `DoSomething` so it does not throw at all:

```
      MyTests.MyTestClass.Test1 [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.InvalidOperationException)
        Actual:   (No exception was thrown)
        Stack Trace:
          C:\<elided>(19,0): at MyTests.MyTestClass.Test1()
```

This correctly reports the stack trace where the Assert.Throws fails.

Expected behavior:

Report the correct stack trace -- that is, where the Assert.Throws fails -- with an inner exception containing the incorrect exception as thrown by the action passed to Assert.Throws.

**Comment by bradwilson** [comment] 2021-07-26 03:29
There are two separate things at play here:

* Why is the stack trace doubled?

I'm not sure yet. 😁 

* Why is the stack trace missing line 19?

This is an easy one. Your Assert.Throws should be this:

```
Assert.Throws<InvalidOperationException>(() => DoSomething());
```

**Comment by bradwilson** [comment] 2021-07-26 03:41
I've opened a new issue for the doubled up exception information, so I'm going to close this for the other half being "by design".

**Closed by bradwilson** 2021-07-26 03:41 UTC

**Comment by geoffkizer** [comment] 2021-08-24 17:14
> * Why is the stack trace missing line 19?
> 
> This is an easy one. Your Assert.Throws should be this:
> 
> ```
> Assert.Throws<InvalidOperationException>(() => DoSomething());
> ```

I think you missed the point here.

Other Assert.XYZ methods report a stack trace where the Assert failed. In this case, that's line 19. Seems like this should do the same.

**Comment by geoffkizer** [comment] 2021-08-30 03:54
It's not a lambda vs non-lambda thing.

Assert.Throws is throwing an exception that does not include the stack trace of where the exception was thrown. That's super weird. I'm not even sure how you can do that. But it must be XUnit doing something to the stack trace, because that's definitely not standard .NET behavior.

Compare this to the Assert.Throws behavior when no exception is thrown from the invoked code (as shown above): as expected, the exception thrown by Assert.Throws contains a stack trace of where the exception was thrown, i.e. line 19.
