### ISSUE TITLE
AD0001: Analyzer 'Xunit.Analyzers.PublicMethodShouldBeMarkedAsTest' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by lcalabrese** [xunit/xunit#1452] opened 2017-09-13 06:38 UTC
I am getting a NullReferenceException with the following stack trace:

```
Exception occurred with following context:
Compilation: MyWebApplication.FunctionalTests
ISymbol: TestStartup (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.Analyzers.PublicMethodShouldBeMarkedAsTest.<>c__DisplayClass2_0.<AnalyzeCompilation>b__0(SymbolAnalysisContext symbolContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__38_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

I have a base web project (Microsoft.NET.Sdk.Web, target frameworks: net461;netcoreapp2.0) with a standard `Startup` class:

```

    public class Startup
    {
        public Startup(IConfiguration configuration, IHostingEnvironment environment)
        {
            Configuration = configuration;
            Environment = environment;
        }

        private IConfiguration Configuration { get; }
        private IHostingEnvironment Environment { get; }

        // This method gets called by the runtime. Use this method to add services to the container
        [UsedImplicitly]
        public virtual void ConfigureServices(IServiceCollection services)
        {
            //normal setup stuff goes here
        }

```

Then I have a test project which references this project. I am then creating a derived class which sets up a SQLite database to use for tests:

```
   [UsedImplicitly]
    public class TestStartup : Startup
    {

        public TestStartup(IConfiguration configuration, IHostingEnvironment environment) : base(configuration, environment)
        {

        }

        public override void ConfigureServices(IServiceCollection services)
        {
             //set up test in-memory database

            //then call the base
            base.ConfigureServices(services);
        }
    }
```

Note, `TestStartup` needs to be public, and there are no test methods in this class. It is simply used by a test fixture to set up a `TestServer` to test API calls.

Also, occasionally this error seems to disappear from the error list (or collapse to a seemingly-blank very thin line in the error list) but it will always eventually come back.

Using VS2017 and the following references for my test project:

```

  <ItemGroup>
    <ProjectReference Include="..\..\src\MyWebApplication\MyWebApplication.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta5-build3769" />
    <PackageReference Include="xunit" Version="2.3.0-beta5-build3769 " />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.3">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.0' ">
    <PackageReference Include="Microsoft.CodeCoverage" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" />
  </ItemGroup>
```

**Comment by TimLovellSmith** [comment] 2018-04-10 16:57
I have also encountered this issue with <package id="xunit.analyzers" version="0.8.0" targetFramework="net452" />

**Comment by bradwilson** [comment] 2021-09-19 19:01
I tried to repro this with some slight changes (`netcoreapp2.1` instead of `netcoreapp2.0`, ASP.NET Core package versions `2.1.1` instead of `2.0.0`), with `xunit.analyzers` version `0.12.0-pre.11` (available on [MyGet](https://myget.org/gallery/xunit)). I'm unable to reproduce this issue, so either my repro is insufficient or the issue has been fixed in the meantime.

Can you still reproduce the issue? If so, can you provide a full repro project and repro steps?

**Comment by bradwilson** [comment] 2023-06-11 00:42
Closing for age. Please open a new issue with a full repro project. Thanks!

**Closed by bradwilson** 2023-06-11 00:42 UTC
Labels: type: Bug, help wanted, status: Waiting for Repro/Response, area: Analyzers

**Comment by TimLovellSmith** [comment] 2023-06-12 18:44
SGTM. Maybe instead of investigating this issue, you should just try to solve it all by being clean w.r.t nullable analysis.

**Comment by bradwilson** [comment] 2023-06-13 07:27
You mean like this? https://github.com/xunit/xunit.analyzers/blob/bf692baa181cce2403aba9707d6468d3eb451b73/src/Directory.Build.props#L21

**Comment by TimLovellSmith** [comment] 2023-06-13 17:04
@bradwilson Yup. :) I.e. I think this issue's well past the use-by-date, unless there are some `#nullable disable` or unsolved warnings hanging around.
