### ISSUE TITLE
Runner inconsistencies

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#487] opened 2015-07-27 22:50 UTC
_From @herecydev on May 30, 2015 12:55_

After updating to the latest beta `2.1.0-beta2-build79` I'm getting inconsistent behavior between the visual studio test explorer and the command line.

Using `dnx . test -list` shows the correct names for the tests (`TestMethodDisplay.Method`):

![image](https://cloud.githubusercontent.com/assets/11328618/7897372/8f9da726-06d1-11e5-817d-d84d0130e928.png)

The visual studio test explorer however, shows:

![image](https://cloud.githubusercontent.com/assets/11328618/7897376/b0478744-06d1-11e5-9cdf-f6cd9c951d33.png)

I also use traits to group tests. This seems now to be broken/ignored. The `ITraitDiscoverer` implementation is executing as before and returning the correct values but it is not honored through the test explorer. Running the command line with specific traits returns 0 results.

Any idea what's causing this?

_Copied from original issue: xunit/dnx.xunit#37_

**Comment by bradwilson** [comment] 2015-07-27 22:50
_From @sblackler on June 8, 2015 13:1_

Any news on this? :)

**Comment by bradwilson** [comment] 2015-07-27 22:50
Sorry, I haven't had a chance to look at it yet.

**Comment by bradwilson** [comment] 2015-07-27 22:50
_From @herecydev on June 19, 2015 18:6_

Regarding traits, I have to admit was down to confusion. I can completely see where you were going with `-trait "name=value" now.

Before I was trying `-trait "name=Category"` or `-trait "name=Unit Tests"`. Instead (for anyone wondering) the correct value for me was `-trait "Category=Unit Tests" where 'Category' was the name of the trait and 'Unit Tests' was the value. Seems obvious in hindsight but maybe an example could help here?

**Comment by bradwilson** [comment] 2015-07-27 22:50
_From @herecydev on June 22, 2015 7:32_

Just to note, display of traits/method displays are still broken within the test explorer (though their functionality exists).

**Comment by bradwilson** [comment] 2015-07-27 22:50
Trait display is broken how? They seem to be working for me (for grouping, at least):

![Traits in VS](https://pbs.twimg.com/media/CHA2sC4VAAAjine.png:large)

**Comment by bradwilson** [comment] 2015-07-27 22:50
_From @herecydev on June 22, 2015 17:21_

Broken as in I'm not seeing any of that..

![image](https://cloud.githubusercontent.com/assets/11328618/8287977/388b7cb4-190b-11e5-8b73-339832619895.png)

Trait display and method display are not honored through the test explorer, though they are correctly run. I have the command set up to only run integration tests in that screenshot and they are the only ones that are run. So correct behavior there.

**Comment by bradwilson** [comment] 2015-07-27 22:50
Oh, right, this is DNX. My bad. My screenshot was from a PCL test library.

My guess is that the bridge they have built in Visual Studio for project.json testing does not support traits, or that we're missing some code to make it happen. /cc @davidfowl

**Comment by rynowak** [comment] 2015-08-05 16:06
This is our bug, we haven't plumbed this data through yet. It was tracked internally, added aspnet/Testing#136 for visibility.

**Comment by herecydev** [comment] 2015-08-05 18:18
@rynowak Thanks for picking this up. Just one suggestion, shouldn't all bugs be made public/visible? It takes a substantial amount of time to research the cause, formulate an assessment and write a formal issue in the hope that it will be fixed.

**Comment by rynowak** [comment] 2015-08-05 18:29
@herecydev - in general that's our policy and practice with ASP.NET. 

One exception is that we're almost always using a newer version of VS than is available publicly. Bugs that we open against the internal tooling hopefully are fixed before that is released to the world. In this case it slipped through the cracks and wasn't moved to the (public) Testing repo.

**Closed** 2017-04-22 22:59 UTC
Labels: [a] dnx.xunit, [s] External, [t] Bug
