### ISSUE TITLE
xunit.extensions.uitest not working on a UWP Test project

### ISSUE THREAD

**Issue by nelsonghezzi** [xunit/xunit#950] opened 2016-08-27 22:41 UTC
Trying to use the [uitest.xunit](https://github.com/xunit/uitest.xunit) extension, I've found that it's not working. I know that it's labeled as a "work-in-progress", and don't know if there are plans to maintain it, (hope so, as it's the xUnit counterpart of MSTest UITestMethod), but I'm filling this issue just in case.

Having the following dependencies in project.json:

```
"dependencies": {
  "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
  "xunit": "2.1.0",
  "xunit.extensions.uitest": "1.0.0-rc1",
  "xunit.runner.visualstudio": "2.1.0"
}
```

I've found two scenarios in which the extension fails:
## First Scenario

Having a test marked with the `UIFact` attribute at the top of the test class.

```
public class UnitTest
{
    [UIFact]
    public void UITestMethod()
    {
        BitmapImage image = new BitmapImage();
    }

    [Fact]
    public void TestMethod()
    {

    }
}
```

**Result:** no tests are discovered.
## Second Scenario

Having the test marked with the `UIFact` attribute come after other `Fact` tests.

```
public class UnitTest
{
    [Fact]
    public void TestMethod()
    {

    }

    [UIFact]
    public void UITestMethod()
    {
        BitmapImage image = new BitmapImage();
    }
}
```

**Result:** only the `Fact` test is discovered, which passes OK, but the following message is written in the output window (note that "xUnit.UITestExtension.Sample" is the name of the assembly):

```
Test adapter sent back a result for an unknown test case. Ignoring result for 'xUnit.UITestExtension.Sample.UnitTest.UITestMethod'.
```

**Additional environment information**
Microsoft Visual Studio Enterprise 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Regards.

**Comment by onovotny** [comment] 2016-08-28 23:38
@nelsonghezzi have you tried using the device runner as described at http://xunit.github.io/docs/getting-started-devices-uwp.html?

**Comment by nelsonghezzi** [comment] 2016-08-29 17:45
Hi Oren,

I can confirm that using the [xunit.runner.devices](https://github.com/xunit/devices.xunit), the `UIFact` test is discovered and successfully executed:

![xunit devicerunner sample](https://cloud.githubusercontent.com/assets/6424021/18060866/ac7cc27c-6df6-11e6-86c4-1cae78653d1f.png)

Any chance to get this to work using the xUnit Visual Studio runner?

Thanks.

**Comment by onovotny** [comment] 2016-08-29 17:56
I'm not sure the Visual Studio runner can ever be made to fully work as it's broken by design. The current VS Runner always does discovery in the Desktop CLR, even for UWP, WinRT, WP8 projects. As such, if you use types in your test that cannot be loaded in the desktop CLR, it'll fail to discover.

The device runner does discovery in the target platform, which is why it works there. Unfortunately, this is a Microsoft limitation in their VS runner architecture and there's not much we can do there.

**Comment by nelsonghezzi** [comment] 2016-08-29 20:31
I'm a bit confused here.

If I understand you correctly, the problem is not with the `UIFact` attribute itself, but with the reference to the `BitmapImage` class (declared on the `Windows.UI.Xaml.Media.Imaging` namespace and not present in the Desktop CLR) ?

Even if a leave empty the UITestMethod, it fails to discover it.

What am I getting wrong?

**Comment by bradwilson** [comment] 2016-08-29 21:00
Just to level-set, are you able to clone our [integration project](https://github.com/xunit/xunit.integration) and run the tests inside Visual Studio?

**Comment by bradwilson** [comment] 2016-08-29 21:09
FWIW, my guess is that `[UIFact]` and friends will simply never work inside Visual Studio, because *it* is [the code that is failing to work correctly on the desktop CLR](https://github.com/xunit/uitest.xunit/blob/master/src/xunit.extensions.uitest.uwp/UITestCase.RunTest.cs).

@onovotny: It seems like a potential "fix" would be to use reflection to discover the APIs you want to call at runtime, so that they don't just fail to resolve during discovery. It might not be worth it, given that the limitation for non-desktop code probably still extends to the unit test...

**Comment by bradwilson** [comment] 2017-04-22 23:11
Closing as External, since we cannot fix this issue.

**Closed by bradwilson** 2017-04-22 23:11 UTC
Labels: [a] extensions.xunit, [r] External
