### ISSUE TITLE
Dotnet Pack requires IsPackable setting in the csproj for class libraries with a reference to Xunit

### ISSUE THREAD

**Issue by djowatts** [xunit/xunit#1520] opened 2017-10-17 09:12 UTC
Hello, 

When trying to get a class library built in .Net core with xUnit referenced, the `dotnet pack` command does not produce a nuget package unless you add the `IsPackable` setting into your csproj file. 

[Here is an issue within the dotnet CLI project](https://github.com/dotnet/cli/issues/7539) that references the issue on web projects. 

To replicate, create a dotnet core class library and reference xUnit, then attempt to run dotnet pack from the command line.

**Comment by bradwilson** [comment] 2017-10-18 23:31
This behavior is by design (of the .NET SDK team).

**Comment by djowatts** [comment] 2017-10-18 23:43
I believe this is only by design for ASP.Net core apps. (Will update with link in the morning) Any class library or console app I build happily generate a nuget package when the dotnet pack command is ran. Only adding the xUnit reference stops this package from being created. 

Like I said, I'll add the link to the docs/MS blog post I made this claim from in the morning. (UK time). It's not game breaking or anything, but I am under the impression that only ASP projects require this setting.

**Comment by bradwilson** [comment] 2017-10-19 01:02
As I understand it, this advice for non-packability comes from the .NET SDK team to the VSTest team, to make test projects not packable by default. This is called out in our [release notes for 2.3](https://xunit.github.io/releases/2.3):

> As a reminder: If you're extending xUnit.net and want to publish your extension as a NuGet package, you should import `xunit.extensibility.core` and/or `xunit.extensibility.execution`, not `xunit` or `xunit.core`. If you do this wrong, you might have problems generating your NuGet package via `dotnet pack`.

**Comment by djowatts** [comment] 2017-10-19 09:08
Yeah, I must have missed that when I was solving this problem for us yesterday. Just read the discussion in this Git Issue https://github.com/dotnet/templating/issues/376 along with the linked release notes.

**Comment by bradwilson** [comment] 2017-10-19 18:27
Closing as By Design.

**Closed by bradwilson** 2017-10-19 18:27 UTC
Labels: [r] By Design

**Comment by micdah** [comment] 2017-12-05 11:55
After reaching near insanity-level confusion over why one of our infrastructure packages suddenly stopped outputting any nupkg files, I finally found this issue and after adding `<IsPackable>true</IsPackable>` we are back on track.

It would be really excellent if the output of `dotnet pack` had some information output to inform that this decision was made, which would have made it much more obvious why no output was generated. Of course this is not a bug, per se, at it is intended behavior. 

But still, because the behavior can be unexpected (_I for one did not expect any `PackageReference` could affect output of `dotnet pack`_), it would be great with informative output to tell as much.

**Comment by bradwilson** [comment] 2017-12-05 22:51
> It would be really excellent if the output of dotnet pack had some information output to inform that this decision was made

This is the wrong repo to make that suggestion in. :)

**Comment by vijayrkn** [comment] 2020-04-29 16:12
> > It would be really excellent if the output of `dotnet pack` had some information output to inform that this decision was made
> 
> This is the wrong repo to make that suggestion in. :)

There is a new property that NuGet supports to warn users if the project is non-packable.
`WarnOnPackingNonPackableProject ` 

WebSdk has started adding this. 
https://github.com/dotnet/websdk/blob/4a4ae15f4c78cb3dfeffdf05ca12094b7e8a72a7/src/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.props#L22

**Comment by mkorsukov** [comment] 2024-03-28 01:22
You can run `dotnet pack /p:IsPackable=true` in case you don't have `IsPackable` set in csproj file.
