### ISSUE TITLE
Assert methods which take lambdas to customer code and await should .ConfigureAwait(false)

### ISSUE THREAD

**Issue by matthchr** [xunit/xunit#507] opened 2015-07-27 23:39 UTC
I am authoring some tests to ensure that a library does not deadlock in certain UI contexts.  You can read more about what causes the particular deadlock here if you're interested: [msdn blog](http://blogs.msdn.com/b/pfxteam/archive/2011/01/13/10115163.aspx)

The relevant snippet is:

> If the UI thread is unable to get back to the message loop to process messages, it will be unable to pick up the posted delegates that resulted from the asynchronous operations in LoadStringAsync completing, which means the remainder of LoadStringAsync will not run, which means the Task<string> returned from LoadStringAsync will not complete"

I edit the SynchronizationContext of my tests in order to reproduce this issue, and I have some code which checks for timeouts after a particular period of time so that the tests will fail if they end up deadlocking.  The problem I am running into is that the XUnit framework itself deadlocks in some cases as well, specifically with methods which take Func/Action's from my code and execute them on my behalf. 

Here's a simplified example (I cut out the timeout detecting code) - the Foo method does not deadlock.  FooDeadlocks does deadlock.  You can see the difference is one uses an Assert method which takes a lambda and the other doesn't.

``` c#
[Fact]
public async Task Foo()
{
    DispatcherSynchronizationContext synchronizationContext = new DispatcherSynchronizationContext();
    SynchronizationContext.SetSynchronizationContext(synchronizationContext);

    try
    {
        await this.ThrowOperationCanceledExceptionAsync().ConfigureAwait(false);
    }
    catch (OperationCanceledException)
    {

    }
}

[Fact]
public async Task FooDeadlocks()
{
    DispatcherSynchronizationContext synchronizationContext = new DispatcherSynchronizationContext();
    SynchronizationContext.SetSynchronizationContext(synchronizationContext);

    await Assert.ThrowsAnyAsync<OperationCanceledException>(async () =>
                                                                  {
                                                                      await this.ThrowOperationCanceledExceptionAsync().ConfigureAwait(false);
                                                                  }).ConfigureAwait(false);
}

public async Task ThrowOperationCanceledExceptionAsync()
{
    Task task = Task.Factory.StartNew(() =>
    {
        throw new OperationCanceledException();
    });

    await task.ConfigureAwait(false);
}
```

I believe the problem stems from Record.cs in XUnit:

``` C#
protected static async Task<Exception> RecordExceptionAsync(Func<Task> testCode)
{
    Assert.GuardArgumentNotNull("testCode", testCode);

    try
    {
        await testCode();
        return null;
    }
    catch (Exception ex)
    {
        return ex;
    }
}
```

_I think_ one possible fix is to update `await testCode();` to be `await testCode().ConfigureAwait(false)` -- otherwise anybody running in a UI context (or simulating one like I am) will hit this issue with the Assert.\* methods which take Func<>'s.  Caveat that I haven't actually tried to make that change to see if it resolves the issue and there might be more to it than that. There is some documentation on MSDN which seems to [suggest that using ConfigureAwait(false) is a best practice](https://msdn.microsoft.com/en-us/magazine/JJ991977.aspx?f=255&MSPPError=-2147217396), although since XUnit seems to set its own Sync Context (or maybe that's just the VS runner) it might be a bit moot for calls which aren't calling customer code.

**Comment by bradwilson** [comment] 2015-07-27 23:57
I disagree with the premise.

We have two synchronization contexts that we use (one to support `async void` and one to support limiting the number of tests in flight), and we need to ensure that the user comes back onto the correct synchronization context.

**Comment by bradwilson** [comment] 2015-07-28 00:00
By the way, if you disagree, you can import the `xunit.assertions.source` project instead of `xunit.assertions` and make the changes yourself.

**Comment by matthchr** [comment] 2015-07-28 00:09
Is there an alternative for supporting tests running with a different sync context?  There seems to be an assumption made by XUnit that the sync context at the point the lambda is called is the same as the sync context set in the XUnit framework itself - but given the fact that I've edited the sync context in the test I've already broken that assumption (regardless of if ConfigureAwait is used by XUnit internally on the lambda or not, the sync context for the lamba call is captured from the test code not from the XUnit framework).

Are you saying that editing the sync context inside the test is unsupported?

**Comment by bradwilson** [comment] 2015-07-28 00:15
> Are you saying that editing the sync context inside the test is unsupported?

The compiler is the one caching the reference to the sync context on method entry, not us (and this is expected behavior). Using `.ConfigureAwait()` isn't going to help you here, either, because it's not going to put you back on your own custom sync context, either; it's going to land you onto the default ThreadPool-based context.

**Comment by bradwilson** [comment] 2015-07-28 00:21
BTW, the advice to use `.ConfigureAwait()` is for library authors, and it's intended to help prevent potential deadlocks in theoretically single-threaded sync contexts (like WinForms, WPF, etc.). That advice is actually poor advice for server apps, because forcing a thread transition is expensive, and on servers, there's no such thing as a "background thread" (unlike UI apps).

Furthermore, the advice is actually wrong for frameworks themselves (f.e., you would rarely if ever see code like that inside of WPF itself).

**Comment by matthchr** [comment] 2015-07-28 00:23
The reason I asked: 
>Are you saying that editing the sync context inside the test is unsupported?

Was because:
>We have two synchronization contexts that we use (one to support async void and one to support limiting the number of tests in flight), and we need to ensure that the user comes back onto the correct synchronization context.

If I set a sync context in the test, then the user won't come back on the "correct" sync context right?  Is that going to break some feature of XUnit (that I'm probably not using right now) - such as tests-in-flight limiting?

**Comment by bradwilson** [comment] 2015-07-28 00:35
> If I set a sync context in the test, then the user won't come back on the "correct" sync context right?

Setting the sync context in a method only affects _**downstream methods that you call**_. It does not affect your own method, because the appropriate sync context was cached when the finite state machine was initialized.

> Is that going to break some feature of XUnit (that I'm probably not using right now) - such as tests-in-flight limiting?

Yes and no. It's impossible for you to "undo" the sync context of _**your caller**_ (meaning, xUnit.net), so you can't break me by changing your sync context inside your test. You will, however, probably break the "maximum number of tests in flight" feature since anything which resumed on a different sync context from our "max concurrency" sync context wouldn't, by definitely, be limited.

**Comment by matthchr** [comment] 2015-07-28 00:40
>That advice is actually poor advice for server apps, because forcing a thread transition is expensive, and on servers, there's no such thing as a "background thread" (unlike UI apps).

I do not believe `ConfigureAwait(false)` *forces* a thread transition, rather it *allows* one as opposed to *forcing* a call back to the original context.  There are cases with `ConfigureAwait(false)` where the same thread would be used for the continuation, depending on the inner workings of TPL.

In any case, rather than taking a dependency on the raw source (and thus have to deal with porting my change forward if I upgrade to new xUnit versions) is there some way to override the implementation of the Record class?  I see a suppressed compiler warning message there suggesting that is a point of extensibility.  I suppose alternately I could supply my own implementation of the asserts methods which are causing me issues.

**Comment by bradwilson** [comment] 2017-04-30 05:14
We won't be fixing this. Importing the source (via NuGet, git submodule, or copy/paste) allows the user to make whatever changes they want. We have our desired default behavior already.

**Closed by bradwilson** 2017-04-30 05:14 UTC
Labels: [a] xunit, [t] Feature
