### ISSUE TITLE
Random ClassData not running

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#2117] opened 2020-07-11 18:48 UTC
Seems along similar lines as with the `MemberDataAttribute`, random data generated with a `ClassDataAttribute` is not running. They discover, once, then I presume there is a disconnect between that case, and any next randomly generated class data. That and/or the underlying runner does not respect the data sets that were previously generated.

As I stated in prior issues, if you raise this flag with the VS team, I'll stand behind you, but as a subscriber to Xunit, that falls on your shoulders, not mine. I'll support your issue, up vote, I can report my test cases, that sort of thing.

Thank you.

**Comment by mwpowellhtx** [comment] 2020-07-11 18:59
@AArnott Quick report, I've got a workaround for the time being. It would be better if the underlying environment "just worked", but such as it is, I can workaround it:

```C#
public static IEnumerable<object[]> EnumStatementWithEmptyStatementCases { get; } = new EmptyEnumStatementTestCases().ToArray();
```

My theoretical data test cases are `IEnumerable<object[]>` as a type, so they generate for class data. But I can easily shim it in as a member data just the same.

In other words:

```C#
typeof(EnumStatementWithEmptyStatementTestCases).AssertIsAssignableTo<IEnumerable<object[]>>();
```

Efforts to capture the test data in any private static field are pretty much futile at this point I think. This sort of approach did used to "just work", but not today, it seems.

**Comment by AArnott** [comment] 2020-07-12 13:57
@mwpowellhtx I'm probably lacking context here. Why did you mention me?
None of this sounds like anything I own or that I recall discussing with you previously.

**Comment by mwpowellhtx** [comment] 2020-07-12 14:10
Yes, we've discussed `MemberDataAttribute` and random generated data before.

**Comment by bradwilson** [comment] 2020-07-16 01:59
Unstable data cannot be pre-discovered. See: https://xunit.net/faq/theory-data-stability-in-vs

**Comment by mwpowellhtx** [comment] 2020-07-16 02:05
Ah, apologies for the confusion. Thanks. So... Same root cause issue I'm assuming.

**Comment by bradwilson** [comment] 2020-07-27 02:39
Closing as "by design".

**Closed by bradwilson** 2020-07-27 02:39 UTC
Labels: status: By Design / Won't Fix
