### ISSUE TITLE
Dispose method on test class not being called if test is cancelled

### ISSUE THREAD

**Issue by lizalc** [xunit/xunit#2008] opened 2019-09-12 18:17 UTC
I'm using .NET 4.7.2 and the xUnit console runner (v2.4.1).

I'm using xUnit to run some integration tests on an external device. My test class constructor performs some device setup, then I use the Dispose method to do some cleanup on the device. Overall it has been working well but I've noticed that sometimes if I cancel a test while it is running - after the constructor has been called and device setup complete - the Dispose method isn't called so the device cleanup code never runs. Cancelling meaning I press `Ctrl+C` once on the console while the test is running.

Here are some example tests I wrote which I have used to reproduce the issue: https://github.com/shvr/xUnitDisposeNotCalled

These tests simply wait for 10 seconds (some using Thread.Sleep and some using Task.Delay). One of the test classes, `ThrowingDispose`, simply throws an exception when called, while the other test class, `SleepyDispose` sleeps for 5 seconds. When running tests in the `ThrowingDispose` class, if I cancel a test the exception is never thrown, and for `SleepyDispose` the 5 second delay never seems to occur.

I've also passed the `-debug` option to the console runner and set a breakpoint in the Dispose methods. If I cancel the tests the breakpoint is never hit.

Here's some console output from a test in the `ThrowingDispose` that I cancelled while it was running:
```
PS C:\Users\lando\source\repos\DisposeNotCalled\DisposeNotCalled\bin\Debug\net472> & 'C:\Users\lando\.nuget\packages\xunit.runner.console\2.4.1\tools\net472\xunit.console.exe' .\DisposeNotCalled.dll -diagnostics -internaldiagnostics -verbose -method DisposeNotCalled.ThrowingDispose.DisposeNotCalled
xUnit.net Console Runner v2.4.1 (64-bit Desktop .NET 4.7.2, runtime: 4.0.30319.42000)
   [AssemblyHelper_Desktop.LoadAssembly] Resolution for 'Microsoft.VisualStudio.TestPlatform.ObjectModel' failed, passed down to next resolver
   DisposeNotCalled: [AssemblyHelper_Desktop.LoadAssembly] Resolution for 'Microsoft.VisualStudio.TestPlatform.ObjectModel' failed, passed down to next resolver
  Discovering: DisposeNotCalled (app domain = on [shadow copy], method display = ClassAndMethod, method display options = None)
  Discovered:  DisposeNotCalled (found 1 of 8 test case)
  Starting:    DisposeNotCalled (parallel test collections = on, max threads = 4)
   [AssemblyHelper_Desktop.LoadAssembly] Resolution for 'xunit.execution.desktop' failed, passed down to next resolver
   DisposeNotCalled: [AssemblyHelper_Desktop.LoadAssembly] Resolved 'xunit.execution.desktop' to 'C:\Users\lando\source\repos\DisposeNotCalled\DisposeNotCalled\bin\Debug\net472\xunit.execution.desktop.dll'
    DisposeNotCalled.ThrowingDispose.DisposeNotCalled [STARTING]
Canceling... (Press Ctrl+C again to terminate)
    DisposeNotCalled.ThrowingDispose.DisposeNotCalled [FINISHED] Time: 10.008432s
  Finished:    DisposeNotCalled
=== TEST EXECUTION SUMMARY ===
   DisposeNotCalled  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 10.112s
```

**Comment by shvr** [comment] 2019-09-30 00:17
I've dug through the xUnit source and I think I've found the source of this problem.

The issue lies in the [`DisposeTestClass` method](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs#L63) in the `ReflectionAbstractionExtentions` class:
```c#
public static void DisposeTestClass(this ITest test,
                                    object testClass,
                                    IMessageBus messageBus,
                                    ExecutionTimer timer,
                                    CancellationTokenSource cancellationTokenSource)
{
    var disposable = testClass as IDisposable;
    if (disposable == null)
        return;

    // ISSUE HERE - If QueueMessage returns false then the disposal won't occur.
    if (!messageBus.QueueMessage(new TestClassDisposeStarting(test)))
        cancellationTokenSource.Cancel();
    else
    {
        try
        {
            timer.Aggregate(disposable.Dispose);
        }
        finally
        {
            if (!messageBus.QueueMessage(new TestClassDisposeFinished(test)))
                cancellationTokenSource.Cancel();
        }
    }
}
```

Essentially, if the user requests test cancellation (ex via `Ctrl+C` in the console runner) the `QueueMessage` call could return false causing the test class to not be properly disposed of.

It seems to me that the `else` should be removed that way the test class is always disposed of even if `QueueMessage` returns false when sending the `TestClassDisposeStarting` message.

I can submit a merge request with this change later this week.

**Comment by bradwilson** [comment] 2019-09-30 00:20
Nice debugging work! 👍🏼

**Comment by GeeWee** [comment] 2020-02-19 16:49
Just wanted to add a +1 because I've also stumbled upon this issue while testing some Kafka work. I'd love for this to be merged in. Currently my workaround is to register the CancelKeypress manually
```csharp
            Console.CancelKeyPress += (_, e) => {
                this.Dispose();
            };
```
in the constructor, but I assume that might only work for console-based test runners.

**Comment by Piedone** [comment] 2020-07-10 22:37
Do I understand correctly, that due to this issue and https://github.com/xunit/xunit/issues/345 there is currently no way to gracefully cancel a test? The same problem came up for us too, canceled UI tests not cleaning up after themselves akin to the test process being killed.

**Closed** 2020-09-02 07:04 UTC

**Comment by Piedone** [comment] 2020-09-02 12:34
@bradwilson do I understand correctly that this will make `Dispose()` on the test class called when the test run in canceled? Will test methods be awaited though or killed mid-execution (which happens currently with `dotnet test` it seem)? For that I guess we'd still need `CancellationToken` support on test methods, as in #345.

And will be this shipped as part of v3 or also v2?

Thank you!

**Comment by bradwilson** [comment] 2020-09-03 01:45
There is no way today to handle it in the tests. The wait that's being done in that case ensures no new tests will be started.

**Comment by Piedone** [comment] 2020-09-03 10:12
Is see, thanks.

**Comment by Piedone** [comment] 2020-09-04 16:14
@GeeWee does the console cancel key press event work in `dotnest test`? Or which runner did you try?

**Comment by MatheusXavier** [comment] 2020-12-29 10:16
Hello guys, I'm facing this issue. I create a new resource on Azure to run my tests and I delete that resource on Dispose method, but when I cancel some test then the Dispose method is not called and this resource is not being deleted. Any sugestions?

**Comment by Piedone** [comment] 2020-12-29 13:54
Only the above-detailed console keypress one can be a potential workaround (didn't work for me), otherwise, everybody has the same problem here.

**Comment by GeeWee** [comment] 2020-12-30 08:14
@Piedone sorry for missing the mention. Yes the consoel cancel key press works in `dotnet test` in an oh-my-zsh shell for me.

**Comment by Piedone** [comment] 2020-12-30 13:07
Thanks @GeeWee. I only tried on Windows with `dotnet test` but the event was never fired. Might be a platform issue then.

**Comment by jzabroski** [comment] 2025-06-06 13:54
> There is no way today to handle it in the tests. The wait that's being done in that case ensures no new tests will be started.

I think we can say something a bit stronger, actually: You don't _want_ to handle this in tests, as it means the behavior of your test is dependent on a user action and could cause a silent passing test. Probably should go into an Architecture Decision Log on test behavior.

**Comment by bradwilson** [comment] 2025-06-06 15:54
@jzabroski As it turns out, between the time I wrote that comment and now, we've added support for cancellation tokens in unit tests, available via `TestContext.Current.CancellationToken`, and a test can request self-cancellation via `TestContext.Current.CancelCurrentTest`.

This is mostly so that tests can stop running when they've been cancelled, and not about any attempt to clean up (though some may choose to try to use it this way, even if that's not what was intended).
