### ISSUE TITLE
dotnet-xunit doesn't respect custom BaseIntermediateOutputPath property

### ISSUE THREAD

**Issue by bording** [xunit/xunit#1234] opened 2017-04-29 02:48 UTC
dotnet-xunit appears to expect the obj folder to be in the default location even when it's moved somewhere else via the `BaseIntermediateOutputPath` property:

When executing `dotnet xunit` I see the following exception:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Code\libgit2sharp\LibGit2Sharp.Tests\obj\LibGit2Sharp.Tests.csproj.dotnet-xunit.props'.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents)
   at Program.Execute(String[] args)
```

The project has a `Directory.Build.props` file at C:\Code\libgit2sharp that has the following line:
```xml
<BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
```
If I remove this line, everything works correctly. While I understand this a non-standard configuration, it seems like dotnet-xunit should be able to respect this and not assume it knows where the obj folder is.

**Comment by bradwilson** [comment] 2017-04-29 03:47
Unfortunately, we don't have a way to read this property. It's a classic check-and-egg problem: in order to read values from the .csproj file, I need to inject things into it via the `obj` folder, so I can't use that technique to figure out where the `obj` folder is.

https://github.com/xunit/xunit/blob/6f83e40d5056ab68ea0ef1c210e177e97baf554a/src/dotnet-xunit/Program.cs#L86-L127

**Comment by bording** [comment] 2017-04-29 04:14
I was looking at the code and realized that you wouldn't have a good way to discover the value of that property. 😢 

Why do the files have be be generated like that? Could you instead include them in the build folder of the `dotnet-xunit` package? Or do packages brought in via `DotNetCliToolReference` not get to do that?

**Comment by bradwilson** [comment] 2017-04-29 04:40
That's correct: `DotNetCliToolReference` packages don't get to bring in build files the way `PackageReference` packages do. There is also no way to set up a dependency between these things. It would require two separate packages; if one was missing, then nothing would work.

**Comment by bording** [comment] 2017-04-29 04:45
Would it be completely crazy to bundle those into the actual xUnit package? You'd be able to guarantee they weren't missing at least that way.

**Comment by bradwilson** [comment] 2017-04-29 04:52
Maybe into `xunit.core`, which theoretically is the package that's required by people writing unit tests.

The problem is that runners are intended to be version-independent. If we put these files into `xunit.core`, then it starts tying things a little too tightly. For starters, it means we'd require 2.3 as a minimum version of the core libraries (instead of today's requirement of 2.0+ for desktop, or 2.2+ for .NET Core). Additionally, if we ever needed to make changes to those prop files, we'd create an even tighter bond between runner and test author, which we have worked very very hard to never have.

It's possible to do a fallback strategy: test to see if the props are already there (in whatever form is necessary), and then fall back to the existing technique when they're not.

On the plus side, we would be able to support a `-nobuild` option when the props file is there, which we can't do today because of the other properties we need injected.

I'll give it some more thought.

**Comment by bradwilson** [comment] 2017-04-30 02:29
Fixed by 2dad9bbc589758b393b7be94131ddb12eb830292

**Closed by bradwilson** 2017-04-30 02:29 UTC
Labels: [a] dotnet-xunit, [t] Bug

**Comment by bradwilson** [comment] 2017-04-30 02:55
FYI: I used a conditional `<Import>` to address the version compatibility issues, and let the runner bring its own imports. So we will get forward compatibility, starting with 2.3 beta 2 (since the Import comes from xunit.core).

https://github.com/xunit/xunit/blob/8b113822cbb48f153f5bac267f6da1235403c141/src/xunit.core/build/xunit.core.props#L3-L4

**Comment by bradwilson** [comment] 2017-04-30 02:56
This also gave us `-nobuild` (#1235). 😸

**Comment by bording** [comment] 2017-04-30 04:17
Looks like a great solution to the problem, thanks for taking the time to figure out a way to make it work!
