### ISSUE TITLE
Is there a way to allow multiple traits with the same name?

### ISSUE THREAD

**Issue by DrLeh** [xunit/xunit#2542] opened 2022-07-01 13:46 UTC
We're using xrayapp http://getxray.app to record our unit tests into Jira so that we can link them to requirements, bugs, etc.

Sometimes we have cases where we have a single unit test covering multiple bugs (maybe the bug was a duplicate, maybe the bug points out something in the original story, so i want to link my test to both). Therefore, I tried to decorate my tests like so:

```c#

        [Trait("Requirement", "ENCORE-16116")]
        [Trait("Requirement", "ENCORE-17436")]
        [Fact]
        public async Task NoAttribute_NoQuantity_Entered_Test()
```

However, when I generate the report, i only see the first trait recorded:

```xml
      <test name="...NoAttribute_NoQuantity_Entered_Test" type="..." method="NoAttribute_NoQuantity_Entered_Test" time="0.0014662" result="Pass">
        <traits>
          <trait name="Requirement" value="ENCORE-16116" />
        </traits>
      </test>
```

Is there any way to have the report contain multiple of these requirement traits? My only other option is to find if xrayapp supports some kind of delimiter in the value of the trait. according to their documentation it doesnt but i could try anyway.

**Comment by bradwilson** [comment] 2022-07-25 02:22
I'm not able to reproduce this:

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/16944/180680756-582f3bca-bcc4-40e9-9cd9-df34b8ed58a3.png">

**Comment by bradwilson** [comment] 2023-06-11 00:41
Closing for age. Please open a new issue with a full repro project. Thanks!

**Closed by bradwilson** 2023-06-11 00:41 UTC
Labels: status: Waiting for Repro/Response
