### ISSUE TITLE
System.NotImplementedException during xUnit test from Xam.Plugins.Settings

### ISSUE THREAD

**Issue by arichar1990** [xunit/xunit#1888] opened 2019-01-23 20:23 UTC
I am getting the following error when I try to run an xUnit test in a Xamarin project that uses Xam.Plugins.Settings to store data to the device:

`Message: System.NotImplementedException : This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.`

The exception occurs in the ISettings property initialization of the Settings class, which has the following form:

```
public static class Settings
    {
        private static ISettings AppSettings
        {
            get
            {
                return CrossSettings.Current;
            }
        }
}
```
When xUnit gets to the return CrossSettings line, the error occurs. Any chance anyone can tell me why this is happening? I have the nuget package installed in both the iOS and Android projects.

**Comment by onovotny** [comment] 2019-01-23 21:02
It sounds like one of the packages is not installed in the test project

**Comment by arichar1990** [comment] 2019-01-23 21:04
> It sounds like one of the packages is not installed in the test project. The test projects need all the same references as your application projects to ensure the right libraries are used.

No, that's not the issue. Xam.Plugins.Settings is installed in the test project as well.

**Comment by onovotny** [comment] 2019-01-23 21:07
How about any other dependencies? The xUnit for devices are applications. The error message is pretty clear that it's not using the right platform-specific package of a bait-switch package.

One recommendation is to switch off of `packages.config`. Those references are not transitive. VS 2017 has an "upgrade to packagereference" option if you right-click the packages.config file in the solution explorer. Once you do that, you don't need to have the application reference every package your libraries do, as they'll flow transitively.

**Comment by bradwilson** [comment] 2019-01-31 20:24
Marking this as by design, since there doesn't appear to be a bug (but rather the need to convert to the more modern form of package reference).

**Closed by bradwilson** 2019-01-31 20:24 UTC
Labels: status: By Design / Won't Fix
