### ISSUE TITLE
False positive xUnit1033 - special case "using alias=class"

### ISSUE THREAD

**Issue by WernerMairl** [xunit/xunit#2728] opened 2023-06-13 05:58 UTC
Hi,
- I'm aware of #2591 et. al. about xUnit1033
- I'm using net7.0 and xUnit 242

I see this (false positive) warning in a usecase where I can imagine it was not implemented yet
I'm using class aliasing via "using" statement

```
using MyApplicationFactory = MyGenericApplicationFactory<Startup,AppSettings>;

...
 public class MyTest : IClassFixture<MyApplicationFactory>
 {
        private readonly MyApplicationFactory Fixture;

        public MyTest (MyApplicationFactory fixture, ITestOutputHelper helper)
        {
            this.Fixture = fixture ;
        }
...
}
```
Hope that helps, and I'm not completely wrong ;-)

BR
Werner

**Comment by bradwilson** [comment] 2023-06-14 06:06
So I tried this:

```csharp
using Xunit;
using Xunit.Abstractions;
using Foo = Bar<int>;

public class Bar<T> { }

public class xUnit1033 : IClassFixture<Foo>
{
    public xUnit1033(Foo foo, ITestOutputHelper helper)
    { }

    [Fact]
    public void TestMethod() { }
}
```

And I cannot reproduce it.

Without constructor:

![image](https://github.com/xunit/xunit/assets/16944/872e81bd-9637-49db-8c54-510994038669)

With constructor:

![image](https://github.com/xunit/xunit/assets/16944/8097cdb8-68b4-4f4e-84bc-a1b07c223442)

This is using the latest public prerelease versions (`xunit` version `2.5.0-pre.22` and `xunit.analyzers` version `1.2.0-pre.9`). It's possible that this has been fixed since `2.4.2` (which brought in `xunit.analyzers` version `1.0.0`).

Can you try upgrade to the prerelease versions and seeing if the problem persists?

**Comment by bradwilson** [comment] 2023-06-14 06:08
(Note: I tried the constructor parameter type as both `Foo` and `Bar<int>` and neither would trigger the analyzer.)

**Comment by bradwilson** [comment] 2023-06-21 21:38
It's entirely possible that it's something we've fixed in the meantime. I'm about to ship another 2.5.0 prerelease build (hoping it's the last one, but you never know...) if you want to try it. It's already on MyGet: https://myget.org/feed/xunit/package/nuget/xunit.analyzers/1.2.0-pre.27

**Comment by WernerMairl** [comment] 2023-06-22 05:16
Hi
please feel free to close this issue - it was my fail.

Basically I was not aware that #2591 was fixed BUT NOT released yet (fighting with this known issue for long long time).

I can confirm that also my "aliased" scenario is working with 2.5.0-pre.37

BR
Werner

**Closed** 2023-06-22 06:46 UTC
Labels: status: Waiting for Repro/Response
