### ISSUE TITLE
Documentation how to run xunit 2.0 tests on Team city

### ISSUE THREAD

**Issue by Ciget** [xunit/xunit#387] opened 2015-04-08 15:00 UTC
Hi all,

Is there is any documentation or examples how to run xunit tests on team city ?
In version 1.9 i setup xunit, create build step .Net Runner, define path to xunit and dll that contain tests. 
But what should i do and how to run xunit 2.0 tests?

Thanks

**Comment by jjmartin** [comment] 2015-04-09 16:50
this would be nice.

**Comment by bradwilson** [comment] 2015-04-09 17:24
This documentation page (not yet ported, but linked from xunit.github.io) is still correct. The console and MSBuild runners automatically detect TeamCity and report appropriately.

http://xunit.codeplex.com/wikipage?title=HowToUseTeamCity

**Comment by Ciget** [comment] 2015-04-09 20:15
http://xunit.codeplex.com/wikipage?title=HowToUseTeamCity
Does not works properly. if i add package xunit console runner and try to execute xunit.console.exe - i got exception like this:
System.ArgumentException: Unknown test framework: Could not find xunit.dll or xunit.execution.desktop.dll.

**Comment by bradwilson** [comment] 2015-04-09 21:08
When you build the tests, either `xunit.dll` (v1.x) or `xunit.core.dll` and `xunit.execution.desktop.dll` (v2.x) should show up in the binary folder with the tests. Is this not the case with your builds? If so, are you doing anything non-standard with your builds (i.e., building to somewhere other than `bin\Release`, copying binaries to a separate folder after build, etc.0?

**Comment by jjmartin** [comment] 2015-04-10 14:29
i got the same problem initially that @Ciget was getting but i found the xunit.runner.console nuget package and installed that and get things going (with ncover coverage).

the issue i am hitting now is that the xunit.runner.console package doesn't actually register into a packages.config and so my build server doesn't download it.

i'm trying to figure out how i can install it via command line and I'll add that to my build script.

**Comment by jjmartin** [comment] 2015-04-10 14:41
for anyone else wanting to add this to their build (package restore won't find it).

.\src\.nuget\nuget.exe install xunit.runner.console -o ".\src\packages"

**Comment by jjmartin** [comment] 2015-04-10 16:13
on my build server (using msbuild to build rather than visual studio) i'm not getting that `xunit.execution.desktop.dll`  during the build.  I get it when i run locally - i'm not sure i'm understanding what the difference is...

**Comment by bradwilson** [comment] 2015-04-10 23:20
> on my build server (using msbuild to build rather than visual studio)

The copy of `xunit.execution.desktop.dll` is handed by code that's inserted into the `.csproj` file by NuGet during installation. We use MSBUILD on our build servers, too, and it works exactly as we expect it to: the file gets copied into the `bin` folder.

Check your `.csproj` file; the inserted code should look something like this:

https://github.com/xunit/visualstudio.xunit.integration/blob/7ddd39c429e6fa14de75044da42bd0be7f39577d/v2_net45/v2_net45.csproj#L4
https://github.com/xunit/visualstudio.xunit.integration/blob/7ddd39c429e6fa14de75044da42bd0be7f39577d/v2_net45/v2_net45.csproj#L74

> the issue i am hitting now is that the xunit.runner.console package doesn't actually register into a packages.config and so my build server doesn't download it.

`xunit.runner.console` is a solution-level package. When installing it via NuGet inside of Visual Studio, it should have created a file named `.NuGet\packages.config`. If you are running NuGet package restore from the command line, then `nuget restore mysolution.sln` should pick that up and do the package restore for you.

**Comment by Ciget** [comment] 2015-04-12 18:17
Hi everybody,

i found solution. First of all - when you add xunit.runner.console nuget package it will add it into .nuget folder on solution level (me personally was expect that it will be added to target project).

Also, you need to configure you teamcity step correctly (see image):
![xunit_issue](https://cloud.githubusercontent.com/assets/2539541/7106873/4fdf224c-e159-11e4-93e0-fd8dad720aa6.png)

**Comment by bradwilson** [comment] 2015-04-13 03:26
> when you add xunit.runner.console nuget package it will add it into .nuget folder on solution level

This is expected behavior when installing a solution-level package. NuGet supports two package types: solution-level and project-level. Since `xunit.runner.console` has no libraries, only tools, it is considered a solution-level package.

**Comment by herecydev** [comment] 2015-04-13 07:08
I created a meta runner for teamcity 8+ which should fulfill this requirement. This can be found [here](https://github.com/4Com/team-city-xunit-meta-runner).

**Comment by jjmartin** [comment] 2015-04-13 15:17
i have a couple of scripts that seem to be working now in team city... 

A powershell i run to build out both an old style 1.9 xunit project and but now it sets up a dotcover.xml with all the dll's ending in Tests.dll (or whatever filter you provide (we also supply *Tests.Integration.dll for running our integration tests separately)  

It looks for dlls like that that ALSO have a xunit.core.dll in the same directory.

```
Param([String]$filter = "*Tests.dll", $name="UnitTests.xunit")

.\src\.nuget\nuget.exe install xunit.runner.console -o ".\src\packages"

$testDlls =  gci -rec -filter $filter | where { $_.Directory -match "bin\\debug" -AND $(Test-Path -PathType Leaf $(Join-Path $_.Directory "xunit.core.dll"))} # this is the spiffyness

$xunitProject = New-Object XML
$dllstring = ''
$xunitProject.LoadXml("<?xml version=`"1.0`" ?><xunit><assemblies></assemblies></xunit>")
$testDlls | % { 
$assemblyElement  = $xunitProject.CreateElement("assembly")
$assemblyElement.SetAttribute("filename",$_.FullName)
$assemblyElement.SetAttribute("shadow-copy","true")
$xunitProject.SelectSingleNode("/xunit/assemblies").AppendChild($assemblyElement)
$dllstring= "$dllstring `"$($_.FullName)`""
}
$name = Join-path $PSScriptRoot $name
Write-Host "Saving $name"

$xunitProject.Save($name)

$xmlCoverPath = '.\xunit-dotcover.xml'
$xmlCoverPath = Join-path $PSScriptRoot $xmlCoverPath
$xmlCover = New-Object XML
$xmlCover.Load( $xmlCoverPath)

$targetArg = $xmlCover.SelectSingleNode("/CoverageParams/TargetArguments") 

$targetArg.InnerText  =  $dllstring.Trim() + " -parallel none"

$xmlCover.Save($xmlCoverPath)
```

I then have a build stop in our TeamCity that looks like this:
```
.\buildXunitProjectFiles.ps1
%teamcity.agent.home.dir%\tools\dotCover\dotcover.exe cover xunit-dotcover.xml /TargetWorkingDirectory="%teamcity.build.checkoutDir%" "/Output=%teamcity.build.checkoutDir%\coverage.xml" "/Filters=-:*.Tests;-:*].Tests;" "/LogFile=dotcover.log"
write-host "##teamcity[importData type='dotNetCoverage' tool='dotcover' path='coverage.xml' verbose='true']"
```

This lets me use the built in DotCover coverage in teamcity for unit test coverage.

**Comment by bradwilson** [comment] 2015-04-13 15:19
The XML mess shouldn't be necessary with the 2.0 console runner, since it allows you to pass multiple assemblies on the command line.

**Comment by jjmartin** [comment] 2015-04-13 15:29
well the xml is being passed into dotcover with the executable and its arguments that it will cover.  its kinda convenient, actually since I already had the code to grab all the DLLs (we can add more unit test projects without doing updates to the script or TeamCity).   in 1.9 the dotcover.xml would pass in xunit and the xunit project file as the argument.  Now it just re-writes the argument element with a list of all the dlls and the -parallel none option.   (Some of our tests are failing under default processing - working that part out).

**Comment by bradwilson** [comment] 2015-04-19 21:29
Closing this as there is already an open doc issue to port the CodePlex content.

**Closed by bradwilson** 2015-04-19 21:29 UTC

**Comment by EdsonECS** [comment] 2019-07-05 01:55
Tradução em Português:

Eu tenho alguns scripts que parecem estar funcionando agora na cidade do time ...

Um powershell eu corro para construir tanto um projeto estilo xunit de estilo antigo e agora ele configura um dotcover.xml com todos os dll's terminando em Tests.dll (ou qualquer outro filtro que você forneça (nós também fornecemos * Tests.Integration.dll para executando nossos testes de integração separadamente)

Ele procura dlls como esse que também tem um xunit.core.dll no mesmo diretório.
