### ISSUE TITLE
Could you add support for DNX46

### ISSUE THREAD

**Issue by nokinger** [xunit/xunit#600] opened 2015-09-23 06:30 UTC
Currently you are supporting DNX451 and DNXCore50, could you also add DNX46?

**Comment by bradwilson** [comment] 2015-09-23 12:36
DNX46 is already supported because DNX451 is compatible with it.

**Comment by nokinger** [comment] 2015-09-23 12:57
sure but i believe it must be added to the project.json

**Comment by bradwilson** [comment] 2015-09-23 14:19
No, it does not. Have you tried using DNX46 yet?

**Comment by nokinger** [comment] 2015-09-23 14:28
yes, i tried it yesterday evening and when i add the reference to xunit.runner.dnx it will fail to compile. Since i am changed my framework settings in my project.json from dnx46 to dnx451 it will compile and run my test.

**Comment by bradwilson** [comment] 2015-09-23 23:52
Please provide a repro project, because I'm not able to reproduce the issue.

I'm using:

- DNX `1.0.0-beta7`
- xunit `2.1.0-rc1-build3168`
- xunit.runner.dnx `2.1.0-beta5-build169`

**Comment by bradwilson** [comment] 2015-09-26 22:18
Please re-open this issue with a repro project. Closing for now.

**Closed by bradwilson** 2015-09-26 22:18 UTC
Labels: [a] dnx.xunit

**Comment by nokinger** [comment] 2015-09-28 20:27
hi bradwilson, i am test it today again and i rember it dosn't work with the xunit.runner.dnx  when i have setup dnx46 in my project json. Now it works as expected, what ever reason. Sorry for the trouble.

**Comment by andrecarlucci** [comment] 2016-02-25 17:27
Hi @bradwilson,
The tests are not appearing for me on the Test Explorer.
I'm using: dnx 1.0.0-rc1-16231

My project.json
```
"frameworks": {
    "dnx46": {
      "dependencies": {
        "xunit": "2.2.0-beta1-build3239",
        "xunit.runner.dnx": "2.1.0-rc1-build204"
      }
    }
  }
```
Any thoughts?

**Comment by bradwilson** [comment] 2016-02-25 18:09
@andrecarlucci Sorry, no.

We're not doing any more work on the DNX runner. Once ASP.NET Core RC 2 is out, a new (Core CLR) runner will replace this one; additionally, we have no plans for any releases between now and the RC 2 release.
