### ISSUE TITLE
ANSI Escape code is being escaped.

### ISSUE THREAD

**Issue by Socolin** [xunit/xunit#2535] opened 2022-06-11 14:18 UTC
Hello,

The Rider test runner is supporting colored output in tests, but when I try to write some colored output with xUnit, I'm getting the following result.

![image](https://user-images.githubusercontent.com/539620/173191534-0806b376-68b4-4370-b890-20682c7b80eb.png)

Expected result:

![image](https://user-images.githubusercontent.com/539620/173191657-e77f09f7-47b8-480a-a74b-4de9808e3562.png)

Also with `dotnet test` I'm getting the same problem (When an assert fail)

![image](https://user-images.githubusercontent.com/539620/173193438-170b54d7-c19d-40b2-af48-080e5ab361e4.png)

## Repro:

https://github.com/Socolin/ReproDotnetTestColorBug/tree/main/ANSIColorInTestsOutput.xUnit

```cs
using Socolin.ANSITerminalColor;
using Xunit.Abstractions;

namespace ANSIColorInTestsOutput.xUnit;

public class UnitTest1
{
	private readonly ITestOutputHelper output;
	
	public UnitTest1(ITestOutputHelper output)
	{
		this.output = output;
	}
	
	[Fact]
	public void Test1()
	{
		output.WriteLine(AnsiColor.Foreground(96, 120, 200).Colorize("Test colored output"));
	}
}
```

Output of dotnet test in gfithub action:
https://github.com/Socolin/ReproDotnetTestColorBug/runs/6843926652?check_suite_focus=true#step:6:76

## Note:

It seems to be working for in assert messages

```
[Fact]
public void Test1()
{
Assert.Equal("Fail", AnsiColor.Foreground(200, 120, 200).Colorize("Colored assert"));
}
```

![image](https://user-images.githubusercontent.com/539620/173193246-c237a571-ed98-49b4-9877-734384eab9d3.png)

## Note 2:

With MS Test it seems to works well for both assert and output 
https://github.com/Socolin/ReproDotnetTestColorBug/runs/6843926653?check_suite_focus=true#step:6:81

**Comment by bradwilson** [comment] 2022-07-25 02:43
We do not intend for the output in ITestOutputHelper to allow for ANSI coloring. We assume that the text written there should be made readable to the end user, including any control characters, so we escape things which are unprintable and make them printable.

This is working as designed.

**Comment by Socolin** [comment] 2022-07-25 03:11
> We do not intend for the output in ITestOutputHelper to allow for ANSI coloring. We assume that the text written there should be made readable to the end user, including any control characters, so we escape things which are unprintable and make them printable.
> 
> This is working as designed.

Any chance to add an option to allow ANSI Code ? 
I agree it's working as expected but  getting color in test output improve readblilty and help a lot to find what's going wrong with the test and make it easier to fix. And this is even more welcome for large test. When we need some noisy output to know what's going on (for example with specflow what is the steps that failed).

**Comment by bradwilson** [comment] 2022-07-25 23:21
If we look explicitly for `ESC[` to say "don't escape that ESC" but continue to escape everything else, that would be sufficient?

**Comment by Socolin** [comment] 2022-07-25 23:57
Yes, only the `escape` (`\x1b`) character is needed, what's next is then read interpreted by the terminal https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters

**Comment by x789** [comment] 2022-09-24 13:14
I would like to take over this issue. @bradwilson, can you please assign it to me?

**Comment by bradwilson** [comment] 2022-09-24 23:19
@x789 We don't really use assignment. You can just open a PR.

**Comment by x789** [comment] 2022-10-07 20:42
It took some time until I got familiar with the codebase.
@bradwilson, can you please check if my assumptions are valid?
1. The `main` branch is the baseline of the next major release (i.e. xunit 3)
2. I do not need to add a test case in the project `xunit.v2.tests` on branch `main` since it does not test the implementation of v3.
3. The `v2` branch is the baseline for the next (minor) release of xunit 2
4. When the _no-color_ mode of xunit is enabled, the ANSI escape-character must be escaped. If _no-color_ mode is inactive, the ANSI escape-character must not be escaped.

**Comment by bradwilson** [comment] 2022-10-07 23:40
@x789 

1. Correct
2. Correct, that project is about testing the v3 runners' ability to run v2 tests
3. Correct, although there is no current plan for another v2 release (doesn't mean there won't be one, but the bar is exceptionally high, and this wouldn't be enough to cause one)
4. This is something I hadn't thought about. I'd say that there are two ways you could interpret this:
    1. `-nocolor` is a switch that only matters to the runner itself, and so we do nothing if the user's tests cause color to be generated; or
    2. `-nocolor` means we strip all ANSI color codes; note, this is different than the existing behavior where we just escape them and thus the output is unreadable. So we'd explicitly go looking for `ESC[` and then strip that, plus everything up to the first `m`.

I'm actually unsure which I think is best. Clearly (ii) is much more work but may be better in line with the intention of `-nocolor`, but I would be absolutely willing to accept (i) for now and let users decide whether the extra effort for (ii) is worth it (by opening a new issue).

**Comment by bradwilson** [comment] 2022-10-16 19:16
Giving this a little more thought, I believe the job for filtering out ANSI belongs at the console runner level (presumably, by creating something which replaces the static `Console` calls with an object that can optionally filter out all color including ANSI sequences). If you opt not to do that, I will open a separate issue to update `-nocolor` behavior to do this.

**Comment by x789** [comment] 2022-10-17 11:04
Yes, I think the console-runner (who is aware of the _nocolor_-setting) is the right place. I'm still wondering which is the best solution for handling ANSI-escapes. As for now, I see two possibilities:
a. The `TestOutputHelper` (the class that escapes all non-displayable characters) escapes all characters. That means, that its behavior remains unchanged. The console-runner then checks if a string contains `\1b[` and converts that to the ANSI-escape sequence.
b. The `TestOutputHelper` does not escape the _escape_-char when it is followed by an opening square bracket. The console-runner escapes that character if _nocolor_ is active.

Solution _A_ has the disadvantage that the substring ` \1b[` in a text can be misinterpreted as an escape sequence.
Solution _B_ has the disadvantage, that the logic to support ANSI-escapes is spread accross TestOutputHelper and the console-runner.

I tend to solution _B_. @bradwilson, what is your opinion?

**Comment by bradwilson** [comment] 2022-10-17 20:32
I think solution B should actually be (if you're going to do any work in the console runner at all) to strip the color sequence (anything starting with `ESC[` and ending with the first `m`), rather than to re-escape the `ESC` and create cluttered output. I don't think it's worth the extra effort to just go back to the ugly display we have today.

So I think I might say the options actually are:

A. as you described above
B. `TestOutputHelper` special cases (does not escape) `ESC[`, and do nothing in the console runner (user-supplied color text still shows up colored even with `-nocolor`)
C. `TestOutputHelper` special cases `ESC[`, and the console runner filters out ANSI color sequences entirely when under `-nocolor`

I think I'm fine with either of B or C (your choice).

**Comment by x789** [comment] 2022-10-20 19:05
I will start with your option B. I think that I will implement option C afterwards.

**Comment by x789** [comment] 2022-10-22 09:15
The `TestOutputHelper` now does not escape the `ESC` of an [ANSI-SGR sequence](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters).
The `ConsoleRunnerLogger`  now removes all ANSI-SGR sequences when `-nocolor` is `true`.

But I found another implementation of `IRunnerLogger`; `MSBuildLogger`. With the current approach, it would write color sequences to an (MSBuild?) log. That feels strange to me. I propose that the `MSBuildLogger` behaves like the `ConsoleRunnerLogger` with `-nocolor` activated. @bradwilson: What are your thoughts?

**Comment by bradwilson** [comment] 2022-10-22 19:42
@x789 There is no `NoColor` options for the MSBuild runner, and I don't think we should add one (as MSBuild itself outputs things into color, so we wouldn't be able to influence that).

I'm not sure what MSBuild will do if presented with ANSI color (should be easy enough to verify). I think the easiest strategy is just "do nothing" for now.

**Comment by bradwilson** [comment] 2022-10-22 20:48
@x789 I just noticed this in the MSBuild help:

```
  -consoleLoggerParameters:<parameters>
                     Parameters to console logger. (Short form: -clp)
                     The available parameters are:
                        PerformanceSummary--Show time spent in tasks, targets
                            and projects.
                        Summary--Show error and warning summary at the end.
                        NoSummary--Don't show error and warning summary at the
                            end.
                        ErrorsOnly--Show only errors.
                        WarningsOnly--Show only warnings.
                        NoItemAndPropertyList--Don't show list of items and
                            properties at the start of each project build.
                        ShowCommandLine--Show TaskCommandLineEvent messages
                        ShowTimestamp--Display the Timestamp as a prefix to any
                            message.
                        ShowEventId--Show eventId for started events, finished
                            events, and messages
                        ForceNoAlign--Does not align the text to the size of
                            the console buffer
                        DisableConsoleColor--Use the default console colors
                            for all logging messages.
                        DisableMPLogging-- Disable the multiprocessor
                            logging style of output when running in
                            non-multiprocessor mode.
                        EnableMPLogging--Enable the multiprocessor logging
                            style even when running in non-multiprocessor
                            mode. This logging style is on by default.
                        ForceConsoleColor--Use ANSI console colors even if
                            console does not support it
                        Verbosity--overrides the -verbosity setting for this
                            logger.
                     Example:
                        -consoleLoggerParameters:PerformanceSummary;NoSummary;
                                                 Verbosity=minimal
```

I wonder what happens when we use `DisableConsoleColor` but still send our own ANSI colors? Will it filter them out? If not, is it even possible for us to know the user has requested `DisableConsoleColor`?

Once again, I'd like to say that it's entirely reasonable to ignore this problem and pick it up as a secondary issue. The primary value we're after with this is to stop escaping ESC when it's part of a CSI. Everything else can be handled separately.

Also, I took a quick look at your branch and I noticed this:

```csharp
Regex AnsiSgrRegex = new Regex("\\e\\[\\d+[m]");
```

I think you want this instead, to handle semi-colon separated attributes:

```csharp
Regex AnsiSgrRegex = new Regex("\\e\\[\\d+(;\\d+)*[m]");
```

and then add some tests looking for things like `ESC[0;1;41m` to validate that compound attributes.

**Comment by Socolin** [comment] 2022-10-22 20:48
About -NoColor there is an env variable too used in many programs: NO_COLOR 
https://no-color.org/
But I don't think the behavior should change things about escape, when NO_COLOR is set, color codes should not be emit in the first place.

I think when -NoColor is given XUnit could set this env so it's easy for underlying code to not emit color codes.

**Comment by bradwilson** [comment] 2022-10-22 20:51
@Socolin We support reading that:

https://github.com/xunit/xunit/blob/653218c4f84714e7031c8118d9d0bb1f5529958a/src/xunit.v3.runner.common/Frameworks/TestProjectConfiguration.cs#L75

I hadn't considered that we should also set it when the user provides `-nocolor`. I'll open a new issue for that. Thanks!

**Comment by x789** [comment] 2022-10-23 09:11
@bradwilson: Thank you for highlighting the problem with semicolon-separated attributes. I overlooked this possibility in the Wikipedia article.
When I read it again, I saw that arguments may also be omitted:
> Missing numbers are treated as 0 (1;;3 acts like the middle number is 0, and no parameters at all in ESC[m acts like a 0 reset code).

Accordingly, I will change the regex to:
`"\\e\\[\\d*(;\\d*)*[m]"`

**Comment by Socolin** [comment] 2022-10-23 16:20
If you want to test with complex scenarios, I have a nuget package generating color codes accordingly to the wikipedia pages https://github.com/Socolin/Socolin.ANSITerminalColor

**Comment by bradwilson** [comment] 2022-11-05 18:52
Fixed by #2606

**Closed by bradwilson** 2022-11-05 18:52 UTC
Labels: type: Feature, area: Core framework, help wanted, good first issue

**Comment by DerAlbertCom** [comment] 2023-05-18 17:17
Fixed also in Rider 2023.1.2 https://youtrack.jetbrains.com/issue/RIDER-93438/Unit-test-console-for-xUnit-does-not-support-ansi-escape-sequencse

**Comment by chekkan** [comment] 2025-03-13 10:00
Will this fix be backported to xunit v2?

**Comment by bradwilson** [comment] 2025-03-13 19:03
@chekkan There are currently no more planned v2 releases.
