### ISSUE TITLE
Class fixture constructor called multiple times

### ISSUE THREAD

**Issue by rafak360** [xunit/xunit#2347] opened 2021-07-10 18:37 UTC
Note that it's the same or similar issue as reported in: https://github.com/xunit/xunit/issues/120

The following stackoverflow question covers up everything:
https://stackoverflow.com/questions/68325189/why-this-fixture-is-running-its-constructor-more-than-once

So what kind of data should I provide to help fix up that bug on my machine?

**Comment by bradwilson** [comment] 2021-07-26 03:22
I'm not able to reproduce this outside of Visual Studio/VSTest. Is it only reproduced when using Visual Studio (or VSTest via `dotnet test`)?

![image](https://user-images.githubusercontent.com/16944/126928799-86f8c5d4-44ed-4caa-aa8f-91962c830635.png)

**Comment by rafak360** [comment] 2021-07-27 08:43
> I'm not able to reproduce this outside of Visual Studio/VSTest. Is it only reproduced when using Visual Studio (or VSTest via `dotnet test`)?
> 
> ![image](https://user-images.githubusercontent.com/16944/126928799-86f8c5d4-44ed-4caa-aa8f-91962c830635.png)
I only used Visual Studio Community 2019 16.10.3, never tried VSTest.

**Comment by mattramsay-ice** [comment] 2021-12-01 12:18
I've seen similar behaviour when running tests in VS Enterprise 2019, when running the tests via right-click on the test class name and then run (class fixture constructor ran multiple times).

Interestingly, if I enact the test run from within the test explorer window (instead of right-clicking the name of test class > run) I don't see the same issue.

FYI - I'm using MS Visual Studio Enterprise 2019 v16.10.3

**Comment by rafak360** [comment] 2021-12-01 13:23
> I've seen similar behaviour when running tests in VS Enterprise 2019, when running the tests via right-click on the test class name and then run (class fixture constructor ran multiple times).
> 
> Interestingly, if I enact the test run from within the test explorer window (instead of right-clicking the name of test class > run) I don't see the same issue.
> 
> FYI - I'm using MS Visual Studio Enterprise 2019 v16.10.3

Nice catch! I always run my tests from right-clicks so it seems it follows a different path from the right-click popup menu which is leading to a faulty algorithm.

**Comment by bradwilson** [comment] 2021-12-01 16:49
The bug is caused by Visual Studio not realizing that it should give us an entire list of tests to run, instead of handing us the tests one at a time. When it does this, we have to treat each test individually (we have no idea what's coming later), and thus the "over-creation" of the fixture. From our perspective, it's exactly the same as if you'd asked to run one test, get the result, and then decided to run a second test separately.

**Comment by dguerin** [comment] 2023-02-11 13:19
Is there any updates on this issue? It sounds like something that is not xunit specific per say but has there been any follow up with MS or the VS Team either?

**Comment by masleshov** [comment] 2023-04-13 10:09
Caught the issue running my test using CLI "dotnet test ...". .NET 7, XUnit 2.4.2

**Comment by bradwilson** [comment] 2023-04-19 20:05
I'm going to close this issue. I would suggest @rafak360 (or some other interested party) open an issue with the VSTest/Test Explorer team(s) and provide a back-reference to this issue for them.

**Closed by bradwilson** 2023-04-19 20:05 UTC
Labels: status: Waiting for Repro/Response

**Comment by Spharad** [comment] 2025-01-06 06:59
This is still an issue in VS 2022
