### ISSUE TITLE
System.AppDomainUnloadedException when running tests on TFS Build Server

### ISSUE THREAD

**Issue by kmcbrearty** [xunit/xunit#256] opened 2015-01-15 03:53 UTC
Currently getting the following error when trying to use xUnit 2.0 in a TFS build process.  If I roll back to xUnit 1.9.2 unit tests are discovered and ran successfully on the build server.

System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain. This can happen if the test(s) started a thread but did not stop it. Make sure that all the threads started by the test(s) are stopped before completion.

Team Foundation Server 2013 Update 2
Build Configuration Release | x86
Xunit.Runner.VisualStudio 0.99.9-build1021
Xunit 2.0.0-beta5-build2785

Steps Taken:

- Created New Test Project
- Installed Nuget Packages
```
install-package xunit.runner.visualstudio my.tests -includeprerelease
install-package xunit my.tests -includeprerelease
```
- Created simple test class
```
namespace My.Tests
{
    public class XunitFacts
    {
		[Fact]
		public void CanRunTest()
		{
			Assert.True(true);	
		}
    }
}
```
- Successfully discovered and ran tests locally
- Commit changes to TFS and ran a CI Build

**Comment by bradwilson** [comment] 2015-01-15 15:31
Duplicate of https://github.com/xunit/visualstudio.xunit/issues/6

**Closed by bradwilson** 2015-01-15 15:31 UTC

**Comment by kmcbrearty** [comment] 2015-01-15 15:35
Sorry I tried to look to see it was an existing issue and didn't see anything.  This is completely preventing me from using it with automated builds so hopefully the priority on this gets increased.  At any rate hopefully the additional details help.

**Comment by bradwilson** [comment] 2015-01-15 18:12
This has not been a blocking issue in Visual Studio (it runs all the tests just fine).

How does it manifest as a blocking issue in Team Build?

**Comment by kmcbrearty** [comment] 2015-01-15 19:58
I am not able to run any unit tests at all.  Any attempt to run a unit test through VS Test Runner in a build results in the following.  
![image](https://cloud.githubusercontent.com/assets/10541440/5765304/6a3a6e94-9cc6-11e4-8fd7-84551b4a3749.png)

Now what I just realized is that this might be a composite issue of enabling Telerik.JustMock profiler within the build.  At the moment I do not have an easy way to prevent the JustMock profiler from being enabled because I didn't foresee a case where I wouldn't need it for mocking.  Either way this is preventing me from running any test.  Based on the linked issue though I don't know that this is caused by Telerik.JustMock.

**Comment by lijunle** [comment] 2015-03-04 16:10
Just FYI: I saw this warning on my Visual Studio Online (TFS Online), but the test cases are NOT blocking.

**Comment by DerAlbertCom** [comment] 2015-05-20 19:59
Yes, in Visual Studio i get this also. WIth very simple Tests. No TypeMock, JustMock or mocking in generall (was only a test).

**Comment by kmcbrearty** [comment] 2015-08-24 14:43
The link for the related item is broken and I am unable to locate the issue.  I really need to know what the status of this issue is.  We still seem to be encountering this problem when attempting to upgrade to xUnit 2.0.

**Comment by kmcbrearty** [comment] 2015-08-24 15:08
Nevermind, I was able to find it and it is still open.  For anyone seeing this in the future the updated link is:

https://github.com/xunit/xunit/issues/490
