### ISSUE TITLE
XUnit tests don't run (endless loop)

### ISSUE THREAD

**Issue by zezba9000** [xunit/xunit#1910] opened 2019-03-07 02:27 UTC
I have a "EMPTY" "[Fact]" / UnitTest method that doesn't run.

* Win10, x64.
* .NET Core SDK 2.2.104
* xUnit proj includes a .NET Standard 2.0 lib
* VS 2017 15.9.8

Click run all tests or try to debug and the green progress bar at the top in VS just keeps doing it waiting green pan. I have tried deleting all NuGet packages, clean builds etc.

This might be some kind of cache bug but idk what to test for that.
https://stackoverflow.com/questions/55035137/xunit-tests-dont-run-endless-loop

**Comment by zezba9000** [comment] 2019-03-07 19:26
Somehow a .NET Core / UWP or .NET Standard 2.0 lib is messing up xUnit as I'm building out all my libs into a single bin path as it helps with mixed C# and C/C++ debugging.

**Comment by zezba9000** [comment] 2019-03-07 19:34
Ok found the issue. Have Newtonsoft.Json.dll from a .NET Framework project in the same directory as my test libraries. This is somehow causing an endless loop.

**Comment by bradwilson** [comment] 2019-03-12 22:50
>I'm building out all my libs into a single bin path

We don't support this. If this is the cause of your problems, then this is a Won't Fix issue.

**Comment by bradwilson** [comment] 2019-03-12 22:50
>Ok found the issue. Have Newtonsoft.Json.dll from a .NET Framework project in the same directory as my test libraries.

Yeah. Frankly, building everything into a single folder is a stupid idea. You're gonna be happier when you stop doing that. This is why we don't support it.

**Comment by zezba9000** [comment] 2019-03-12 23:03
Its actually not a stupid idea when 99% of your libs and apps share the same stuff. Makes it very easy to validate packaging. It is stupid to lump .NET Core with .NET Framework though which I've moved out (even though .NET Framework only depended on .NET Standard libs).

XUnit has potentially issues when testing projects with different version of Json.NET. Because you guys will move to .NET Core 3.0 json libs the issue will go away maybe. Seems like xUnit should pre-load its dependencies without effecting the testing binaries. Reflection could be used for this I think.

**Comment by bradwilson** [comment] 2019-03-12 23:19
Current versions of xUnit.net don't use JSON.net at all. There is no conflict here.

**Comment by bradwilson** [comment] 2019-03-12 23:21
.NET Core itself absolutely has a dependency on JSON.net. If you replaced the .NET Core/.NET standard version of JSON.net with a .NET Framework version, you'll be breaking .NET Core, not us.

**Comment by zezba9000** [comment] 2019-03-12 23:25
Why would the .NET Core runtime depend on that? This seems wrong / odd. Anyway thanks for clarifying what is loading it.

**Comment by bradwilson** [comment] 2019-03-13 06:16
I made the exact same argument to them, and they agreed. It's taken them until 3.0 to remove it (and replace it with something else that's built-in). The problem is that nothing inside the core platform should ever take dependencies on anything that's not in the core platform, or else you get into this situation where version upgrades can't be safely respected.

Unfortunately, they are using JSON.NET to de-serialize several things; the most deeply embedded is the dependency resolution system's JSON files (`.deps.json` and friends), and since this is used to load assemblies, it's used by every single .NET Core application. (This doesn't even begin to scratch the surface, as it's also used in higher layers of the platform, like the configuration system and ASP.NET Core's support for JSON input/output in controllers.)

**Comment by bradwilson** [comment] 2019-03-14 16:26
Resolving this as an external issue.

**Closed by bradwilson** 2019-03-14 16:26 UTC
Labels: status: External
