### ISSUE TITLE
Proposal: Better user experience when Microsoft.NET.Test.Sdk reference is missing

### ISSUE THREAD

**Issue by NickCraver** [xunit/xunit#1450] opened 2017-09-10 16:52 UTC
#### Problem
Something I've hit several times now is migrating an existing project to the new project system (SDK style) and missing tests in Visual Studio, after chatting with others it seems like I'm not alone. I think xUnit can improve this a bit in a simple way.

In the SDK, there is defined a `UsingMicrosoftNETSdk` property ([see here](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.props#L26)). If this is defined, then the user needs [`Microsoft.NET.Test.Sdk`](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/) as well.

#### Proposal
In an xUnit package (not sure if `xunit` or `xunit.runner.visualstudio`, since `dotnet xunit` is in play too - I'm thinking `xunit` itself), provide a build warning to the user.

If we look for: `$(UsingMicrosoftNETSdk) == 'true'` and that the `PackageReference` doesn't exist for `Microsoft.NET.Test.Sdk` >= 15.0.0, then we have our situation, and emit a build warning that the `Microsoft.NET.Test.Sdk` reference needs to be added. In addition, this should include an override property (something like `<xUnitDisableSdkChecks>true</xUnitDisableSdkChecks>`) to disable the check from triggering if the user so desires.

Thoughts? Something like this would have saved me many hours, I'm hoping it'd do the same for other users.

**Comment by onovotny** [comment] 2017-09-10 16:55
The issue is that packages cannot bring in other packages via props/targets since NuGet doesn't do another pass after the restore. If they did, when would it stop, since it'd be recursive.

It would be possible to display a warning though.

**Comment by NickCraver** [comment] 2017-09-10 16:55
cc @onovotny @vcsjones

**Comment by NickCraver** [comment] 2017-09-10 17:15
Rephased the above to be clearer: I'm only proposing including a warning, no package changes (I see that being problematic with version skew later anyway).

**Comment by bradwilson** [comment] 2017-09-10 18:41
I'm reluctant to issue a warning for all users when there only affected users are those using the Visual Studio runner (which I believe to be in the minority).

**Comment by bradwilson** [comment] 2017-09-10 18:43
`Microsoft.NET.Test.Sdk` is *_not_* required for `dotnet xunit`.

**Comment by onovotny** [comment] 2017-09-10 19:36
@bradwilson the warning could come from targets that are only in the VS runner package?

**Comment by vcsjones** [comment] 2017-09-10 20:11
>which I believe to be in the minority

You're probably in the best position to say that but I'm a tad surprised.

I'm happy to use `dotnet xunit` in CI scenarios or right before a check in, but if I need to run an individual test or debug a test, the VS Runner is my go-to. Debugging is really the core scenario where I needed VS Runner support working. I would have been reluctant to move forward with a migration to SDK-style projects if I wasn't sure that the debugging story was working.

Secondly I think it's helpful to have it working in as many scenarios as possible for library authors in open projects. Some contributors may be comfortable with xunit CLI, others may prefer the VS GUI runner.

I agree that putting this in xunit feels strange - it would make more sense if the VS runner handled or warned on this, somehow. That would cover other test frameworks as well. However having xunit do it is more likely to happen and happen sooner than anything that's going to happen in vstest. Maybe this becomes throw away work because the user story around this gets better in vstest itself. But a helping hand to those using xunit would be appreciated.

**Comment by NickCraver** [comment] 2017-09-10 20:13
Without the SDK, users can get run failures with `dotnet xunit` as well, because the test SDK does some magic with runtimes in `netcoreapp`targets. 

For a runnable example of this I just hit, grab [`StackExchange.Exceptional`](https://github.com/NickCraver/StackExchange.Exceptional/tree/f5b59c787543db2938b3bb5e0dd211b9de1aafbb) and remove [the `Microsoft.NET.Test.Sdk` reference](https://github.com/NickCraver/StackExchange.Exceptional/blob/f5b59c787543db2938b3bb5e0dd211b9de1aafbb/tests/Directory.build.props). `dotnet xunit` no longer runs the .NET Core tests because SqlClient does not know which runtime DLL to resolve. This confused me for a while too, but to say this only affects Visual Studio is incorrect.

With the test SDK:
```
λ dotnet xunit
Detecting target frameworks in StackExchange.Exceptional.Tests.AspNetCore.csproj...
Building for framework net461...
  StackExchange.Exceptional.Shared -> c:\git\NickCraver\StackExchange.Exceptional\src\StackExchange.Exceptional.Shared\bin\Debug\net451\StackExchange.Exceptional.Shared.dll
  StackExchange.Exceptional.AspNetCore -> c:\git\NickCraver\StackExchange.Exceptional\src\StackExchange.Exceptional.AspNetCore\bin\Debug\net461\StackExchange.Exceptional.AspNetCore.dll
  StackExchange.Exceptional.Tests.AspNetCore -> c:\git\NickCraver\StackExchange.Exceptional\tests\StackExchange.Exceptional.Tests.AspNetCore\bin\Debug\net461\StackExchange.Exceptional.Tests.AspNetCore.dll
Running desktop CLR tests for framework net461...
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
  Discovering: StackExchange.Exceptional.Tests.AspNetCore
  Discovered:  StackExchange.Exceptional.Tests.AspNetCore
  Starting:    StackExchange.Exceptional.Tests.AspNetCore
  Finished:    StackExchange.Exceptional.Tests.AspNetCore
=== TEST EXECUTION SUMMARY ===
   StackExchange.Exceptional.Tests.AspNetCore  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.965s
Building for framework netcoreapp2.0...
  StackExchange.Exceptional.Shared -> c:\git\NickCraver\StackExchange.Exceptional\src\StackExchange.Exceptional.Shared\bin\Debug\netstandard2.0\StackExchange.Exceptional.Shared.dll
  StackExchange.Exceptional.AspNetCore -> c:\git\NickCraver\StackExchange.Exceptional\src\StackExchange.Exceptional.AspNetCore\bin\Debug\netstandard2.0\StackExchange.Exceptional.AspNetCore.dll
  StackExchange.Exceptional.Tests.AspNetCore -> c:\git\NickCraver\StackExchange.Exceptional\tests\StackExchange.Exceptional.Tests.AspNetCore\bin\Debug\netcoreapp2.0\StackExchange.Exceptional.Tests.AspNetCore.dll
Running .NET Core tests for framework netcoreapp2.0...
xUnit.net Console Runner (64-bit .NET Core 4.6.00001.0)
  Discovering: StackExchange.Exceptional.Tests.AspNetCore
  Discovered:  StackExchange.Exceptional.Tests.AspNetCore
  Starting:    StackExchange.Exceptional.Tests.AspNetCore
  Finished:    StackExchange.Exceptional.Tests.AspNetCore
=== TEST EXECUTION SUMMARY ===
   StackExchange.Exceptional.Tests.AspNetCore  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.395s
```
Without it:
```
λ dotnet xunit
Detecting target frameworks in StackExchange.Exceptional.Tests.AspNetCore.csproj...
Building for framework net461...
  StackExchange.Exceptional.Shared -> c:\git\NickCraver\StackExchange.Exceptional\src\StackExchange.Exceptional.Shared\bin\Debug\net451\StackExchange.Exceptional.Shared.dll
  StackExchange.Exceptional.AspNetCore -> c:\git\NickCraver\StackExchange.Exceptional\src\StackExchange.Exceptional.AspNetCore\bin\Debug\net461\StackExchange.Exceptional.AspNetCore.dll
  StackExchange.Exceptional.Tests.AspNetCore -> c:\git\NickCraver\StackExchange.Exceptional\tests\StackExchange.Exceptional.Tests.AspNetCore\bin\Debug\net461\StackExchange.Exceptional.Tests.AspNetCore.dll
Running desktop CLR tests for framework net461...
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
  Discovering: StackExchange.Exceptional.Tests.AspNetCore
  Discovered:  StackExchange.Exceptional.Tests.AspNetCore
  Starting:    StackExchange.Exceptional.Tests.AspNetCore
  Finished:    StackExchange.Exceptional.Tests.AspNetCore
=== TEST EXECUTION SUMMARY ===
   StackExchange.Exceptional.Tests.AspNetCore  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.933s
Building for framework netcoreapp2.0...
  StackExchange.Exceptional.Shared -> c:\git\NickCraver\StackExchange.Exceptional\src\StackExchange.Exceptional.Shared\bin\Debug\netstandard2.0\StackExchange.Exceptional.Shared.dll
  StackExchange.Exceptional.AspNetCore -> c:\git\NickCraver\StackExchange.Exceptional\src\StackExchange.Exceptional.AspNetCore\bin\Debug\netstandard2.0\StackExchange.Exceptional.AspNetCore.dll
  StackExchange.Exceptional.Tests.AspNetCore -> c:\git\NickCraver\StackExchange.Exceptional\tests\StackExchange.Exceptional.Tests.AspNetCore\bin\Debug\netcoreapp2.0\StackExchange.Exceptional.Tests.AspNetCore.dll
Running .NET Core tests for framework netcoreapp2.0...
Error:
  An assembly specified in the application dependencies manifest (StackExchange.Exceptional.Tests.AspNetCore.deps.json) was not found:
    package: 'System.Data.SqlClient', version: '4.1.0'
    path: 'runtimes/win/lib/netstandard1.3/System.Data.SqlClient.dll'
```

**Comment by NickCraver** [comment] 2017-09-10 20:18
I'm also curious about the Visual Studio minority claim - according to NuGet:
- [`xunit` download stats](https://www.nuget.org/stats/packages/xunit?groupby=Version)

| Version | Downloads |
|---------|------------|
|2.3.0-beta5-build3769 | 4,793|
|2.3.0-beta4-build3742 | 32,815|
|2.3.0-beta3-build3705 | 37,591|
|2.3.0-beta2-build3683 | 29,665|
|2.3.0-beta1-build3642 | 14,696|
|2.2.0 | 391,500|

- [`xunit.runner.visualstudio` download stats](https://www.nuget.org/stats/packages/xunit.runner.visualstudio?groupby=Version)

| Version | Downloads |
|---------|------------|
|2.3.0-beta5-build3769 | 4,461|
|2.3.0-beta4-build3742 | 31,262|
|2.3.0-beta3-build3705 | 40,295|
|2.3.0-beta2-build1317 | 24,587|
|2.3.0-beta1-build1309 | 11,265|
|2.2.0 | 348,049|

...it would seem the vast majority of users are using it. I'm really curious if you guys have data showing a different story, since that'd make me question our own NuGet downloads vs. real-world usage.

**Comment by bradwilson** [comment] 2017-09-10 21:55
> Without the SDK, users can get run failures with dotnet xunit

Please open this as a separate issue do that it can get fixed.

**Comment by onovotny** [comment] 2017-09-11 15:07
Sorry, hit the button by mistake

**Comment by bradwilson** [comment] 2017-10-01 21:23
No need for warnings. I just put a dependency into the .nuspec file. Now you can't forget. :) 2c85a423

I'm considering this issue closed as a result.

**Closed by bradwilson** 2017-10-01 21:23 UTC
