### ISSUE TITLE
Generic method broken with xunit 2.4

### ISSUE THREAD

**Issue by ViktorHofer** [xunit/xunit#1781] opened 2018-08-09 09:43 UTC
This sample which worked in xunit 2.3.1 doesn't work anymore in xunit 2.4 and results in a "Specified method is not supported" exception:

```
[Theory, MemberData(nameof(ReverseData))]
public void RunOnce<T>(IEnumerable<T> source, T dummy)
{
    T[] expected = source.ToArray();
    Array.Reverse(expected);

    IEnumerable<T> actual = source.Reverse();

    Assert.Equal(expected, actual);
}

public static IEnumerable<object[]> ReverseData()
{
    var integers = new[]
    {
        Array.Empty<int>(), // No elements.
        new[] { 1 }, // One element.
        new[] { 9999, 0, 888, -1, 66, -777, 1, 2, -12345 }, // Distinct elements.
        new[] { -10, 0, 5, 0, 9, 100, 9 }, // Some repeating elements.
    };
    
    // TODO: Remove workarounds when xUnit is updated to include xunit/xunit#965.
    return integers
        .Select(collection => new object[] { collection, 0 })
        .Concat(
            integers.Select(c => new object[] { c.Select(i => i.ToString()), string.Empty })
        );
}
```

Exception:
```
Error Message:
 System.NotSupportedException : Specified method is not supported.
Stack Trace:
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Is that a known bug? This currently blocks us in corefx adopting the xunit 2.4 runner. It would ideal if we can fix that issue so that we can either take a dependency on a nightly build or a service release.

**Comment by ViktorHofer** [comment] 2018-08-09 09:48
cc @bradwilson @onovotny

**Comment by ViktorHofer** [comment] 2018-08-10 18:45
Any hints how to debug that issue? I looked through the commits if something related shouts out but didn't find anything.

**Comment by bradwilson** [comment] 2018-08-12 02:01
Looks like a new bug. I don't know of any workaround, other than staying on 2.3.1.

**Comment by bradwilson** [comment] 2018-08-13 00:51
Sorry, no. I've done no investigation into the problem, only verified that it was broken.

**Comment by ViktorHofer** [comment] 2018-08-13 19:54
Ok then I'll start digging.

**Comment by jkotas** [comment] 2018-08-15 14:58
@ViktorHofer What is the method that this is trying to call?

**Comment by ViktorHofer** [comment] 2018-08-15 15:03
The test method (`MethodInfo`): https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs#L150

**Comment by ViktorHofer** [comment] 2018-08-15 15:17
Could also be the MemberData method invocation: https://github.com/xunit/xunit/blob/master/src/xunit.core/MemberDataAttributeBase.cs#L116

**Comment by ViktorHofer** [comment] 2018-08-15 15:27
@jkotas It seems to be throwing here: https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/TypeUtility.cs#L160

**Comment by jkotas** [comment] 2018-08-15 15:33
I think it is throwing because of we are trying to invoke a method that takes byref-like types (`Span<T>`, etc.). MethodInfo.Invoke does not support it.

> `op_Implicit`

Maybe the problem is that we have added more implicit conversions somewhere, and xunit is picking a wrong implicit conversion now?

**Comment by ViktorHofer** [comment] 2018-08-20 21:27
You are right, it picks this one: `{System.ReadOnlySpan`1[System.Char] op_Implicit(System.String)}` which has a return type of ReadOnlySpan<char>.

**Comment by bradwilson** [comment] 2018-10-10 20:40
This original fix was incorrect, so I fixed it so that it always works, not just on NS2. Re-closing. If you think you have a repro with the latest 2.4 pre-release build, open a new issue.

https://github.com/xunit/xunit/commit/be452a200ea2f8fc189eded722d43bae1a37ce23#diff-60e08670daa222f4aa773b0c4f4030c9

**Closed by bradwilson** 2018-10-10 20:40 UTC
Labels: area: Core framework, help wanted, type: Bug
