### ISSUE TITLE
dotnet xunit fails to load localization assemblies

### ISSUE THREAD

**Issue by onovotny** [xunit/xunit#1597] opened 2017-12-22 18:07 UTC
Tests fail with `dotnet xunit` but succeed with `dotnet test`. The failing tests are around localization and the test project has resource assemblies that get produced `locale\foo.resources.dll`.

Repro:
Get Humanizer https://github.com/Humanizr/Humanizer
go to /src/Humanizer.Tests
run `dotnet test` - pass.
run `dotnet xunit` lots of failing tests

Tested with `2.4.0-beta1-build3895` and still has the same issue.

**Comment by GeorgDangl** [comment] 2017-12-22 19:34
This looks like a duplicate of #1555

**Comment by bradwilson** [comment] 2017-12-30 07:23
Verified fixed with 2.4.0-beta1-build3897:

![image](https://user-images.githubusercontent.com/16944/34452212-47d02cdc-ecef-11e7-8e47-f5bfdea0fb5d.png)

**Closed by bradwilson** 2017-12-30 07:23 UTC
