### ISSUE TITLE
xUnit1026 (Unused parameter) fires on `fixed` statement

### ISSUE THREAD

**Issue by Gnbrkm41** [xunit/xunit#1969] opened 2019-06-20 10:36 UTC
https://github.com/dotnet/corefx/pull/38701/files#diff-91724393075e1a7718d3521655506742R86

In the following test code:
```cs
        public static unsafe void Ctor_CharPtr_Int_Int(char[] valueArray, int startIndex, int length, string expected)
        {
            fixed (char* value = valueArray)
            {
                Assert.Equal(expected, new string(value, startIndex, length));
            }
        }
```

`valueArray` is marked as unused even though it is used in the `fixed` statement.

**Comment by AidanTheDeveloper** [comment] 2019-10-14 06:57
Hey @Gnbrkm41 I'm new to this repo, but I'm interested in finding ways to contribute. I've taken a look at this issue, but I have been having trouble reproducing it. I tried adding a similar test to test.xunit1/xunit.extensions/DataTheories/GenericTheoryTest.cs, but when I build test.xunit1 I get no warnings. I was wondering if you could point me in the right direction here 😅
![image](https://user-images.githubusercontent.com/15628084/66733686-d0737280-eebc-11e9-9dd6-bcd6acd4062a.png)

**Comment by Gnbrkm41** [comment] 2019-10-14 07:13
@AidanTheDeveloper I am not completely sure why it's not happening on your side, but for me this is enough to reproduce the error from an empty project:
```cs
using System;
using Xunit;

namespace XUnitTestProject2
{
    public class UnitTest1
    {
        [Theory]
        [InlineData(new char[] { 'a' })]
        public static unsafe void FixedBlockUnusedValue(char[] valueArray)
        {
            fixed (char* value = valueArray)
            {
                Assert.Equal('a', *value);
            }
        }
    }
}
```

Attaching the whole solution, though I doubt this actually matters. [XUnitTestProject2.zip](https://github.com/xunit/xunit/files/3723319/XUnitTestProject2.zip)

As far as the workflow of this repo is concerned, I am not aware of it & can't tell much about it but is that how you test that the analyzers work? Just adding the tests to the file then building the repo.

**Comment by AidanTheDeveloper** [comment] 2019-10-14 07:25
@Gnbrkm41 Honestly I'm not really sure how to test anything at this point, but I've managed to reproduce your issue by creating an empty project. I'll try to investigate this some more, but this is my first issue so it'll probably take me a while to figure out what's going on. I appreciate your fast response!

**Comment by hrai** [comment] 2020-09-01 01:53
I added this test to the analyser but the test seems to pass without throwing any diagnostic error.

https://github.com/hrai/xunit.analyzers/commit/0154531285ce6c159e55a4ba2cc97907719ab17c

**Comment by bjornhellander** [comment] 2022-07-16 14:35
I created a test case and the variable is reported as "WrittenInside" (instead of "ReadInside") by the data flow analysis.
Looks like a Roslyn bug: https://github.com/dotnet/roslyn/issues/60402

**Comment by bradwilson** [comment] 2023-08-03 19:51
We use Roslyn to do the analysis of what's used or not:

https://github.com/xunit/xunit.analyzers/blob/4c1c7e2fce2d65e473c8eef2ba83ec0b37d3c144/src/xunit.analyzers/X1000/TheoryMethodShouldUseAllParameters.cs#L54

It seems to me like this is might be a bug or missing feature on the Roslyn side.

**Comment by bradwilson** [comment] 2023-12-22 04:31
Closing because it's a Roslyn issue.

**Closed by bradwilson** 2023-12-22 04:31 UTC
Labels: type: Bug, status: External, area: Analyzers
