### ISSUE TITLE
[Fact] methods are not allowed to be generic during TDD

### ISSUE THREAD

**Issue by shaunluttin** [xunit/xunit#1622] opened 2018-01-26 16:54 UTC
We have been following the Microsoft docs on [unit testing with .NET Core and xUnit.](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-fsharp-with-dotnet-test#creating-the-test-project), which recommends initially stubbing functions by returning a `NotImplementedException`. 

---

**Actual behavior**: xUnit fails the test with a `InvalidOperationException`.
**Expected behavior**: xUnit fails the test with a `NotImplementedException`. 

```
module Tests

open Xunit

let foo x = raise (System.NotImplementedException("Not implemented"))

[<Fact>]
let ``foo test`` () = foo 0
```

> Failed   Tests.foo test                                                          
> Error Message:                                                                   
>  System.InvalidOperationException : [Fact] methods are not allowed to be generic.

--- 

One work around is to call `foo` with type parameters

```
[<Fact>]
let ``foo test`` () = foo<int, int> 0
```

Then the test will fail with a `NotImplementedException`.

**Comment by bradwilson** [comment] 2018-01-29 07:31
This is by design, even if it seems strange from F#. If a method is an open generic, then we don't know how to close it to instantiate it. For theories, we can close open generic methods when they are represented by a (non-null) method parameter.

**Closed** 2018-02-11 22:54 UTC
