### ISSUE TITLE
Some generic theories pass on Windows while failing on Linux 

### ISSUE THREAD

**Issue by safakgur** [xunit/xunit#1788] opened 2018-08-18 14:14 UTC
Windows 10 Pro 17134.112

The project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.8.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <PackageReference Include="coverlet.msbuild" Version="2.2.1" />
  </ItemGroup>

</Project>
```

The test:

```c#
using Xunit;

namespace Tests
{
    public sealed class Tests
    {
        [Theory]
        [InlineData(null)]
        [InlineData(1)]
        [InlineData("S")]
        public void GenericTest<T>(T value)
        {
            var temp = value;
        }
    }
}
```

`dotnet test` (SDK 2.1.400-win-x64) succeeds:

```
Test run for ...\bin\Debug\netcoreapp2.0\Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 3. Passed: 3. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1,2411 Seconds
```

Then I start `wsl` on the same device.

* `lsb_release -a` gives me "Ubuntu 16.04.4"
* `dotnet test` (SDK 2.1.400-linux-x64) fails:

```
Test run for /mnt/c/.../bin/Debug/netcoreapp2.0/Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.41]     Tests.Tests.GenericTest [FAIL]
Failed   Tests.Tests.GenericTest
Error Message:
 System.NotSupportedException : Specified method is not supported.
Stack Trace:
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location where exception was thrown ---

Total tests: 3. Passed: 2. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 3.9909 Seconds
```

Points of interest:
* Tests pass 2/2 if I remove `[InlineData(1)]`.
* Tests pass 3/3 if I change `TargetFrameworks` value to "netcoreapp1.0".

Edit:
* [Same behavior][1] on macOS.

[1]: https://travis-ci.org/safakgur/guard/builds/417704032

**Comment by bradwilson** [comment] 2018-08-18 16:39
Seems like a duplicate of #1781.

**Comment by ViktorHofer** [comment] 2018-08-20 20:01
Yeah that's the same cause. Only the netcoreapp runner is affected.

**Closed** 2018-08-21 21:49 UTC

**Comment by bradwilson** [comment] 2018-10-10 20:41
Disagree. https://github.com/xunit/xunit/issues/1781#issuecomment-428723521
