### ISSUE TITLE
FormatComplexValue breaks xUnit v1-Upgrades using AutoFixture.NSubstitute

### ISSUE THREAD

**Issue by dklinger** [xunit/xunit#1682] opened 2018-03-29 18:21 UTC
Hello, we are in the upgrade-process vom xUnit to xUnit2. Currently one-fifth of our tests are failing after the upgrade because the test-naming-process described at https://github.com/xunit/xunit/issues/243 is a breaking change in xUnit, at least for us. We are talking of 1000 failing tests and more for every project. 
We are using xUnit, AutoFixture, NSubstitute and AutoFixture.NSubstitute.
In this scenario our tests look like this:
```csharp
        [Theory, AutoNSubstituteData]
        public void DoItNowAsProperty_UsingAutoNSubstitute(
            [Frozen] IRunSpeed runSpeed,
            GetToDaChoppa sut)
        {
            // Arrange
            runSpeed.Speed.Returns(49);

            //Act
            var x = sut.DoItNow;

            //Assert
            var tmp = runSpeed.Received(1).Speed;
            Assert.Equal(1, runSpeed.ReceivedCalls().Count());
        }
```
The failed tests come from the ".Received()" and ".ReceivedCalls()" lines. The breaking change is, that xUnit2 is now calling all properties of the system under test - as the SUT is part of the test methods parameters - and therefore calling all of its properties once. As part of our test-methodology is to test the call count on those properties, all of our tests having either ".Received()" or ".ReceivedCalls()" are now failing as the call count is +1 compared to xUnit v1. 

My feature request therefore is to have a global option which turns of the execution of the Value-retrieval-process of Complex test-method-parameters(this part of the ArgumentFormatter: https://github.com/xunit/assert.xunit/blob/2b70a9b0c5bb291f98472ec24cec437acf8d65c8/Sdk/ArgumentFormatter.cs#L156)

Besides the feature request: Do you have any suggestion for us on how to proceed with the upgrade process without changing thousands of test methods? Or is there no "easy" way?

**Comment by bradwilson** [comment] 2018-05-21 15:09
Assuming the issue is caused by theory pre-enumeration, that is a flag you can set: `[MemberData(..., DisableDiscoveryEnumeration=true)]`. I have no idea whether `[AutoNSubstituteData]` offers such a flag.

**Comment by zvirja** [comment] 2018-05-21 15:27
@bradwilson This issue has nothing to do with the discovery enumeration. I've provided the scenario above with pure xUnit/NSubstitute and if you change it to disable the enumeration, it will still fail - try to copy it and run 😉

**Comment by bradwilson** [comment] 2018-05-25 17:54
Then that's definitely something we won't fix.

**Comment by dklinger** [comment] 2018-07-18 11:52
Hi Brad. That's sad to hear. 
So there isn't any change on making this a configurable setting? A setting within the function https://github.com/xunit/xunit/blob/b592a1a475d1542b8e6598c6c704dd1da5fa2ffa/src/xunit.execution/Sdk/TypeUtility.cs#L182 to disable resolution of the parameter values would be more than enough. Maybe as a global config parameter. That way it would not break the new xunit2-default-behaviour but allows the option to get back the xUnit1-way of doing things. It would furthermore simplify xUnit1 -> xUnit2 upgrades and improve compatbility with other frameworks as NSubstitute and AutoFixture.

**Comment by evilbaschdi** [comment] 2019-02-11 14:58
any update on @dklinger s suggesetion?

**Comment by bradwilson** [comment] 2019-02-11 16:46
No, still not planning to do anything about this.

**Closed by bradwilson** 2019-02-11 16:46 UTC
Labels: status: By Design / Won't Fix
