### ISSUE TITLE
Theory arguments of a derived type cause first-chance InvalidCastException when debugging

### ISSUE THREAD

**Issue by EmperorXLII** [xunit/xunit#788] opened 2016-03-01 14:23 UTC
In the [`Xunit.Sdk.Reflector.ConvertArgument`](https://github.com/xunit/xunit/blob/fe8d78df7cfec55ddab93c29ea96b0032ca998a8/src/xunit.execution/Sdk/Reflection/Reflector.cs#L45) method, the if checks whether the argument exactly matches the parameter type, rather than if it is assignable.  This causes an unnecessary call to `Convert.ChangeType`, which will fail with an `InvalidCastException` if the argument is not `IConvertible`, even though the test method executes successfully.
 
Running this test method under the debugger with first-chance exceptions enabled will break before we enter the test method, and in the `Assert.Throws` call.
 
```
[Theory]
[MemberData("TestValues")]
public void Test2(object value)
{
    Type parameterType = typeof(object);
    Type argumentType = value.GetType();
 
    Assert.False(argumentType == parameterType);
    Assert.True(parameterType.IsAssignableFrom(argumentType));
    Assert.Throws<InvalidCastException>(() => Convert.ChangeType(value, parameterType));
}
 
public static IEnumerable<object[]> TestValues
{
    get { yield return new object[] { new TestData() }; }
}
 
private sealed class TestData { }
```

**Comment by Ausm** [comment] 2016-03-02 13:54
I think that's the same issue I had.
See: #770 and #771 
But I didn't find the call to ```Xunit.Sdk.Reflector.ConvertArgument```...

**Comment by EmperorXLII** [comment] 2016-03-02 13:56
Ah, maybe so!  I searched specifically for `InvalidCastException`, so I missed your post.

**Comment by Ausm** [comment] 2016-03-02 14:09
Yes, because it throwed a
```System.ArgumentException : Object of type '...' cannot be converted to type '...'.
StackTrace:    at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)...```
when I tested it.

**Comment by Porges** [comment] 2016-10-27 03:39
This is fixed in `master`, can be closed

**Closed** 2016-10-27 15:48 UTC

**Comment by Ausm** [comment] 2016-10-27 16:30
Are you really sure, that this is fixed?
The only difference I see in that function is that you use ```!type.IsAssignableFrom(arg.GetType())``` instead of ```arg.GetType() != type````.
But the problem was that you use ```Convert.ChangeType``` when the type of the argument isn't a array.
But for changing the type via ChangeType the object requires to be an ```IConvertible```, which it not necessarily is.
See [here](https://msdn.microsoft.com/de-de/library/dtb69x08(v=vs.110).aspx):
> Parameter
> value
> Type: System.Object
> An object that implements the IConvertible interface.

Or am I wrong here, and the problem is solved anywhere else?
