### ISSUE TITLE
Unable to resolve dependencies. 'xunit.abstractions 2.0.1'

### ISSUE THREAD

**Issue by Allann** [xunit/xunit#939] opened 2016-08-15 00:28 UTC
When installing xunit NuGet package, there is an update available.  However, trying to do the update produces the following error:

Unable to resolve dependencies. 'xunit.abstractions 2.0.1' is not compatible with 'xunit.extensibility.core 2.1.0 constraint: xunit.abstractions (= 2.0.0)'.

Extract from package.config:
```
  <package id="xunit" version="2.1.0" targetFramework="net461" />
  <package id="xunit.abstractions" version="2.0.0" targetFramework="net461" />
  <package id="xunit.assert" version="2.1.0" targetFramework="net461" />
  <package id="xunit.core" version="2.1.0" targetFramework="net461" />
  <package id="xunit.extensibility.core" version="2.1.0" targetFramework="net461" />
  <package id="xunit.extensibility.execution" version="2.1.0" targetFramework="net461" />

```

**Comment by bradwilson** [comment] 2016-08-15 00:31
Yep. Don't do that. :)

The DLLs are identical. The change is to support `netstandard`, which isn't officially supported with xUnit.net 2.1 (it will be in 2.2).

**Comment by Allann** [comment] 2016-08-28 04:47
Sorry @bradwilson that isn't really helpful.  Any chance you could fix the dependencies so that this doesn't continue?

**Comment by bradwilson** [comment] 2016-08-28 14:44
I'm not sure why you're demanding to upgrade something that doesn't need to upgraded. Just don't do it.

**Comment by Allann** [comment] 2016-08-29 08:01
i'm not demanding to upgrade.  When I go into the Nuget Package Manager screen and click on available updates, it appears as a possible upgrade.  But it isn't possible, it fails.  So whenever we need to do updates we have to always remember to uncheck it.

**Comment by onovotny** [comment] 2016-08-29 12:37
@Allann I would recommend switching your test project (all of your projects, really) to use `project.json` instead of `packages.config` as detailed here: https://oren.codes/2016/02/08/project-json-all-the-things/. Then you'll only see the top-level dependency (xunit) and the correct dependency versions will transitively be brought in.

**Comment by bradwilson** [comment] 2016-08-29 17:07
This behavior is by design. Complain to the @nuget team for creating a UI that encourages you to upgrade something that you didn't even ask for in the first place. ¯\_(ツ)_/¯

**Closed by bradwilson** 2016-08-29 17:07 UTC
