### ISSUE TITLE
xUnit1026 false positive with C# 12 collection literals

### ISSUE THREAD

**Issue by martincostello** [xunit/xunit#2789] opened 2023-09-29 15:30 UTC
Using C# 12 collection literals with .NET 8 can cause xUnit1026 false positives.

For example:

```csharp
public class FalsePositive
{
    [Theory]
    [InlineData("hello")]
    public void XUnit1026_False_Positive(string greeting)
    {
        string[] values = [greeting, "world"];
        string actual = string.Join(' ', values);
        Assert.Equal("hello world", actual);
    }
}
```

Produces this warning:

```
Theory method 'XUnit1026_False_Positive' on test class 'FalsePositive' does not use parameter 'greeting'. Use the parameter, or remove the parameter and associated data.
```

**Comment by bradwilson** [comment] 2023-10-29 18:29
This will need to wait until C# 12 is released (should be in the next month or so).

**Comment by JamesTerwilliger** [comment] 2023-12-04 05:33
The issue is that the Roslyn package needs to be updated to the latest. This PR fixes the issue and adds the above case as a test case:

https://github.com/xunit/xunit.analyzers/pull/174

**Comment by bradwilson** [comment] 2023-12-04 16:13
Given that we cannot upgrade past Roslyn 4.2.0 (see [xunit/xunit.analyzers](https://github.com/xunit/xunit.analyzers/pull/174#issuecomment-1838965194) for links), fixing this means we will need to investigate whether it can be fixed without bumping up the Roslyn version.

There is an available strategy that we could use to build a version of the analyzers with 4.8.0 so that we can run tests against C# 12 to verify the fix, while still shipping against 4.2.0. That assumes that we can fix the issue with 4.2.0, though. If we cannot fix the issue linked against 4.2.0, then we will likely be unable to fix the issue until January 2025 when VS 2022 17.8 (which is what correlates with Roslyn 4.8.0) becomes the lowest supported LTS version.

**Comment by bradwilson** [comment] 2023-12-14 23:59
@martincostello Please try `1.8.0-pre.13` and let me know if this resolves the problem for you. https://xunit.net/docs/using-ci-builds

Fix commit: https://github.com/xunit/xunit.analyzers/commit/7b8a772f5c4df014c5a3b1f34282e20be68bad08

**Comment by martincostello** [comment] 2023-12-15 12:20
With xunit 2.6.3, I can't replicate the issue anymore: https://github.com/martincostello/project-euler/pull/319

Appears _something_ has changed that fixed the issue without your specific fix in `1.8.0-pre.13`.

**Comment by martincostello** [comment] 2023-12-15 12:25
I guess this is something that got fixed in .NET between 8.0-rc.1 and 8.0.

**Comment by bradwilson** [comment] 2023-12-15 18:27
Well, one way or another, I guess this issue is done. 😄

**Closed by bradwilson** 2023-12-15 18:27 UTC
Labels: type: Feature, help wanted, area: Analyzers
