### ISSUE TITLE
Change of supported return types when upgrading from 2.4.x to 2.5.0

### ISSUE THREAD

**Issue by vguzmanp** [xunit/xunit#2748] opened 2023-07-10 07:50 UTC
Hi, we are upgrading to the latest version, (from 2.4.2 / 2.4.5 to 2.5.0) and we run into a regression.

We now receive this build error:
```
error xUnit1028: Test methods must have a supported return type. Valid types are: void, Task. Change the return type to one of the compatible types.
```

For this test:
```
[Theory]
[InlineData(false)]
[InlineData(true)]
public async Task<IEnumerable<byte[]>> SignDocumentsTest(bool flag, level level = level.LT, bool withTimestamp = true)
{
    [...]
    var documents = await WriteDocuments();
    [...]
    return documents;
}
```

We are testing a two-step process, where we need to generate some files as a byte[], then process something.
The second step is now just calling the first test and getting the returned list of byte arrays.

**Comment by ploeh** [comment] 2023-07-10 17:30
Apparently, this behaviour produces some false positives, as pointed out in https://github.com/fscheck/FsCheck/issues/636.

> The only types that have ever been supported are `void` and `Task`. What was added in 2.5.0 was an analyzer that alerted you to this fact.

This may be true for tests annotated with the `[Fact]` or `[Theory]` attributes, but since xUnit.net has a great extensibility API, it's possible to write tests in other ways. The [FsCheck.Xunit](https://www.nuget.org/packages/FsCheck.Xunit) library defines a [PropertyAttribute](https://github.com/fscheck/FsCheck/blob/master/src/FsCheck.Xunit/PropertyAttribute.fs#L113) that supports other return types, which are useful when defining properties using various combinators.

```csharp
[Property(MaxTest = 250)]
public Property Merging_2_finite_adjacent_DateRanges_properties() {...}
```

(Example copied from https://github.com/fscheck/FsCheck/issues/636#issuecomment-1629264440.)

May I suggest that the analyser only considers `[Fact]` and `[Theory]`, but not third-party attributes that derive from `FactAttribute`?

There could be other third-party libraries that also extend `FactAttribute` to support other return types, so this need not only be an issue with FsCheck.Xunit.

Thank you for a great testing framework.

**Comment by bradwilson** [comment] 2023-07-10 20:50
> May I ask what problems this can cause?

The _primary_ motivation is that returning `ValueTask` causes false positives (per #2733), because developers may believe it is supported when it isn't.

**Comment by bradwilson** [comment] 2023-07-10 20:54
> given it was a minor update

Our v1 and v2 versioning system is 14 years old. It predates SemVer. You cannot make a SemVer-based assumption about the scope of changes based on the version.

For v3, we're moving to SemVer (with renamed packages and verisoning).

**Comment by bradwilson** [comment] 2023-07-12 02:37
I'm going to close this as "by design", with the caveat of having opened #2749 for @ploeh's extensibility issue.

**Closed** 2023-07-12 02:37 UTC
Labels: status: By Design / Won't Fix

**Comment by Tr00d** [comment] 2023-07-13 06:49
I guess v2.5.0 should have been a major version, given this was a breaking change. It will be a non-issue after the mentioned extensibility.
Looking forward to it, and keep up the great work 👏
