### ISSUE TITLE
Open test log has error

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [xunit/xunit#2373] opened 2021-09-05 10:34 UTC
A large file name with a generic test class has an exception when I click on 'Open test log' in Test explorer:

```
ctoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\AppData\Local\Temp\Utravs.Hub.SepehrFlight.Tests.BookConfirm.OneWay.OneWayBookConfirmTest.BookingConfirm(origin_ _THR_, destination_ _MHD_, adultCount_ 2, childCount_ 0, infantCount_ 0, responseType_ Separated)-637664509866076558.testlog'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Microsoft.VisualStudio.TestWindow.Internal.UI.Summary.SummaryBuilder.<BuildSummaryLogFileAsync>d__108.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Internal.Commands.OpenTestLogCommands.<>c__DisplayClass7_0.<<OnInvokeOpenFullTestLogAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Internal.Commands.OpenTestLogCommands.<<OnInvokeOpenFullTestLogAsync>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by bradwilson** [comment] 2021-09-08 04:04
Can you provide a repro project? This partial stack trace isn't enough for me to work from.

**Comment by HaavardL** [comment] 2022-01-28 12:45
I have a similar problem. If my test method has more than 8 arguments the testlog is not created/saved and I get an error dialog when clicking 'Open test log'. <=8 arguments work OK.
I'm using xUnit in VS2022 Preview.

**Comment by HaavardL** [comment] 2022-01-28 13:42
@bradwilson It looks like the additional log file is not created if the generated filename (or total filepath) is to long. 
The filename is generated from projectname, classname, methodname, argumentnames and argumetnvalues.

**Comment by bradwilson** [comment] 2022-02-02 18:39
I still require a repro project. There is not enough information in this bug for me to understand what the problem is.

**Comment by bradwilson** [comment] 2022-02-02 18:40
Also, my gut tells me that this is a VSTest bug. We don't generate test logs, and we have nothing to do with any test log UI in Visual Studio.

**Comment by keystroke** [comment] 2022-04-12 03:20
I'm also having this issue with test explorer in Visual Studio, here is screenshot of the problem:

![image](https://user-images.githubusercontent.com/2002281/162872830-f31982bf-85cb-457a-a0a4-354d72741793.png)

When I select the "Open Test Log" option from Visual Studio Test Explorer after the test has run, I get above error message referencing a path which looks to be way too long. The file path described in the error message does not exist on disk; in fact, the target folder is completely empty. It looks to be related to xunit and using the theory and inline data test attributes which seem to somehow induce a "target test file name" which may be something in the test explorer itself? Does xunit provide some target test name to the runner for this?

**Comment by bradwilson** [comment] 2022-04-12 14:54
Closing this issue as it's a bug in Visual Studio, not xUnit.net.

**Closed by bradwilson** 2022-04-12 14:54 UTC
Labels: status: Waiting for Repro/Response
