### ISSUE TITLE
vs2017 release 15.2 - Test source code not found and project marked as "external"

### ISSUE THREAD

**Issue by bragma** [xunit/xunit#1295] opened 2017-05-22 08:48 UTC
Hi,
after installing the latest vs2017 and converting an existing project (ASP NET Core, .NET Framework) with 1000+ tests, most of them are now marked as "external" in "view by project" and no source code is associated with them (when clicking on the code name).
I've not been able to reproduce it on a sample project, but it seems somehow to be related with async (await) operations in the test. Fiddling with the test code (i.e. removing some code using await at the end of the test) I've managed to make the test being recognized.
Is this a known issue? I've found some references to similar problem but for VS2017 RC and were marked as solved.
Thanks

**Comment by onovotny** [comment] 2017-05-22 12:33
Do you have a repro? That said, the metadata reader is part of vstest so bugs would likely need to be here https://github.com/Microsoft/vstest

**Comment by bragma** [comment] 2017-05-22 14:27
Hi, sadly I cannot share the project where the problem happens. I've tried to reproduce the problem with a sample project but to no avail. In any case, thanks for pointing me to the correct repository, I'll give a look there.

**Comment by bradwilson** [comment] 2017-05-22 18:16
This typically happens because you have wrong `DebugType` in your project.

Desktop & UWP projects need `full`.
.NET Core projects need `portable`.

If you're multi-targeting (desktop + .NET Core), use MSBuild `Condition=` on these to ensure you get the right type.

https://github.com/xunit/xunit/blob/9a18a005bef44aa160104e63b039ec2b591b4f36/src/xunit.core/build/xunit.core.props#L12-L26

**Comment by bragma** [comment] 2017-05-23 09:42
@bradwilson thanks but I've not fully understood. My project is ASP NET Core, but it's targeting .NET Framework 4.6. It seems I should use full, as it is but it does not work. Do I need  to force it to use portable? If I try to do so from the "advanced" section of the project properties, it reverts back to "full.

**Comment by bradwilson** [comment] 2017-05-23 16:02
@bragma Sounds like we will need a repro project.

**Comment by bragma** [comment] 2017-05-24 10:43
@bradwilson I'll try to make a repro as soon as I have some time, since it seems that there is some work involved in causing the problem, not just creating a sample project and adding a test.
My latest investigations (notice the last line):

```
		[Fact]
		public async Task CreateBrand()
		{
			// This line is ok
			Assert.True(await Task.FromResult(true));

			// This line is ok
			var y = new Brand();

			// This line is not, must be commented to make the test being recognized
			var x = await Task.FromResult(new Brand());
		}
```

"Brand" is a class defined in the tested project.

**Comment by Faizan2304** [comment] 2017-05-25 05:15
@onovotny : You can repro this with https://github.com/aspnet/Mvc or any of the asp.net repos. 
If I am changing Xunit version to 2.2.0 [Here](https://github.com/aspnet/Mvc/blob/dev/build/dependencies.props#L15) source information starts coming (Some projects fail to build but the project which pass get discovered and source information for those tests are there)

**Comment by Faizan2304** [comment] 2017-05-25 05:34
@onovotny : You can also repro it with vanilla xunit project

## Csproj of Test project
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170517-02" />
    <PackageReference Include="xunit" Version="2.3.0-beta2-*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>

</Project>
```

## Test Code:
```csharp
using System;
using System.Threading.Tasks;
using Xunit;

namespace XUnitTestProject2
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {

        }
    }
}
```

**Comment by RehanSaeed** [comment] 2017-09-20 13:45
In my case using `IClassFixture<T>` causes the test to be marked as `External`. This is using the latest beta5 release with 15.3.0 of Microsoft.NET.Test.Sdk.

**Comment by bradwilson** [comment] 2017-09-20 19:26
Does this still repro with:

- Visual Studio 15.3.5
- `Microsoft.NET.Test.SDK` version `15.3.0`
- `xunit` and `xunit.runner.visualstudio` version `2.3.0-beta5-build3769`

?

**Comment by bradwilson** [comment] 2017-09-20 19:27
(I'm trying to understand if this is an issue with Visual Studio 15.2 that's already been fixed, since I don't have access to 15.2 any more)

**Comment by RehanSaeed** [comment] 2017-09-22 13:54
I'm using the latest VS 15.3.3 (I guess 15.3.5 is the preview?), version `15.3.0` of `Microsoft.NET.Test.Sdk` and `xunit`, `xunit.runner.visualstudio` version `2.3.0-beta5-build3769`.

I've just tried creating a repro project by cutting down my work project but have been unable to recreate so far.

**Comment by marcoregueira** [comment] 2017-11-02 09:21
Hi @bradwilson. It still reproduces with the last official (15.4.1) and last preview (15.0.1 preview 2.0)
I have not tested the demo project from @Faizan2304, but in my case all tests returning an "async Task" are marked as "External" and the remaining are grouped properly with their projects, which seems to reinforce the @bragma's thesis.

**Comment by bradwilson** [comment] 2017-11-02 09:35
We use `IClassFixture<T>` in our [integration test project](https://github.com/xunit/xunit.integration/blob/master/test-explorer/v2x_net452/FixtureWithMixedFactAndTheory.cs), and the source information all shows up as expected:

![Source Information](https://user-images.githubusercontent.com/16944/32318996-3ebe0dd6-bf76-11e7-8096-74166763281b.png)

Whatever's going on here is clearly more complex than just adding `IClassFixture`. Can anybody provide a simple repro project? Or, alternatively, the people who are having the problem: does the problem also reproduce for you with our integration test project? If so, then that would indicate that there is something broken with your Visual Studio installation as opposed to our integration.

**Comment by marcoregueira** [comment] 2017-11-02 09:36
Just to complete the picture. @Faizan2304 @bradwilson 
I'm seeing some differences using the VS test explorer and Resharper's test explorer.

- Using VS, all tests returning "async Task" are marked as external and double-clicking doesn't open the test code nor the file. Non async tests are properly grouped and can be navigated to.

- Using Resharper, all tests appear properly grouped by project but double-clicking them doesn't go to the test code. You can still go to the file containing the test, but not to the test itself, and this seems to happen for ALL the tests in the solution.

**Comment by bradwilson** [comment] 2017-11-02 09:37
Any issues with Resharper should be reported to them. We do not create, nor support, the Resharper xUnit.net integration; JetBrains does.

**Comment by marcoregueira** [comment] 2017-11-02 09:40
Sure. I understand that, but I suppose both resharper and VS get the data from the same API. Or maybe not. I don't know the internals and I'm not able to judge. I just highlight the difference for the case it might bring some light on where the source of the problem is. If it is unuseful input, just disregard it, please.

**Comment by bradwilson** [comment] 2017-11-02 09:41
> Using VS, all tests returning "async Task" are marked as external and double-clicking doesn't open the test code nor the file. 

I cannot reproduce this, either. All three supported test modes (non-async `void`, `async void`, and `async Task`) all work fine with source information. The `BasicTests` file in our integration tests contains examples of these which also show up as expected in Test Explorer.

**Comment by bradwilson** [comment] 2017-11-02 09:42
> Sure. I understand that, but I suppose both resharper and VS get the data from the same API.

Actually, they don't. Resharper has its own parser that does not work like any other test runner, and can be a source of differences/bugs.

**Comment by marcoregueira** [comment] 2017-11-02 09:42
Understood.

**Comment by bradwilson** [comment] 2017-11-11 18:28
Too many issues in one bug. Please open a new issue if there are still problems with 2.3.1.

**Closed by bradwilson** 2017-11-11 18:28 UTC
