### ISSUE TITLE
xunit.runner.visualstudio cannot be used with MVC in test projects unless you add a reference to Microsoft.DotNet.InternalAbstractions.

### ISSUE THREAD

**Issue by NTaylorMullen** [xunit/xunit#1088] opened 2017-02-03 00:28 UTC
MVC depends on `Microsoft.Extensions.DependencyModel` 1.2.0 and `xunit.runner.visualstudio` depends on version 1.1.0. In 1.1.0 it had a dependency on `Microsoft.DotNet.InternalAbstractions` 1.0.0. The goal of this dependency at the time was to not be used and to be treated as "internal". Therefore, in 1.2.0 the `Microsoft.DotNet.InternalAbstractions` dependency disappeared. Xunit used something from the internal abstractions so when MVC lifts `Microsoft.Extensions.DependencyModel` to 1.2.0 you get a file not found exception:

```
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Warning: [xUnit.net 00:00:03.9860811] Exception discovering tests: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetAvailableRunnerReporters(IEnumerable`1 sources)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetRunnerReporter(IEnumerable`1 assemblyFileNames)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IRunSettings runSettings, IEnumerable`1 sources, LoggerHelper logger, Func`4 visitorFactory, Action`4 visitComplete)



Error: [xUnit.net 00:00:04.0416376] Catastrophic failure: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetAvailableRunnerReporters(IEnumerable`1 sources)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetRunnerReporter(IEnumerable`1 assemblyFileNames)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTests(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, Func`1 testCaseAccessor)



Warning: No test is available in C:\Users\nimullen\Documents\GitHub\Mvc\test\Microsoft.AspNetCore.Mvc.FunctionalTests\.\bin\Debug\netcoreapp1.1\Microsoft.AspNetCore.Mvc.FunctionalTests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```

This could be fixed by removing the usage or lifting `xunit.runner.visualstudio`'s `Microsoft.Extension.DependencyModel` to 1.2.0.

**Comment by bradwilson** [comment] 2017-02-03 03:16
Duplicate of #1080

**Closed by bradwilson** 2017-02-03 03:16 UTC
