### ISSUE TITLE
Xunit 2.4 Console Runner and StoryQ logging

### ISSUE THREAD

**Issue by zein-makki** [xunit/xunit#1849] opened 2018-11-07 21:47 UTC
We use [StoryQ ](https://github.com/wforney/storyq)to write some of our test suites and after upgrading from Xunit 1.9 to 2.4 we started seeing too many logs being written by the tests on the build server. Previously with Xunit 1.9, only the failures would be reported in the console logs. Note that the `-quiet` switch doesn't change the output in this case for the 2.0+ xUnit Runner.

Here is a screenshot comparing the two behaviors (XunitRunner_OLD Vs. XunitRunner) : 

![image](https://user-images.githubusercontent.com/25294002/48160908-d7275c00-e2e1-11e8-971d-201db8684fd5.png)

We understand that this might be due to the way StoryQ writes the logs, and we understand that xunit has changed the capturing of the logs starting 2.0 . What we need to know is if this is an issue with xUnit and if there is any way around it.

For Reference:
- This is the suspected [class](https://github.com/wforney/storyq/blob/02c44c786c691025695ac61e4d6afb6b525040df/src/StoryQ/Infrastructure/FragmentBase.cs) that is writing the logs using `Console.Out `
- We're using StoryQ 2.0.5
- Here is a repo [project](https://github.com/zein-makki/XunitStoryQLogging).

**Comment by bradwilson** [comment] 2018-11-07 22:47
xUnit v2.x does not capture console output. This is a breaking change from v1.x.

**Comment by zein-makki** [comment] 2018-11-12 14:14
@bradwilson Any updates on this one ?

**Comment by bradwilson** [comment] 2018-11-12 16:03
What further updates are you expecting? We used to capture console output in 1.x, and we don't in 2.x. What you're seeing is the expected behavior.

**Comment by zein-makki** [comment] 2018-11-12 16:35
@bradwilson I'm not sure we're on the same page. What I'm saying in the description of the issue is that we're seeing **more** logs in the 2.x Runner.. Is that expected ?

**Comment by bradwilson** [comment] 2018-11-12 16:54
Yeah. What you're seeing is the console output from StoryQ, which was previously being captured (and thus hidden) in 1.x.

**Comment by zein-makki** [comment] 2018-11-12 17:45
Thank you @bradwilson 
So there is no way around this other than generating a modified StoryQ binaries ?. If that's the case, I'll close this issue.
_(The confusion in the previous comments was that I thought that by capturing you meant capturing and redirecting to the Console and not Capturing and ignoring)_

**Comment by bradwilson** [comment] 2018-11-12 17:50
"Capturing" means that it captured (without echoing) the console output and assigned it to the test. With the parallelization now, it's impossible to know which test to assign console output to (since many can be running at the same time), so we removed that feature, and the console output therefore ends up just on the console.

**Closed** 2018-11-12 18:18 UTC
