### ISSUE TITLE
Isolate the different threads in parallel execution to allow for assembly globals

### ISSUE THREAD

**Issue by perbergland** [xunit/xunit#1752] opened 2018-06-25 18:50 UTC
We have some hard-to-change assembly globals which blocks us from running tests in parallel. If xUnit supported more isolation between the test threads, e.g. by setting up a new appdomain for each runner thread, we would be much happier.

**Comment by perbergland** [comment] 2018-06-25 20:39
Yeah not surprised - appdomains have been on the chopping block for a while. It’s still problematic with globals when prallelising tests but there are no obvious solutions. Or are there?

**Comment by perbergland** [comment] 2018-06-25 20:49
I wonder if a solution is to use SynchronizationContexts…
Do I have any control over the threads created by xunit, eg to set the context?

https://blogs.msdn.microsoft.com/pfxteam/2012/01/20/await-synchronizationcontext-and-console-apps/

**Comment by bradwilson** [comment] 2018-06-25 21:11
This sample is probably the closest to showing you how you'd go about making a change like this: https://github.com/xunit/samples.xunit/tree/master/PartialTrustExample

It's not trivial.

**Comment by bradwilson** [comment] 2018-07-01 15:30
Closing this as By Design. Hopefully the link helps you get what you're after.

**Closed by bradwilson** 2018-07-01 15:30 UTC
