### ISSUE TITLE
MemberData using another Class' method requires a dummy method in the test class

### ISSUE THREAD

**Issue by R1DEN** [xunit/xunit#1976] opened 2019-06-26 09:26 UTC
If i want to make the dataprovider for a test method to be a method from another class, i am required to have a dummy method in the test class with the same method as in the real TestDataGenerator class.

TestDataGenerator class:

```
public static IEnumerable<object[]> GetDataForCreateObjectBusinessLogic()
        {
            ...
        }
```

Example 1:

TestClass
```
[Theory]
[MemberData(nameof(GetDataForCreateObjectBusinessLogic), MemberType = typeof(TestDataGenerator))]
public void CreateObjectBusinessLogicTest(TestCaseFromCSV testCaseFromCSV) {...}
```

This one shows an Error in the xUnit attribute:
`xUnit1015	MemberData must reference an existing member '' on type '.../TestDataGenerator'`

Example 2 (the TestDataGenerator class remains the same):

TestClass
```
[Theory]
[MemberData(nameof(GetDataForCreateObjectBusinessLogic), MemberType = typeof(TestDataGenerator))]
public void CreateObjectBusinessLogicTest(TestCaseFromCSV testCaseFromCSV) {...}

private object GetDataForCreateObjectBusinessLogic()
  {
      throw new Exception();
  }

```

Now it works, however it doesn't use this method at all, since my tests run exactly as they did when using a Class type data provider, and no exceptions are thrown.

**Comment by raterus** [comment] 2019-10-02 18:37
You can do this already by referencing your other class in the nameof(), e.g. "TestDataGenerator.GetDataForCreateObjectBusinessLogic"

`[Theory]
[MemberData(nameof(TestDataGenerator.GetDataForCreateObjectBusinessLogic), MemberType = typeof(TestDataGenerator))]
public void CreateObjectBusinessLogicTest(TestCaseFromCSV testCaseFromCSV) {...}`

**Comment by josefblaha** [comment] 2020-10-04 18:08
@R1DEN, your Example 1 does not compile as-is, because of  ``error CS0103: The name 'GetDataForCreateObjectBusinessLogic' does not exist in the current context``.

Did you forgot to mention ``using static yournamespace.TestDataGenerator`` in your Example 1? Or do you expect the Xunit analyzer to give you a better error message even if the code does not compile?

**Comment by Jenn712** [comment] 2022-10-25 08:36
My myspace was static beauty

**Comment by bradwilson** [comment] 2023-01-22 23:30
I have verified that both `nameof(Foo.Bar)` and `using static Foo;` + `nameof(Bar)` incorrectly trigger xUnit1015.

**Comment by sdelarosbil** [comment] 2023-03-10 19:14
hey @bradwilson I tried to reproduce the issue, but despite following as much as I could, I was not able to, are you able to still reproduce this now?

**Comment by bradwilson** [comment] 2023-03-10 23:21
@sdelarosbil I cannot repro this now. My best guess is that in trying to quickly repro this, I accidentally left off the `MemberType` property.

Without `MemberType`:

![image](https://user-images.githubusercontent.com/16944/224446021-134a9c92-47fa-4f6e-b341-178af9f2a6a9.png)

With:

![image](https://user-images.githubusercontent.com/16944/224446130-cb372c96-b3c5-4e54-b512-f5a3e4bfac43.png)

Since @R1DEN doesn't have access to the original repro and I can no longer reproduce this, I'm going to close the issue.

**Closed by bradwilson** 2023-03-10 23:21 UTC
Labels: type: Bug, help wanted, area: Analyzers, good first issue

**Comment by AMEZING77** [comment] 2024-09-14 09:13
Got it
