### ISSUE TITLE
[assembly: CollectionBehavior(DisableTestParallelization = true)] does not work

### ISSUE THREAD

**Issue by suwatch** [xunit/xunit#379] opened 2015-04-01 07:21 UTC
I put this assembly attribute in my AssemblyInfo.cs in order to make all my tests in this assembly to run sequentially - somehow, they are still running in parellel.   

If I do below, then it works (run sequentially).   I must misunderstand something.

`[assembly: CollectionBehavior(CollectionBehavior.CollectionPerAssembly)]`

**Comment by wholroyd** [comment] 2015-04-03 18:12
There was a nullable issue between where the attribute was discovered and where it needed to honor that flag when it went to build the collections and run them.

This issue was fixed in #276. Can you verify that the issue is resolved by upgrading to RC2 or newer?

**Comment by suwatch** [comment] 2015-04-03 18:19
Great to know.  I have added comment to our codes.   We will sure try with the RC when we get a chance.

**Comment by wholroyd** [comment] 2015-04-03 18:22
What framework version are your projects targeting?

If you're not using ASP.NET 5, the xunit framework has reached RTM for 2.0. I'd suggest going with that version instead.

If you are using ASP.NET 5, stay with either a newer RC, or go to the 2.1 Beta.

**Comment by suwatch** [comment] 2015-04-03 18:31
We are targeting ASP.NET 4.

**Comment by wholroyd** [comment] 2015-04-03 18:32
Good to hear for the 2.0 RTM. Let us know if your issue is resolved.

**Comment by bradwilson** [comment] 2015-04-06 22:59
Closing for now. Please re-open if you have any further issues.

**Closed by bradwilson** 2015-04-06 22:59 UTC
