### ISSUE TITLE
Unable to install the NuGet package xunit.runner.console in VS 2015

### ISSUE THREAD

**Issue by MarkKharitonov** [xunit/xunit#1784] opened 2018-08-15 01:17 UTC
I am using VS 2015 Enterprise Update 3.

My project targets the .NET framework 4.6.1.

Here is what I get in the PM console inside VS IDE:
```
PM> Install-Package xunit.runner.console


Attempting to gather dependency information for package 'xunit.runner.console.2.4.0' with respect to project 'MSBuildEventLogFileToolTests', targeting '.NETFramework,Version=v4.6.1'
Install-Package : An error occurred while retrieving package metadata for 'xunit.abstractions.2.0.2' from source 'C:\Dayforce\MSBuildEventLogger\packages'.
At line:1 char:1
+ Install-Package xunit.runner.console
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:00.2142704
PM> 
```

**Comment by bartelink** [comment] 2018-08-15 09:50
> `'C:\Dayforce\MSBuildEventLogger\packages'.`
This suggests its worth clearing down your local packages folder and retrying (and/or checking whether others experience the same issue with the same codebase)

**Comment by filsanet** [comment] 2018-08-17 07:38
I am getting this same error, when I attempt to install xunit.runner.console v2.4.0. 

As @ChristophHornung  suggests, it looks like it is related to #1786.

My workaround for now is to remove the v2.4.0 xunit and install the previous version, 2.3.1. This is working for me for now.

**Comment by bradwilson** [comment] 2018-08-21 21:49
Resolving as duplicate of #1786 (which describes the issue and fix).

**Closed by bradwilson** 2018-08-21 21:49 UTC
