### ISSUE TITLE
Also v2.6.2 breaks existing test (Assert.Equal on Dictionary with null values)

### ISSUE THREAD

**Issue by gioce90** [xunit/xunit#2837] opened 2023-12-05 15:47 UTC
I have a similar problem to #2821. 
Every version of `xunit.assert` and `xunit` > `2.5.3 `give me an error, also with the `2.6.2`.

I tested with version 2.6.2 (of both `xunit.assert` and `xunit`), and I think there is still a problem with collections like Dictionary when there is a Value field with null value.

This is my first test, that is totally fine:
```
        [Fact]
        public void MyTest__OKAY()
        {
            IDictionary<string, string> dict1 = new Dictionary<string, string>
            {
                { "A", "The" },
                { "B", "empty" },
                { "C", "" },
                { "D", "test" },
                { "E", "is" },
                { "F", "OKAY" },
            };
            IDictionary<string, string> dict2 = new Dictionary<string, string>
            {
                { "A", "The" },
                { "B", "empty" },
                { "C", "" },
                { "D", "test" },
                { "E", "is" },
                { "F", "OKAY" },
            };
            Assert.Equal(dict1, dict2);
            Assert.Equal(dict2, dict1);
        }
```

This second one instead, where i just put a null value, fails:
```
        [Fact]
        public void MyTest__WRONG()
        {
            IDictionary<string, string> dict1 = new Dictionary<string, string>
            {
                { "A", "The" },
                { "B", "null" },
                { "C", null },
                { "D", "test" },
                { "E", "is" },
                { "F", "NOT" },
            };
            IDictionary<string, string> dict2 = new Dictionary<string, string>
            {
                { "A", "The" },
                { "B", "null" },
                { "C", null },
                { "D", "test" },
                { "E", "is" },
                { "F", "NOT" },
            };
            Assert.Equal(dict2, dict1);
            Assert.Equal(dict1, dict2);
        }
```

But if I go back to version "2.5.3", both tests are fine. I think I've found another regression here.

**Comment by ladeak** [comment] 2023-12-05 18:01
Duplicate of https://github.com/xunit/xunit/issues/2824

**Closed** 2023-12-05 18:57 UTC
Labels: status: Duplicate
