### ISSUE TITLE
New project does not build in Visual Studio 2015

### ISSUE THREAD

**Issue by staff0rd** [xunit/xunit#590] opened 2015-09-15 09:50 UTC
I've added a new Class Library package targeting DNX SDK 1.0.0-beta7, and ran the following;

```
PM> install-package xunit -pre
Installing NuGet package xunit.2.1.0-rc2-build3170.
Successfully installed 'xunit.2.1.0-rc2-build3170' to EntityFramework.Extensions
```

Then I added this test;

```
using Xunit;
namespace Fanatics.Tests
{
    public class TestOne
    {
        [Fact]
        public void Test_One()
        {
            Assert.True(true);
        }
    }
}
```

But the project won't compile;

~~~
1>C:\Tests\TestOne.cs(7,10,7,14): DNX 4.5.1 error CS0012: The type 'Attribute' is defined in an assembly that is not referenced.You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
1>C:\Tests\TestOne.cs(10,20,10,24): DNX 4.5.1 error CS0012: The type 'Object' is defined in an assembly that is not referenced.You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
1>C:\Tests\TestOne.cs(10,13,10,24): DNX 4.5.1 error CS0012: The type 'Nullable<>' is defined in an assembly that is not referenced.You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
~~~

**project.json**

~~~
  "version": "1.0.0-*",
  "description": "Tests Class Library",
  "authors": [ "stafford" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
    "frameworks": {
        "dnx451": { },
        "dnxcore50": {
            "dependencies": {
                "Microsoft.CSharp": "4.0.1-beta-23225",
                "System.Collections": "4.0.11-beta-23225",
                "System.Linq": "4.0.1-beta-23225",
                "System.Runtime": "4.0.21-beta-23225",
                "System.Threading": "4.0.11-beta-23225"
            }
        }
    },
    "dependencies": {
        "xunit": "2.1.0-rc2-build3170"
    }
~~~

**Comment by bradwilson** [comment] 2015-09-17 16:27
This is a duplicate of https://github.com/xunit/xunit/issues/545 (whose title would've give you no indication that it was related :-p).

Short answer: this is [a bug in DNU](https://github.com/aspnet/dnx/issues/2387), which is being fixed for beta 8.

**Closed** 2015-09-19 18:15 UTC
Labels: [r] Duplicate, [r] External
