### ISSUE TITLE
Unable to run tests for Windows Phone 8.1

### ISSUE THREAD

**Issue by nelsonghezzi** [xunit/xunit#277] opened 2015-01-28 14:02 UTC
I'm trying to create a test project for a PCL that targets W8.1/WP8.1, using the latest pre-release of xUnit 2 (RC1), but the tests fails to run.

I've setup the test project following the steps in [this article] (http://blog.novotny.org/2014/08/11/now-shipping-xunit-support-for-windows-8-and-windows-phone-app-8-1/), but using the Nuget-based Visual Studio runner instead of the -deprecated- VS Extension.

Steps to reproduce this issue:
1. Create a new **Unit Test App (Windows Phone)** project.
2. Remove reference to **MSTestFramework**.
3. Right click the solution item in the *Solution Explorer* and select *Configuration Manager...* and change the target platform of the project to *x86*.
4. Install package xunit, version **2.0.0-rc1-build2826**.
5. Install package xunit.runner.visualstudio, version **2.0.0-rc1-build1030**.
6. Replace the content of the **UnitTest1.cs** file with the following code:

    using Xunit;

    namespace xUnit.WindowsPhone.Sample
    {
        public class UnitTest1
        {
            [Fact]
            public void TestMethod1()
            {
                Assert.True(true);
            }
        }
    }

6. At this point, build the project. The *Test Explorer* window should display the discovered test.
7. Run the test.
8. The *Output* window shows the following information:

------ Run test started ------
Deploying to Phone Internal Storage...

Updating the layout...

Registering the application to run from layout...

Deployment complete (2495ms). Full package name: "50741b91-724e-4adc-a769-4a7f780e62a2_1.0.0.0_x86__4xw3mn7d00ecc"

Could not find test executor with URI 'executor://xunit/VsTestRunner2'.  Make sure that the test executor is installed and supports .net runtime version .
========== Run test finished: 0 run (0:00:09,4816448) ==========

**Additional environment information**
Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51650

Regards.

**Comment by bradwilson** [comment] 2015-01-29 20:31
The issue is the targets files had the wrong name in them. This will be fixed in the next drop.

**Closed** 2015-01-29 20:31 UTC
Labels: Bug

**Comment by nelsonghezzi** [comment] 2015-01-30 15:16
Thanks @bradwilson, I'm glad to hear that.

Hope the next release is coming out soon!

Cheers!
