### ISSUE TITLE
Catastrophic failure: System.Runtime.InteropServices.COMException : The specified test case was not found in the current result context.

### ISSUE THREAD

**Issue by craig-wagner** [xunit/xunit#467] opened 2015-07-15 00:49 UTC
In Visual Studio 2013 our xUnit-based tests run just fine. I recently opened the solution in Visual Studio 2015 RC and tried running the tests. In the Output pane I get several of the following errors:

> Catastrophic failure: System.Runtime.InteropServices.COMException : The specified test case was not found in the current result context.

Not sure if it's an xUnit runner issue or a VS 2015 issue so thought I'd start here. Happy to provide any additional information if you can tell me where to look.

**Comment by bradwilson** [comment] 2015-07-15 01:19
Duplicate of https://github.com/xunit/visualstudio.xunit/issues/72 (a bug in VS 2015)

**Closed by bradwilson** 2015-07-15 01:19 UTC

**Comment by craig-wagner** [comment] 2015-07-15 14:10
I looked at #72 and #71 (which #72 references) and they both referenced running 1.9.2 tests. We upgraded all of our unit test projects and libraries to xUnit v2 quite a while back.

They also indicate that the tests run successfully which is not happening in our case. We end up with over a thousand tests in the Not Run state after the test run completes, and right-clicking on a single test and selecting Run Selected Test results in nothing being run.

It may still be a VS bug but the symptoms appear to be different than the referenced issue.

**Comment by bradwilson** [comment] 2015-07-15 15:12
Are the catastrophic failures for the tests that show as "not run"? If so, then that means they were run, but Visual Studio refuses to accept the result.

There are only a couple ways that I'm aware of that you can make this happen:

1. In xUnit.net 1.9.2, all theories make this happen, though they should always report the results correct. In xUnit.net 2.0, any theory which does not have serializable data, or if you've turned off pre-enumeration of theory data, will also cause this to happen.
2. In xUnit.net 2.0, if you are pre-enumerating non-stable (i.e., random) data, in versions of Visual Studio prior to 2015, the "Run All" gesture tells the test runner to re-discover tests and run them. This means the newly discovered theories with have different data elements, and therefore Visual Studio will claim (correctly, in this case) that you are reporting results for a test it doesn't know anything about. This is actually your fault, not Visual Studio's, and can be fixed by either turning off all theory pre-enumeration, or at least by instructing the data attribute generating random data that it should not pre-enumerate that data.

**Comment by craig-wagner** [comment] 2015-07-16 20:39
Unfortunately I can't tell which tests the failures are showing for. I literally get:

> Catastrophic failure: System.Runtime.InteropServices.COMException : The specified test case was not found in the current result context.

Repeated 69 times in the output window. No additional details.

The "Not Run" test count shows 1357 tests (out of 4583 total). Some of them are Theory tests, some are Fact tests. If I try to debug one of the "Not Run" tests my breakpoints never get hit.

I went through all our unit test projects and added the following to the app.config.

    <add key="xunit.diagnosticMessages" value="true"/>

That allowed me to narrow it down at least to which unit test projects were generating the errors. Then through trial-and-error I managed to find some of the tests that were generating the messages. One of them is:

	[Theory]
	[InlineData("UserName", typeof(RequiredAttribute))]
	[InlineData("FirstName", typeof(RequiredAttribute))]
	[InlineData("LastName", typeof(RequiredAttribute))]
	[InlineData("Password", typeof(RequiredAttribute))]
	[InlineData("Password", typeof(RegularExpressionAttribute))]
	[InlineData("ConfirmPassword", typeof(CompareAttribute))]
	[InlineData("EmailAddress", typeof(RequiredAttribute))]
	[InlineData("EmailAddress", typeof(RegularExpressionAttribute))]
	[InlineData("ConfirmEmailAddress", typeof(CompareAttribute))]
	[InlineData("SecurityQuestion", typeof(RequiredAttribute))]
	[InlineData("SecurityQuestionAnswer", typeof(RequiredAttribute))]
	public void RegisterRequest_ExpectedPropertiesAndAttributesExist(string propertyName, Type attributeType)
	{ ValidateExpectedPropertyExistsWithAttribute(typeof(RegisterRequest), propertyName, attributeType); }

The above test passes for `[InlineData("SecurityQuestionAnswer", typeof(RequiredAttribute))]` and generates the `Catastrophic failure` message for the other 10 values.

The other tests that I've found so far are similarly structured, but I haven't been able to identify all of the tests.

The other strange thing is that the tests that are showing as "Not Run" are not the tests generating the `Catastrophic Failure` message. The "Not Run" tests seem to be all the tests in three of our unit test assemblies. They're obviously being discovered because they show up in Test Explorer but they just will not run, even when I right-click on them and select "Run Test".
